### ISSUE TITLE
Locator cleanup

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#129]
~~https://git.rudin.io/minetest/locator~~ https://github.com/pandorabox-io/locator

## Goal

* Remove old entries by checking periodically if a beacon still exists

**Comment by BobFred7** [comment]
The URL is a 404 now, so it doesn't provide much information

**Comment by OgelGames** [comment]
It was moved here: https://github.com/pandorabox-io/locator

**Comment by thomasrudin** [comment]
> The URL is a 404 now, so it doesn't provide much information

my mistake, forgot to change the url after migration... :P

**Comment by BuckarooBanzay** [comment]
replaced by https://github.com/pandorabox-io/locator/issues/1
