### ISSUE TITLE
Complete modlist?

### ISSUE THREAD

**Issue by Guard13007** [pandorabox-io/pandorabox.io#141]
Is there anyway I can get a complete modlist for the server? I have been trying to figure it out from this repo/the site/the forum post/in-game but I only have a general idea of most of the mods.

Additionally, would it be possible to get more info about what is enabled/disabled within mods? I could be wrong but it looks like the digilines RTC is disabled? I'd also like to know what is considered acceptable with respects to programming/using blocks that may cause lag. I saw in server chat at one point to use a 3 second delay at minimum for digtron creations, but do you also place that restriction on mesecon luacontrollers?

I want to test certain ideas and structures in a local creative world before attempting to construct them on the server to save resources/time (and also try not to accidentally break things!) which is why I'm looking for this information.

**Comment by thomasrudin** [comment]
Glad to hear that:
I added the modlist:
https://github.com/pandorabox-io/pandorabox.io/blob/master/doc/settings.md
And the relevant `minetest.conf` with redacted keys:
https://github.com/pandorabox-io/pandorabox.io/blob/master/doc/mods.md

The RTC could be disabled, yes, but not on purpose though..
I don't believe in the additional delay on the digtrons, they always performed very well if not abused.
I'm always using 1 second delay and never had lag-issues :rofl: 

Let me know if you need further info :+1:

**Comment by Guard13007** [comment]
Thank you very much for both the list and the tarball! <3
