### ISSUE TITLE
shop search in pandorabox.io homepage not working

### ISSUE THREAD

**Issue by stacode123** [pandorabox-io/pandorabox.io#143]
![Adnotacja 2019-04-19 190649](https://user-images.githubusercontent.com/49679054/56437170-5334bf80-62d6-11e9-98a5-773815dad034.png)

**Comment by thomasrudin** [comment]
This is an issue in the mapserver: https://github.com/thomasrudin-mt/mapserver/issues/9
But i'm working on that: the info is there but no ui to display it yet :smile:
