### ISSUE TITLE
Enable digilines rtc

### ISSUE THREAD

**Issue by TangentFoxy** [pandorabox-io/pandorabox.io#156]
I believe @thomasrudin told me in-game (my in-game name is Tangent) that the RTC is meant to be enabled, but it isn't.

**Comment by Guard13007** [comment]
Sorry, I meant @thomasrudin and [here is where the setting is checked](https://github.com/minetest-mods/digilines/blob/master/init.lua#L80).

**Comment by thomasrudin** [comment]
Looks like the rtc has no recipe but is enabled:
https://github.com/minetest-mods/digilines/blob/master/rtc.lua

I think i'm placing a vendor in the compat shop (spawn, admin-shop 3rd floor), long-term solution would be a recipe though...

**Comment by Guard13007** [comment]
Suggestion: add a recipe into your custom code? One of the clocks (I would
say whichever is most generic/easiest to build) + luacontroller + digiline.

Alternately, I'll see what the author/maintainer says about a recipe.

**Comment by thomasrudin** [comment]
shop placed in admin shop
