### ISSUE TITLE
[Mod Request] charcoal

### ISSUE THREAD

**Issue by TangentFoxy** [pandorabox-io/pandorabox.io#157]
I would like to see a charcoal mod, like [perhaps this one](https://gitlab.com/VanessaE/charcoal).

- Might break existing machinery by having wood group as both a fuel item and something that can be cooked.
- Might break existing recipes (how does Minetest handle conflicting recipes?)
- More options for fueling things
- I'm a shameless proponent of Minecraft stuff sometimes

**Comment by thomasrudin** [comment]
**added**, needs a restart/crash

I like the torch recipe, i always bought coal lumps, but with this i can integrate that in my tree machine :smile:

**Comment by TangentFoxy** [comment]
:D
