### ISSUE TITLE
Mod updates

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#160]
* [x] https://git.rudin.io/minetest/locator (radar range)
* [ ] https://github.com/pandorabox-io/digtron (branch: limit-digtron-size-setting)
* [ ] https://github.com/thomasrudin/mapserver_mod (locator stub)

**Comment by TangentFoxy** [comment]
I believe digilines is outdated as well, but I am not sure.

**Comment by thomasrudin** [comment]
Digilines in minetest-mods: https://github.com/minetest-mods/digilines dates: 20 Oct 2017
We are on the "latest" state :rofl:

**Comment by thomasrudin** [comment]
* relevant mods updated
* digtron issue follow up: #164

**Comment by TangentFoxy** [comment]
In that case I need to continue talking to them about minetest-mods/digilines#42 as the interface for digiline chests is completely @#%!'ed..

**Comment by thomasrudin** [comment]
@TangentFoxy can you give me the coords of your setup? I'll take a look at it...

**Comment by TangentFoxy** [comment]
I removed it since it wasn't working as intended, have yet to try again.

**Comment by TangentFoxy** [comment]
Also I am having some confusion, because the commit you reference is dated 2017, and indeed shows as the latest commit, but it also shows as March 6, 2019. Are you certain the server has ALL the latest commits and not just happening to have that same commit from 2017 and lacking other more recent commits?

**Comment by thomasrudin** [comment]
You were right, i missed about 6 commits :open_mouth:
It is updated and needs a crash/restart...
In my defense: the git history on that repo looks timetravelled :rofl:

**Comment by TangentFoxy** [comment]
That might explain the strange behavior I witnessed. Thank you!
