### ISSUE TITLE
[Mod Request] lcd (better LCDs)

### ISSUE THREAD

**Issue by TangentFoxy** [pandorabox-io/pandorabox.io#163]
Better than digilines' LCD (in my opinion)
- Left-aligned text
- Standard line-breaks
- Better font and clearer text (more readable!)

https://forum.minetest.net/viewtopic.php?t=20794

**Comment by thomasrudin** [comment]
We have the digiterms installed: https://forum.minetest.net/viewtopic.php?pid=103857
Those can even be placed on the ceiling or the floor :D and they have cathodic/scifi variants...
The lcd-mod can't really compete with that :/

**Comment by TangentFoxy** [comment]
Ah, haven't looked at those yet. Thanks!

**Comment by thomasrudin** [comment]
closing, due to cleanup (feel free to re-submit)
