### ISSUE TITLE
autocrafter drains hunger points

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#179]

**Comment by kiedtl** [comment]
So, if I go afk while running my compressed-cobble stone gen, I'll come back to find myself dead from starvation??

**Comment by thomasrudin** [comment]
> So, if I go afk while running my compressed-cobble stone gen, I'll come back to find myself dead from starvation??

It is a bug, it should not be that way....

**Comment by kiedtl** [comment]
Oh.

**Comment by int-ua** [comment]
I don't think I ever noticed such behaviour and I use them a lot. Is there some special case where this happens?

**Comment by thomasrudin** [comment]
Never experienced that myself, it was a report from a play (don't know the name anymore...)
Closing until relevant again
