### ISSUE TITLE
Something, something, space-radiation

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#181]
Rebalance: #192

* radioactive fog near ores in space?

**Comment by kiedtl** [comment]
So, we would have to wear a spacesuit and a hazmat? that's not even possible...

**Comment by thomasrudin** [comment]
It _is_ however possible to mine with a shielded ship, just saying :smile:
You could even have air in there...

**Comment by kiedtl** [comment]
Right, with HV quarries or something similar. I think if that ever happens, I'll just go into space with a hazmat and some papyrus and ditch my spacesuit forever. :P

**Comment by thomasrudin** [comment]
> Right, with HV quarries or something similar. I think if that ever happens, I'll just go into space with a hazmat and some papyrus and ditch my spacesuit forever. :P

https://github.com/thomasrudin-mt/vacuum/commit/9bdb141b5d8842124cc92fa9687ad03d409616eb
:rofl:
