### ISSUE TITLE
Game rebalance

### ISSUE THREAD

**Issue by kiedtl** [pandorabox-io/pandorabox.io#192]
admin:

I've seen your email. I'ts very interesting. I have a few ideas about how to rebalance game:

1. balance out mapgen to make mese FAR rarer, ESPECIALLY on asteroids. Right now, I'm mining this asteroid that's practically MADE of mese and iron. (I just throw the iron away ;P)
    - asteroids should not be filled with resources, there should be an appreciable amount of stone too.
    - mese should be rarer than diamonds and mithril in space as well as on earth.
2. the idea about limiting space to those with a certain amount of XP is good - I mean, do we really need a Cobble God mining the moon? But, uh, I think the min. xp amount to go into space above the moon should be just 30k xp, because, uh, I have only 55k xp and that would mean that I wouldn't be able to mine my asteroid. I mean, if you are an Iron Mayor, that doesn't mean your a noob, right? (IMO graduating into the Iron ranks means you're not a noob anymore.)
3. **xenomorphs**: I'm not sure how powerful they are, but they shouldn't appear TOO frequently because it's kinda hard to wear armor in space. Unless, you have tons of papyrus to waste.
4. **Dangerous environment**: how willl we combat this? you can't wear a spacesuit and hazmat in space at the same time.

Also, what peanut says...

> BUT what I have noticed on this site is how simple a new player can go from nothing to building a house with a gold block wall ! 

*cough* *cough* korlen *cough* *cough*

> To many teleporters, open access to to space, androids, etc.

IS THAT A BAD THING??

> Worse still, they get "drunk" on minerals , start ambitious projects they never will finish, use both our resources and the server resources.

That's true - but fixing mapgen will fix this.

> Otherwise, you will see the reAL "crew" leave and the site full of one time thrill seekers.

Reading that, I'm also a little concerned... both with the above statement and with this rebalancing. I was once part of another game where is was really easy to move forward in the game. Then the devs cracked down, and made it extremely hard to do anything in the game, without gettign tons of the ingame currency which was also very hard. All in the name of rebalance. All the while, the REAL players mooved away. now the game is mostly dominated by ten-year-old noobs who with rich parents who buy lots of the ingame currency and defeat the actual players that have been in the game for years.

Just my humble $0.02,

Kied Llaentenn

**Comment by thomasrudin** [comment]
Thx for your input, the goal is not to make it too hard.
I'll sleep over that and think about some possible solutions.
Before i change something i'll notify ingame again...

> cough cough korlen cough cough

Uhm, yeah, i know. I saw that too late. can't tear it down now, he invested too much work...

**Comment by kiedtl** [comment]
> Uhm, yeah, i know. I saw that too late. can't tear it down now, he invested too much work...

nothing to do I guess...

BTW, another time the actually created a death trap in a public place - once in fruitland and once in the fruitland public workshop. I dealt with the first one, ask UncleSam for details about the other. The first was build of diamonds and gold lol

**Comment by thomasrudin** [comment]
> > Uhm, yeah, i know. I saw that too late. can't tear it down now, he invested too much work...
> 
> nothing to do I guess...

I think the situation will resolve itself there:
I've seen similar players start something _very_ big in a public place and then just quit forever.
In that case i can move that thing to the archive :smile: 
 
> BTW, another time the actually created a death trap in a public place - once in fruitland and once in the fruitland public workshop. I dealt with the first one, ask UncleSam for details about the other. The first was build of diamonds and gold lol

Hmm, i think i'm missing a lot of stuff nowadays, it just happens much more than in the
early days...

But i think thats a good sign: the player-base grows

**Comment by thomasrudin** [comment]
Closing this for now, if it needs another rebalance session i'll open a new one..
