### ISSUE TITLE
2019-06-28 mod updates

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#193]
## Test & Add

* [x] https://github.com/pandorabox-io/planetoids (core ore gen, cleanup)
* [x] https://github.com/pandorabox-io/planet_moon (ore gen)
* [x] https://github.com/pandorabox-io/planet_mars (cave deco, mars ores)
* [x] https://github.com/pandorabox-io/mobs_xenomorph (spawning, rarity, fly)
* [x] https://github.com/pandorabox-io/telemosaic (telemosaic.travel_allowed)
* [x] https://github.com/thomasrudin-mt/missions (missions.can_create_wand(player, pos))
* [x] https://github.com/thomasrudin-mt/vacuum (papyrus)
* [x] https://github.com/pandorabox-io/pandorabox_custom/ (ui, teleport, optionals)
* [x] https://github.com/minetest-mods/unified_inventory (reset to upstream)
* [x] https://github.com/thomasrudin-mt/jumpdrive (sane coords)
* [x] https://github.com/pandorabox-io/digtron (ejection delay)
* [x] https://github.com/thomasrudin-mt/vacuum/pull/14
* [x] https://github.com/thomasrudin-mt/spacesuit/pull/9
* [x] Remove https://git.rudin.io/minetest/jumpdrive_limit/
* [x] https://github.com/pandorabox-io/pandorabox_custom/ (jump limit)
* [x] https://github.com/pandorabox-io/mesecons/ (actionqueue perf)

## Add

* [x] https://github.com/thomasrudin-mt/vacuum/pull/15
* [x] https://github.com/Sokomine/replacer/pull/12

## Nice to have

* [ ] http://github.com/pandorabox-io/redwood

**Comment by kiedtl** [comment]
Just a question

>  Remove git.rudin.io/minetest/jumpdrive_limit

will the landing privs be removed, jumpdrives be able to fly above 18k, or both?

I mean, I don't thing every person with a spaceship should be able to land it on earth, if they have malicious intent they could cause alot of damage.

Just my humble 2 cents.

**Comment by thomasrudin** [comment]
> Just a question
> 
> > Remove git.rudin.io/minetest/jumpdrive_limit
> 
> will the landing privs be removed, jumpdrives be able to fly above 18k, or both?
> 
> I mean, I don't thing every person with a spaceship should be able to land it on earth, if they have malicious intent they could cause alot of damage.
> 
> Just my humble 2 cents.

Thats not the case: i'm just incorporating that (tiny) mod in the customization mod:
https://github.com/pandorabox-io/pandorabox_custom/blob/master/travel.lua#L49

I'm going to implement a kind of "no magic" zone for certain areas:

The new 6-planet system (forgot the name :P)  will be only accessible through the teleport in the sun.
From there on you have to walk to the other planets (or use/build a train-line)
Every teleporter in that area simply won't work.

**Comment by kiedtl** [comment]
>Thats not the case: i'm just incorporating that (tiny) mod in the customization mod:
pandorabox-io/pandorabox_custom:travel.lua@master#L49 


ah, ok :D
