### ISSUE TITLE
Homedecor beer tap not working correctly

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#195]
It takes your cup but doesn't give a beer in return.

It was working a few days ago, as I used the one near downtime's shop, but now it's not working...

PS. AceRichman here :)

**Comment by thomasrudin** [comment]
There was a homedecor upgrade that may have introduced some bugs...
Is this still an issue?

**Comment by OgelGames** [comment]
It's fixed now :)
