### ISSUE TITLE
Teleports

### ISSUE THREAD

**Issue by Techniknoob** [pandorabox-io/pandorabox.io#205]
ich werde manschmal random teleportirt zu einer kordinate  -inf

![screenshot_20190702_235737](https://user-images.githubusercontent.com/52414063/60626445-0e0b2e80-9deb-11e9-8102-9e918ff6c6b4.png)

**Comment by Techniknoob** [comment]
kam schon 5 mal for.

**Comment by Techniknoob** [comment]
Manchmal die x coordinate oder y oder z

**Comment by thomasrudin** [comment]
Kannst du das reproduzieren?
Falls ja: Kannst du einen Bug im minetest-repo öffnen: http://github.com/minetest/minetest/issues
Engine-Probleme sind nicht mein Ding :smile:
