### ISSUE TITLE
"Connection Timed Out" Linux 

### ISSUE THREAD

**Issue by codic12** [pandorabox-io/pandorabox.io#217]
So I recently discovered Minetest and am loving it. A friend of mine recommended Pandorabox, so I decided to check it out. _It dosen't work._ I keep getting Connection Timed Out. I have rebooted several times and every other server works.
**System Info (from `uname`)**
```
Linux Robot 4.19.56-1-MANJARO #1 SMP PREEMPT Wed Jun 26 03:35:21 UTC 2019 x86_64 GNU/Linux
```
Running KDE... any help would be appreciated.

**Comment by thomasrudin** [comment]
The stats page is down, but i guess thats the http2 issue again ;P
Anyway: i tried it myself and it worked...
Can you try the test-server at `test.pandorabox.io` ?

**Comment by gsbhasin123** [comment]
Sure... hold on

**Comment by gsbhasin123** [comment]
I can ping both of them. Seems this is a Minetest issue, not a pandorabox one since it does not work on certain other servers with the same error

**Comment by thomasrudin** [comment]
What version do you have? We are on 5.x...
The 0.4.x and 5.x are sadly not compatible... :/

**Comment by gsbhasin123** [comment]
I am on 5.0.1... whats the IP-Version?

**Comment by gsbhasin123** [comment]
Also having this issue with some other servers

**Comment by thomasrudin** [comment]
IP v4 or v6, i think that could be an issue...
On what servers can and can't you connect?

**Comment by gsbhasin123** [comment]
output of `ip a`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 00:26:b9:db:14:98 brd ff:ff:ff:ff:ff:ff
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 78:e4:00:c3:fd:9f brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.68/24 brd 10.0.0.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 9676201sec preferred_lft 9676201sec
    inet6 2601:641:380:556a::9ff4/128 scope global dynamic noprefixroute 
       valid_lft 9676203sec preferred_lft 9676203sec
    inet6 2601:641:380:556a:8667:3a0:c019:819f/64 scope global dynamic noprefixroute 
       valid_lft 334759sec preferred_lft 334759sec
    inet6 fe80::81be:a4bd:1322:e571/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
Some servers like all that belong to "VanessaE", Illuna TechEth, and Capture the flag - multiple flags all work .Some other servers, like Pandorabox and Undercore don't.

**Comment by thomasrudin** [comment]
I pinged you on the forums: if this is still an issue please try to access from another internet-access (school, work, neighbors open wifi, etc)

My guess is a weird IPv6 issue (i'm still open for a network capturing session, just saying :smile: )

**Comment by gsbhasin123** [comment]
Hey... I tried to connect to another WiFi network but all other WiFi networks in proximity don't work.
It's also reproducable on Lubuntu 19.04 with a Live USB (using the same WiFi, of course :smile: ). And what is a networking capture session?

**Comment by thomasrudin** [comment]
> And what is a networking capture session?

I could capture the traffic that comes in on my side when you try to connect to see what exactly goes wrong or if it even receives something...

Your issue is really strange, it normally works without problems (TM) everywhere, even on windows crapware...

**Comment by gsbhasin123** [comment]
Sure.. we can try that. Just tell me when you are free...

**Comment by thomasrudin** [comment]
Sorry for the lag :smile: i was a bit busy

If it is still important to you to join our server, can you test the following and report back:
* Connect to `test.pandorabox.io` with your minetest client
* Check out https://pandorabox.io with your browser

If you lost your interest, i fully understand though..

**Comment by gsbhasin123** [comment]
Hey @thomasrudin, thanks for helping me out! 

- Connection timed out for test.pandorabox.io:30000 from serverlist
- I can visit the website with Chromium and Brave
- Hold on... The ipv6 works!! I guess you were right... thanks for your help

**Comment by gsbhasin123** [comment]
btw would you mind telling any other server authors you know to add the ipv6 to their domain? thanks

**Comment by thomasrudin** [comment]
Does sound fair, yes :)

**Comment by gsbhasin123** [comment]
Start with `test.pandorabox.io`.
Another server which dosen't support ipv6 is BlockCity creative
