### ISSUE TITLE
Mod/Engine updates 2019-07-17

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#218]
## Upstream updates
* [x] https://gitlab.com/VanessaE/pipeworks (tube dos'ing)
/bb05ff8fd210fc9fac0b521f15e755380e6916d3 (coil0)
* [x] https://github.com/D00Med/scifi_nodes/pull/15 (coil0)

## Tested
* [x] https://github.com/minetest-mods/moreblocks/issues/145 (textures changed -> server restart)
* [x] https://github.com/thomasrudin-mt/missions/pull/34 (mapserver visibility)

## Need testing
* [x] https://github.com/thomasrudin-mt/jumpdrive (digiline, teleport tube, protection, particles)
* [x] https://github.com/pandorabox-io/stamina/pull/1
* [x] https://github.com/thomasrudin-mt/missions/pull/31
* [x] https://github.com/pandorabox-io/mesecons (#219)
* [x] https://github.com/pandorabox-io/geoip (logging)
* [x] https://github.com/pandorabox-io/pandorabox_custom (onplace bypass)

## Engine

* [x] pg-fix: https://github.com/minetest/minetest/commit/02882aa34ad376689f810f6bf1cd5a8800e2634f
 * should fix: #224
* [x] network receive tuning https://github.com/thomasrudin-mt/minetest/commit/51b299618bd2f183c38bfb45f3bf7454d05a0cb9
 * should fix (somewhat) #223

**Comment by S-S-X** [comment]
centered wooden tile recipe seems to be fixed upstream, requested few times in game: https://github.com/minetest-mods/moreblocks/issues/145

**Comment by thomasrudin** [comment]
@S-S-X updated the moreblocks mod on the test-server, there were about 20 new commits... :/
i havent found any obvious bugs, but if you wanna check you have `server` and `privs` on the test-server...

new entry in minetest.conf (prevents the 130-page inventory)
```
moreblocks.stairsplus_in_creative_inventory = false
```

**Comment by S-S-X** [comment]
didn't test much but wooden tile recipes seems to work correctly now.
