### ISSUE TITLE
LuaControllers spend all saplings from a Deployer exclusively when area is not loaded

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#231]
When area is loaded everything is fine.

Code for my tree farm with single controller:
```Lua
if 'program' == event.type or 'interrupt' == event.type then
 digiline_send('detector', 'GET')
 digiline_send('mulch_out', 'bonemeal:mulch 99')
 dt = os.datetable()
 digiline_send("screen", dt.min .. ':' .. dt.sec .. 'cycle')
 -- port.b = false
 interrupt(5, 'rince')
end

if 'digiline' == event.type then
 digiline_send('screen', event.msg)

 if 'air' == event.msg then
  port.b = true
  digiline_send("saplings", "default:sapling 1")
  --interrupt(1, 'close_deployer')
 else
  port.b = false
 end

 if 'default:sapling' == event.msg  then
  port.c = not port.c
 else
  port.c = false
 end

 if 'default:tree' == event.msg  then
  port.d = true
 else
  port.d = false
 end

 if event.channel == 'auto' then
  digiline_send("trunks", "default:tree 12")
  digiline_send("leaves", "default:leaves 96")
  dt = os.datetable()
  digiline_send("screen", dt.min .. ':' .. dt.sec .. 'mulch')
 end

end
```

```Lua
if 'air' == event.msg then
  port.b = not port.b
```
give same results.

**Comment by thomasrudin** [comment]
Weird, the mesecons should be inactive when the are is unloaded: https://github.com/minetest-mods/mesecons/commit/737f366741f54659b17bd9c96e2232eedb9735ee

Can you give me coords to it? (you gave some in a mail but i deleted that already, sorry...)

Also: Its possible certain mesecons contraptions cause an event-loop that event persists if the area is unloaded (NOT looped with itself should do the trick)...

**Comment by int-ua** [comment]
Somewhere around -2483,50,3741.

Can you please explain "not-looping" after checking the farm layout?

**Comment by int-ua** [comment]
I'll try

```Lua
interrupt(0.1, 'close_deployer')
```
in several hours when I'll be online

**Comment by thomasrudin** [comment]
My bad:
After i submitted the PR to the upstream repo i changed back the branch to it but forgot to rename the changed setting names :disappointed: 
```
# old setting
mesecon.luacontroller_nodetimer = true
# new setting
mesecon.luacontroller_lightweight_interrupts = true
```

This may be the reason for #229 and #223 ...
I changed it, needs a restart now....

sorry for the trouble..
