### ISSUE TITLE
New Skybox for moon

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#236]
I create new skybox for moon. It's not perfect at bottom, but looks so nice. The pictures are high quality, so You will probably need to change their resolution. Preview https://imgur.com/3XbGCx1

Repo: https://github.com/kubaorlen/Skybox-moon-for-Pandorabox.git

1) moon up:
https://i.imgur.com/ZWUUJtV.png
2) moon down:
https://i.imgur.com/R19lKBT.png
3) moon right:
https://i.imgur.com/biEiBkl.png
4) moon left:
https://i.imgur.com/OreL2mB.png
5) moon back:
https://i.imgur.com/KwpCPPE.png
6) moon front:
https://i.imgur.com/l3qixfB.jpg

-- skybox.lua

textures = {
"moon_up.png^[transformR270",
"moon_down.png^[transformR90",
"moon_right.png",
"moon_left.png",
"moon_back.png",
"moon_front.png",
	}

**Comment by thomasrudin** [comment]
Oh, i'll check that out when i have time, the high-res images are tempting...
Shy questiion: license? :smile:

**Comment by kubaorlen** [comment]
GPLv3

**Comment by thomasrudin** [comment]
The upper images look nice, but the bottom is pretty ugly:

![screenshot_20190803_090855](https://user-images.githubusercontent.com/1026711/62408808-6ee67c00-b5ce-11e9-9c18-0e60bb91016c.png)

**Comment by thomasrudin** [comment]
No feedback, closing
