### ISSUE TITLE
Fix teleport requests (again)

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#237]
Broken (or not properly configure) after last update

Related:
https://github.com/BlockySurvival/issue-tracker/issues/83#issuecomment-515721634

**Comment by Panquesito7** [comment]
If there are any other bugs, you may probably want to use [my fork](https://github.com/Panquesito7/teleport-request) as it contains bugfixes and new features. Submit an issue if there are any errors there.
