### ISSUE TITLE
Bike crash

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#240]
```
minetest_1           | terminate called after throwing an instance of 'LuaError'
minetest_1           |   what():  Runtime error from mod 'bike' in callback on_shutdown(): /data/world//worldmods/bike/init.lua:52: attempt to concatenate local 'color' (a nil value)
minetest_1           | stack traceback:
minetest_1           | 	/data/world//worldmods/bike/init.lua:52: in function 'colormetal'
minetest_1           | 	/data/world//worldmods/bike/init.lua:109: in function 'default_tex'
minetest_1           | 	/data/world//worldmods/bike/init.lua:155: in function 'dismount_player'
minetest_1           | 	/data/world//worldmods/bike/init.lua:542: in function </data/world//worldmods/bike/init.lua:539>
minetest_1           | 	/usr/local/share/minetest/builtin/game/register.lua:419: in function </usr/local/share/minetest/builtin/game/register.lua:399>

```

**Comment by HybridDog** [comment]
bike.color should never be nil, so maybe there's a luaentity which is not a bike and has a driver field.
https://gitlab.com/h2mm/bike/blob/master/init.lua#L155
https://gitlab.com/h2mm/bike/blob/master/init.lua#L541
In line 541 the code does not check if e is a bike object.

"Bike crash" sounds ambiguous.

**Comment by thomasrudin** [comment]
> "Bike crash" sounds ambiguous.

Heh, yeah, the `crash` labels are just my dump-issues in which i put all the errors i find (and eventually make a PR upstream or fix it locally)

In case of the bike crash: we did not have that issue since then again, closing (but thx for checking that out :smile:)
