### ISSUE TITLE
Investigate mission nointeract issue

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#242]
-> Super mario mission

**Comment by thomasrudin** [comment]
@int-ua i rewrote you interact PR, sorry :/ there is now a "revoke interact temporary" step
Your code did some comparisons that did not work:
```
if 0 then print("ok") end
-- prints "ok" :)
```

I took the liberty of rewriting your part, sorry for that.
Now you can add a step on the beginning of the mission that revokes the interact privs...

If there are issues with my code or the interact stuff in general, feel free to open an issue

**PS**: needs a restart...

**Comment by int-ua** [comment]
Ok, thank you, that will work too.

> some comparisons that did not work

Please clarify which ones when you have time.

The new code will grant interact in a case that's extremely low probable: when someone has a mission active and admin tries to revoke interact priv for some reason. But that's not a significant problem at all.
