### ISSUE TITLE
Conflicting crafting recipes for extendable ladders

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#250]
The crafting recipe for the steel extendable ladders (ropes mod) are conflicting with steel leggings (3d armor mod), and thus cannot be crafted.

The current recipe for the extendable ladders is as follows:

| M | M | M |
| M | -- | M |
| M | -- | M |
(where M is iron ingots)

A possible fix would be to change the recipe to the following:

| M | M | M |
| M | M | M |
| M | -- | M |

**Comment by OgelGames** [comment]
Has already been fixed: https://github.com/minetest-mods/ropes/commit/be0897ee1d777ecae98c9d8908ce5eb6199c83a1

**Comment by thomasrudin** [comment]
Thx, i put it on the update list
