### ISSUE TITLE
Wiki login does not work

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#251]
Issue is simple, login ([https://pandorabox.io/wiki/index.php?title=Special:UserLogin](https://pandorabox.io/wiki/index.php?title=Special:UserLogin)) wont accept credentials but instead displays following message:

> The supplied credentials could not be authenticated.

Few users tested this and could not login to wiki.

**Comment by thomasrudin** [comment]
Thx for reporting, the auth service was not restarted after the server restart... :P
