### ISSUE TITLE
Reduce max player count

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#254]
Current value is 50, with 30 player there are some lag spikes.

TODO: determine reasonable value, maybe 35?

@SwissalpS @6r1d @kiedtl @int-ua @S-S-X (sorry for pinging) can you give some feedback

**EDIT**: moderators can always join, even if the server is full

**Comment by SwissalpS** [comment]
50 only inspires more afk players. but then again 30 does too, but not so
much.
30 felt good :D
/* * * Luke@SwissalpS.ws * * */

**Comment by 6r1d** [comment]
I agree with SwissalpS, 30 seems to be enough for now.
Or even more than enough, since game lags a bit (rarely), and I suppose it happens when someone is doing some resource-consuming stuff.

**Comment by kiedtl** [comment]
Late to the party here, but I've honestly never noticed much of a difference. I dont' play as often anyway xD

**Comment by thomasrudin** [comment]
Ok, my current plan:
* Keeping the limit of 40 players for now
* Adding some more metrics to the engine: https://pandorabox.io/grafana/d/ifuy9KSZz/minetest-engine?orgId=1&refresh=5s
* Look for the lag cuplrit (i'm guessing DB-Read or network this time)
* **If fixing possible**: create a PR/fix and raise limit
* **If not**: reduce max player-count to 30
