### ISSUE TITLE
Loading remote areas using teleporting tubes

### ISSUE THREAD

**Issue by coil0** [pandorabox-io/pandorabox.io#257]
By placing two teleporting tubes in each of two remote areas and sending items in a loop between the two pairs of teleporting tubes, you can keep the items looping even when neither of the two areas is loaded.

I added a mesecon-detecting tube that the items passed through and could keep a node breaker working long after I left the area. Keeping a switching station loaded might be more difficult, but this is enough to keep generators not dependent on technic working as if they were made active by an anchor. However, an anchor would continue working after a server restart.

**Comment by thomasrudin** [comment]
Hmm, interesting, is this a bug or a feature? :smile: 

On a related note:
I think i need to figure out how/when i re-add the anchor-code to the technic switching station again.
That was the original design but i removed that part in fear of performance issues...

**Comment by thomasrudin** [comment]
There is not forceload-call in the pipeworks mod:
```
thomas@thomas-VirtualBox:~/secure/git/pipeworks$ grep forceload * -Rn
luaentity.lua:76:local active_blocks = {} -- These only contain active blocks near players (i.e., not forceloaded ones)
```

The pipeworks transport logic invokes the mesecon effectors here:
https://gitlab.com/VanessaE/pipeworks/blob/master/signal_tubes.lua#L52

Maybe someone is abusing that to keep his mesecons-contraptions loaded... (#271)
