### ISSUE TITLE
Recipe for silver sand or make silver sand stone generated

### ISSUE THREAD

**Issue by lockonrzwei** [pandorabox-io/pandorabox.io#259]
Silver sandstone structures look nice. Unfortunately there is no way to make silver sand. I don't know if it is intended to make it a rare material, but i'd be happy to see a recipe for it. Buying it is also quite hard because no one wants to sell it for a price reasonable to use it as a building material.

There are only two ways i know to obtain it: under the surface or silver sand deserts. Getting in from the first one requires huge amounts of digtron usage, the second one is less work intensive but it destroys landscapes (and still a lot of digtroning).

So I'd like to propose a solution to this: either the ability to produce silver sand (e.g. grinding stone dust or sand + white dye) or the generation of silver sandstone under silver deserts, so it can be dug underground.

I don't know if there are other players mining actively for silver sand, but maybe a possibility to produce it might reduce lag and destruction of landscapes, although it might require machine usage or bone generators (if white dye is used).

**Comment by thomasrudin** [comment]
If i search for `silver_sand` on the map i find a few shops that sell it.
Most importantly: https://pandorabox.io/map/#0/-675.375/-3937.375/11

If you insist on the recipe then a grinder recipe would be optimal i think.
We need to find a (relatively real) material that can be grinded to silver sandstone.
If i remember correctly most of the stone-nodes can already be grinded to something though.

I'm open for suggestions as long as there is no conflict with existing recipes...

**PS**: the custom grinder recipes are here, if you want to code that yourself: https://github.com/pandorabox-io/pandorabox_custom/blob/master/grinder.lua#L5 :smile:

**Comment by thomasrudin** [comment]
Should be fixed with: https://github.com/pandorabox-io/pandorabox_custom/pull/1
