### ISSUE TITLE
One player is singled out and gets mobs privs. He floods the market with orbs.

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#261]
This changes the game completely. He floods the game with free lava orbs while stockpiling 4 times the amount he gives out, in his coffers.
This gives him unbalanced power to stop giving free orbs and dictating the price.
Even if he gave out 40 orbs and kept 1 to himself, he would become unfairly advantaged over
any other player that is not from the 'old-crew'.
It is currently easier for a noob to get a full set of lava gear than for him to grow a stack of carrots.
He just goes to the mission block and spends 5-15 minutes there, then goes and buys or digs some mese and thanks to the new recipe that doubles the ingots per orb/mese, he has a full set in no time. Skipping any other armour and tool in the game.
Why take the mob mission privs only to give it to one player? Bringing back the mob mission priv will not solve the current situation.
I am not affected, I have my orbs and never intended to sell competitively. The more other
players sell orbs, the less time I need to spend getting orbs for my vendor. That's how I look at it.
But if I start a new game today, I would ask myself what for all the other armours are, if lava is cheaper to have than diamond.

Do we need to limit orb ownage by xp too now? or is this the new pandorabox?

**Comment by thomasrudin** [comment]
That was not the idea of the `missions_mod` priv...
Give me the name and i'll deal with it tomorrow or threaten whoever it is with a ban (or just ban, your choice)

**Comment by SwissalpS** [comment]
Please warning, not ban, he probably does not see the scope of what he is doing.

**Comment by SwissalpS** [comment]
Player has seen his misscalculation and removed the mission entirely, problem solved.
