### ISSUE TITLE
Item gravity wip

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#263]
Centralized gravity and item throwing support

* Gravity manager: https://github.com/pandorabox-io/gravity_manager
  * [ ] override builtin item

**Comment by BobFred7** [comment]
All steps are checked off
should this be closed now?

**Comment by thomasrudin** [comment]
hmm, don't know why i crossed that off, the "floating items" thing does not work yet... :/

**Comment by BuckarooBanzay** [comment]
abandoning that, this would be a big hack currently with the `builtin` api (a mess of overrides with redefinitions)
