### ISSUE TITLE
homedecor's beer give glasses on full stamina

### ISSUE THREAD

**Issue by Su20ma** [pandorabox-io/pandorabox.io#279]
[homedecor's](https://gitlab.com/VanessaE/homedecor_modpack.git) beer give players glasses without checking for player stamina.
This can be solved by simply checking for player stamina, but I suggest we have a seperate mod for this, that has a function that accepts a parameter that is the material that will be given back to the player if the stamina isn't full.

**Comment by coil0** [comment]
Seems like `minetest.do_item_eat` returns the leftover item stack and homedecor [ignores it](https://gitlab.com/VanessaE/homedecor_modpack/blob/0cd8bd7780ff62cd718d90ec72011b58fcd19ec5/homedecor_gastronomy/init.lua#L178). Writing a separate mod shouldn’t be necessary.

**Comment by thomasrudin** [comment]
fluxionary opened an issue there: https://gitlab.com/VanessaE/homedecor_modpack/issues/18

**Comment by Su20ma** [comment]
We should stop homedecor from sending messages when filling beer aswell

**Comment by thomasrudin** [comment]
thx @coil0 https://gitlab.com/VanessaE/homedecor_modpack/merge_requests/5 :rofl:
