### ISSUE TITLE
Vendor display doesn't update correctly when restocked in unloaded area

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#280]
When an out-of-stock fancy vendor gets restocked with pipeworks tubes in an area away from players (such as with a teleporter tube), the vendor displays both the item for sale and an out-of-stock icon.

**Comment by thomasrudin** [comment]
I always wondered how the vendors in Lejo's place reached that state :rofl:

**Comment by thomasrudin** [comment]
this should now work too: https://github.com/pandorabox-io/fancy_vend/blob/92023639ecb38a19f969876d06ddaa36c5faebf2/init.lua#L209

**Comment by OgelGames** [comment]
Not fixed, worse actually, it only shows out-of-stock icon.

**Comment by thomasrudin** [comment]
I think there are two separate `fancyvend` repos now, i see if i can merge them...
