### ISSUE TITLE
Vendor's "Fill lots to max" button doesn't work correctly

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#281]
When the "fill lots to max" button is used with player vendors, the resulting max lots is one lot higher than the actual max lots the player can buy, and when used with admin vendors the max lots is zero.

**Comment by kiedtl** [comment]
> and when used with admin vendors the max lots is zero.\

For me, every max lot is zero, admin vendor or not.

**Comment by OgelGames** [comment]
Seems to be partly fixed, player vendors work correctly now (at least for me), but admin vendors still show zero lots

**Comment by SwissalpS** [comment]
[this should fix it](https://github.com/pandorabox-io/fancy_vend/commit/081c11d04e5b993d713ef26b7075e2008ffce89d)

**Comment by thomasrudin** [comment]
thanks :+1: i'm optimistic and close this for now... :smirk:

**Comment by OgelGames** [comment]
It works on my test server, so should be fine 👍
