### ISSUE TITLE
Use player_monoids

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#283]
https://github.com/minetest-mods/player_monoids

* gravity_manager -> gravity
* pandorabox_custom -> fly

**Comment by Su20ma** [comment]
Could these prevent modified clients from granting privs without checking?

**Comment by thomasrudin** [comment]
> Could these prevent modified clients from granting privs without checking?

No, but that should not be possible right now (except fly, fast and noclip with "hacked" clients)...

**Comment by thomasrudin** [comment]
This looks fixed, thx @coil0 :)
