### ISSUE TITLE
[Mod Request] Cherry Tree [cherrytree]

### ISSUE THREAD

**Issue by puddingm300** [pandorabox-io/pandorabox.io#287]
I wanted to know if we could add this Cherry Tree Mod to the Server?

https://forum.minetest.net/viewtopic.php?t=22118

It would really enhance towns and add a cool resource.

Please take it into consideration,

puddingm300 & OnePunch

**Comment by thomasrudin** [comment]
The tree looks good, i'll have to figure out how i add a single tree from that modpack though.. :/

Github-Source: https://github.com/runsy/cool_trees

**Comment by puddingm300** [comment]
I don't know how the server is set up for mods, but according to the creator of the mods that I contacted, you can individually enable trees from the mod pack. :)

**Comment by thomasrudin** [comment]
Added in the staging-repo, will be installed in the next update-swoop...
