### ISSUE TITLE
Hazmat/Radiation not working

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#290]
Since the new update of the engine the hazmat armor does not seem to work anymore

**Comment by coil0** [comment]
Fixed by minetest-mods/technic#509. The change was caused by the engine update that added [4d7f2967172c5a358811ac1f24115b281eff2431](/pandorabox-io/minetest/commit/4d7f2967172c5a358811ac1f24115b281eff2431).

**Comment by thomasrudin** [comment]
thx coil, you are awesome :+1:
