### ISSUE TITLE
Add recipe to make black dye from charcoal

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#291]
Currently there are only two ways to get black dye; coal (which cannot be created), and black tulips (which can be created, but only very inefficiently).

With demand for black dye so high (mainly for making silver sandstone), it would make sense to add some way of producing it that matches the production of white dye (from bone generators).

So I would propose to add a way of making black dye from charcoal, such as 1 dye being extracted from 4 charcoal.

Please let me know what you think, an I will add the appropriate recipe if you think it's ok.

**Comment by thomasrudin** [comment]
I think that sounds fair (i may be biased though :smile:)
The quantity could be higher:
* 1 black dye from 1 charcoal (if crafted)
* 2 black dye from 1 charcoal (if extracted)

I need to add some recipes for dyes too: some flowers aren't available as an extractor recipe, but i'll do that myself when i have time..

**Comment by OgelGames** [comment]
> The quantity could be higher:
> 
> * 1 black dye from 1 charcoal (if crafted)
> * 2 black dye from 1 charcoal (if extracted)

Maybe, but with the fact that currently you can get 16 charcoal from a single tree node (and some trees like oak yielding a few thousand nodes), I feel it would lead to an oversupply if the amount of dye produced is too high...

**Comment by thomasrudin** [comment]
Oh, right. And because of the changed recipe (https://github.com/pandorabox-io/pandorabox_custom/blob/master/recipes.lua#L21 `wood` instead of `tree`) that makes it even worse...

Alternatively the yield of the charcoal recipe could be changed from 4 to 1

But yeah, your proposal makes sense now...

**Comment by OgelGames** [comment]
> Alternatively the yield of the charcoal recipe could be changed from 4 to 1

No, I don't think that should change, as it nicely matches the quantity of sticks that can be made, which are of course used to make torches.

I think the quantity of dye could be increased a bit though, as I just did some rough calculations on what could be created from one default tree, and it can actually make a lot more white dye than I first though.

* one tree yields about 10 tree nodes, and 50 leaves.
* 10 tree nodes > 40 wood > 160 charcoal > 80 or 160 black dye (if recipes below are used)
* 50 leaves > 100 dirt > 100 bones > 800 white dye (though in practice it would take much longer to make the white dye, than the black dye)

So the recipes could be adjusted to produce 1 black dye from 2 charcoal when crafted, and 1 black dye from 1 charcoal when extracted.

**Comment by OgelGames** [comment]
When will this be added to the server?

**Comment by thomasrudin** [comment]
> When will this be added to the server?

This was already in there, just the recipe for "plain" crafting was missing:
https://github.com/pandorabox-io/pandorabox_custom/commit/d92cb5a7d602169b12b523c6832e7b7e14fa5498

By the way: we have a "continuous delivery" pipeline now for the mods.
If the mod gets upgraded in the `pandorabox-mods` repo it gets updated on the server automatically... (https://github.com/pandorabox-io/pandorabox-mods/issues/3)

**Comment by OgelGames** [comment]
Oh, nice, must be a bug in the crafting guide then, because extracting dye still isn't showing as a use for charcoal...

**Comment by thomasrudin** [comment]
I need to retest this then :/

**Comment by SwissalpS** [comment]
I was able to craft black dye from nine charcoal.

**Comment by thomasrudin** [comment]
Worked for me too, closing...
