### ISSUE TITLE
Automatic updates of colors.txt

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#295]
Source: https://github.com/MilesBDyson/Colors.txt

**Comment by MilesBDyson** [comment]
how are you wanting to update this .. from within the game .. on a timed schedule or do you just want to simplify the process for the occasional update from the terminal..

**Comment by thomasrudin** [comment]
I will implement a similar solution to https://github.com/pandorabox-io/pandorabox-mods/issues/3

Just a cron-triggered script that checks for upstream updates.
I'll add a symlink to the `colors.txt` repo and maybe a mapserver-restart after changes.

**Comment by thomasrudin** [comment]
@MilesBDyson i added an hourly update mechanism, can you try to make changes to your repo?
