### ISSUE TITLE
Melons disappearing

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#298]
If you right-click a melon with a melon, previous one disappears. If you place something on a melon, new node is placed and old melon disappears.

**Comment by thomasrudin** [comment]
They may be `buildable_to = true`, don't know if that is intentional...

**Comment by 6r1d** [comment]
I think, melons [have a lot of potential](https://www.youtube.com/watch?v=3mHGL_kSEBw). And usually you can place a block on a block. Worst case scenario, one melon is rolling from another as a server object.

Also,
![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Square_watermelon.jpg/220px-Square_watermelon.jpg)

**Comment by thomasrudin** [comment]
I just checked, it is defined with `buildable_to = true`:
https://notabug.org/TenPlus1/farming/src/master/crops/melon.lua#L37
```lua
-- melon definition
local crop_def = {
	drawtype = "plantlike",
	tiles = {"farming_melon_1.png"},
	paramtype = "light",
	sunlight_propagates = true,
	walkable = false,
	buildable_to = true,
	drop = "",
	selection_box = farming.select,
	groups = {
		snappy = 3, flammable = 2, plant = 1, attached_node = 1,
		not_in_creative_inventory = 1, growing = 1
	},
	sounds = default.node_sound_leaves_defaults()
}
```

This could theoretically be overriden by `minetest.override_item(name, redefinition)` and should pose no big gameplay-related change:

```lua
minetest.override_item("farming:melon_8", {
  buildable_to = true
})
```
