### ISSUE TITLE
New telemosaic bugs

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#299]
Commit https://github.com/pandorabox-io/telemosaic/commit/1840efeb3efe8f47af46f9283fea70b49ae305b0 has added two bugs:

* Right-click teleportation can be spammed
* Right-click teleportation doesn't check for protected beacons

**Comment by thomasrudin** [comment]
thx :smile: 
Sorry for changing your code, force of habit: if i touch something it ends in a refactoring :/

**Comment by OgelGames** [comment]
That's ok 😄 
Except the bugs are still not fixed... So I'm working on a fix right now 😉
