### ISSUE TITLE
Steelbar recipe clash

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#300]
```
Steel bar and steel pole are in collision, and steel bar is needed for locker, used in locked chest.

Thanks by advance, an happy player. =)
```

**Comment by OgelGames** [comment]
Looks to be fixed here: https://github.com/pandorabox-io/banners/commit/a6b1a280b4429d355ac985ca06804a539abbdee5

**Comment by thomasrudin** [comment]
Looks like i forgot to update the mod in the `pandoarbox-mods` repo :/
thx for checking :)
