### ISSUE TITLE
Sand recipe issue

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#301]
```
Are you able to back craft recipe for silver sand with grey dye. Usings slabs and digging whole desert is not soution to finish city.
```

**Comment by OgelGames** [comment]
Seems like there's an old version of the pandorabox-custom mod on the server (charcoal dye recipe is also missing), not sure if this is intentional, or...

**Comment by thomasrudin** [comment]
Looks like it, the latest change was 3 days ago, but the repo is up-to-date on the server.
Maybe it just needs the occasional restart (crash?) to apply the changes..

A few months back there were crashes every few days, we haven't had out-of-sync problems like that back then :smile:

**Comment by thomasrudin** [comment]
fixed and staged
