### ISSUE TITLE
Settings tuning

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#309]
Settings tuning, please give feedback for the current settings

# Links
* Default settings: https://github.com/minetest/minetest/blob/master/src/defaultsettings.cpp
* Customizations of the engine: #230

Stats:
* Lua stats: https://monitoring.minetest.land/d/YUpouLmWk/overview?orgId=1&var-instance=pandorabox.io&refresh=5s
* Mesecons stats: https://monitoring.minetest.land/d/LjYzPumWz/mesecons?orgId=1&refresh=5s&from=now-1h&to=now
* Technic stats: https://monitoring.minetest.land/d/mk0TEXiZk/technic?orgId=1&refresh=5s&from=now-1h&to=now
* Engine stats: https://pandorabox.io/grafana/d/ifuy9KSZz/minetest-engine?orgId=1&from=now-1h&to=now&refresh=5s
* Engine network stats: https://pandorabox.io/grafana/d/1Sm9YXDZz/engine-network?orgId=1&from=now-6h&to=now&refresh=10s
# Settings

## Since 2019-09-01 19:00 CEST
```
#    Maximum number of blocks that are simultaneously sent per client.
#    type: int
# 40 = default
max_simultaneous_block_sends_per_client = 1

#    Maximum number of packets sent per send step, if you have a slow connection
#    try reducing it, but don't reduce it to a number below double of targeted
#    client number.
#    type: int
# 1024 = default
max_packets_per_iteration = 4096


# see: https://github.com/pandorabox-io/minetest/commit/af6956e7d2c5fae3151ddf5d769d52b81f9a7270
receive_iterations_per_step = 50

#    From how far blocks are sent to clients, stated in mapblocks (16 nodes).
#    type: int
max_block_send_distance = 5

```

**Comment by thomasrudin** [comment]
## Since 2019-09-03 19:50 CEST (restart pending)

```
max_simultaneous_block_sends_per_client = 2
max_packets_per_iteration = 4096
receive_iterations_per_step = 20
max_block_send_distance = 10
```

**Comment by thomasrudin** [comment]
## Since 2019-09-09 22:00 CEST (restart pending)

```
max_simultaneous_block_sends_per_client = 10
max_packets_per_iteration = 4096
receive_iterations_per_step = 5
max_block_send_distance = 10
```

**Comment by Lejo1** [comment]
What about the profiler?
It should show what functions take very long or are called very/too often.

**Comment by thomasrudin** [comment]
> What about the profiler?
> It should show what functions take very long or are called very/too often.

Already enabled, just forgot to post it here :)

**Comment by thomasrudin** [comment]
## Since 2019-09-11 12:00 CEST (restart pending)

```
max_simultaneous_block_sends_per_client = 10
max_packets_per_iteration = 4096
receive_iterations_per_step = 5
max_block_send_distance = 10
dedicated_server_step = 0.2
```

**Comment by thomasrudin** [comment]
## Since 2019-09-14 17:00 CEST

https://github.com/thomasrudin-mt/mesecons_debug
```
mesecons_debug_autoflush = false
mesecons_debug_cooldown_steps = 5
mesecons_debug_max_globalstep_time = 250000
```

**Comment by thomasrudin** [comment]
closing this issue:
* original perf issues was in the `client_unload_unused_data_timeout` setting which was set to roughly a day, this caused some of the lag-buildup (now at 5 minutes)
* `mesecons` should run normal again
* https://github.com/thomasrudin-mt/mesecons_ratelimiter to deduplicate some bad mesecons circuits (https://monitoring.minetest.land/d/o8HuMRtZk/mesecons-ratelimiting?orgId=1&refresh=5s)
* there are a few ingame machines that elevate lag, i'll contact the owners separately
