### ISSUE TITLE
Fly priv (escalation?)

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#310]
Thx to the player "TK234" for the report:

Repro (roughly):
* Go to space where fly is active
* Log out
* Log in / go away from space

Result:
* fly priv persists

Could be something with the new `player_monoids` thing..

**Comment by SwissalpS** [comment]
same thing can be reproduced near green beacon. If second player removes beacon while first has logged off. First player can fly anywhere when logs on again. Going near another beacon and moving away removes the priv as expected.

**Comment by coil0** [comment]
The monoid changes are cleared when the player leaves but the priv is not. If the player joins back somewhere they cannot fly, the caching check skips updating the priv.

A single update without the caching check when the player joins would fix it, but if saving the privileges is really that expensive the check could as well be in builtin instead.
