### ISSUE TITLE
Lava tools fire

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#311]
No fire since last update

Related:
* https://github.com/LoneWolfHT/lavastuff/blob/master/init.lua#L13
* https://github.com/LoneWolfHT/lavastuff/issues/6

**Comment by OgelGames** [comment]
The problem lies here: https://github.com/LoneWolfHT/lavastuff/commit/476b08c7fee97d5e827f34e7817e25eea60bd214

Or more specifically, it was changed to only place fire on flammable nodes: https://github.com/LoneWolfHT/lavastuff/blob/master/init.lua#L44

Not sure what an appropriate fix would be though...

**Comment by thomasrudin** [comment]
@SwissalpS congrats: you reported a bug you have inadvertently caused yourself, now only flammable nodes can be set on fire :rofl: (as your issue in LoneWolfHT/lavastuff#6)

@OgelGames thx

**Comment by SwissalpS** [comment]
yep, I sort of regret reporting it :/
Would like to be able to repair lava sword on anvil again.

**Comment by SwissalpS** [comment]
[could we test this on test-server?](https://github.com/SwissalpS/lavastuff/tree/patch-1)
I think it needs testing on a more complex world than my small test-world.

@thomasrudin

**Comment by thomasrudin** [comment]
> could we test this on test-server?

I pulled the latest mods-repo and your lavastuff changes (`patch-1`), the world may be a few days/weeks old though.

You have sufficient privileges on your main (?) account to play around i think :smile:
I can't automatically publish the logs because that would revert the changes again (long story) let me know if you need the crash-logs...

**Comment by SwissalpS** [comment]
thank you very much. If it crashes, I'll know what I was doing and recreate it on my server, so np.

**Comment by SwissalpS** [comment]
anvil, itemframe and itemframe:pedestal is still a problem -> duplicates item.
But doors, vendors and such worked fine.

On a side-note: I was not able to fly around green beacons.

**Comment by thomasrudin** [comment]
> On a side-note: I was not able to fly around green beacons.

https://github.com/pandorabox-io/pandorabox_custom/blob/master/fly.lua#L49

**Comment by SwissalpS** [comment]
[my patch-2 branch seems to work](https://github.com/SwissalpS/lavastuff/tree/patch-2)
May we please test it on testserver before I PR the change upstream?

**Comment by SwissalpS** [comment]
thanks, have submitted PR to upstream
