### ISSUE TITLE
Metal signs cannot be neither updated nor removed

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#314]
jackb confirmed that I'm not the only one experiencing this

**Comment by thomasrudin** [comment]
I heard that one before but could not reproduce it :confused: 
Are we talking about the `default:sign_wall_steel` node?

**Comment by int-ua** [comment]
Yes, `default:sign_wall_steel`. News at my base is on example. Don't have direct coordinates at hand right now, TravelHub > gold > int

**Comment by thomasrudin** [comment]
Addressed here: https://gitlab.com/VanessaE/signs_lib/issues/5

**Comment by int-ua** [comment]
Looks like it's fixed.
