### ISSUE TITLE
Cherry tree blossom leaves grow after cutting down

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#316]
If you cut cherry tree bossom leaves and place it, leaves starts growing to cherry. For eg. If you harvest blueberry leaves and put it again leaves stop producing blueberries. The idea is to create artifical node which looks like the same as original node but without growing up. 

texture:
https://github.com/runsy/cool_trees/blob/master/cherrytree/textures/cherrytree_blossom_leaves.png

**Comment by thomasrudin** [comment]
I'd like to solve that like the `default` game does it:
https://github.com/minetest/minetest_game/blob/master/mods/default/functions.lua#L399

Manually placed leaves get a `param2 = 1`:
```lua
default.after_place_leaves = function(pos, placer, itemstack, pointed_thing)
	if placer and placer:is_player() and not placer:get_player_control().sneak then
		local node = minetest.get_node(pos)
		node.param2 = 1
		minetest.set_node(pos, node)
	end
end
```

Just let your tree as it is right now, this can be fixed...
