### ISSUE TITLE
Bamboo and pandas

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#317]
Just saw the addition of bamboo from the cool trees mod, and thought I'd note that currently the pandas in the mobs animal mod only eat ethereal bamboo (https://notabug.org/TenPlus1/mobs_animal/src/master/panda.lua#L36), not the cool trees bamboo.

**Comment by thomasrudin** [comment]
Addressed here: https://notabug.org/TenPlus1/mobs_animal/issues/12
