### ISSUE TITLE
Redwood can't be cut by chainsaw

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#318]
Rather than just adding another set of nodes to cut, I'm going to try to implement some code from the woodcutting mod (https://github.com/thomasrudin-mt/woodcutting/blob/nil-check/init.lua#L368) that finds what nodes it can cut automatically, so that this doesn't keep happening.

**Comment by thomasrudin** [comment]
i added the bounty to your inventory, let me know if it isn't there :confused:
