### ISSUE TITLE
Missing scifi-node recipe

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#319]
Reported by *JRPete*
```
scifi_nodes:blue_door_closed has no craft recipe. 
```

**Comment by OgelGames** [comment]
Fixed: https://github.com/D00Med/scifi_nodes/commit/caa98d98b1fb59ba7d0493c1b9bac721f9990bd1

**Comment by thomasrudin** [comment]
thx :+1: did you get the bug-bounty?

**Comment by OgelGames** [comment]
Yes, thanks for that :smile:
