### ISSUE TITLE
replace poshud mod

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#321]
simple mod with mapblock display

**Comment by thomasrudin** [comment]
@SwissalpS is https://github.com/SwissalpS/postool ready? i'd like to throw the `poshud` mod out, i have the feeling that there will be less hud-related issues then... :smile:

**Comment by SwissalpS** [comment]
yes, postool should be ready.
I also just made some changes to poshud_light to see if it's the technique used that causes the trouble.
poshud, until now, would make and remove the hud element whenever turned on or off
postool makes the hud elements when user joins and only hides the content when switched off.
maybe this is why poshud can fix certain hud related issues but maybe it is also the cause.
I'm liking postool a lot, it's not as light but combines the currently important data into one
configurable hud.

**Comment by SwissalpS** [comment]
I was on testserver. The longer update-delay is a good idea for many reasons. Helps make ppl linger to get a better reading.

**Comment by thomasrudin** [comment]
Thanks :+1: 
I merged my test-branch with the added `postool` and removed `poshud`  (https://github.com/pandorabox-io/pandorabox-mods/pull/159)

The server should pull that in automatically the next few minutes (https://github.com/pandorabox-io/pandorabox-mods/issues/3)
