### ISSUE TITLE
Node replacer doesn't place functioning deployers

### ISSUE THREAD

**Issue by WoosterUK** [pandorabox-io/pandorabox.io#322]
I was trying to build an autoplanter using deployers, and because I was doing a mass install, I used the node replacer to put down the deployers. Any deployer placed by node replacer (pointing in at least two different directions) didn't work properly, while the ones placed by hand did.

**Comment by coil0** [comment]
Since pandorabox-io/pandorabox-mods#177 it calls `on_places` and the deployers work.
