### ISSUE TITLE
incorrect recipe for farming:salt

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#326]
bucket of water after cooking, don't throw empty bucket into output slot.

**Comment by thomasrudin** [comment]
Looks like a limitation of the crafting/cooking type:
https://notabug.org/TenPlus1/farming/src/master/food.lua#L39

**Comment by thomasrudin** [comment]
I checked that yesterday and cooking a water bucket produces salt+empty bucket...
What _did_ you expect?

**Comment by kubaorlen** [comment]
indeed:
Bucket of water ----> Empty bucket + Salt

**Comment by kubaorlen** [comment]
How actually is:
![screenshot_20190923_171907](https://user-images.githubusercontent.com/41878182/65438793-5f452000-de26-11e9-91f5-bf58281ca707.png)
How should be:
![screenshot_20190923_171916](https://user-images.githubusercontent.com/41878182/65438813-6704c480-de26-11e9-8f0e-7850faf89c18.png)

**Comment by thomasrudin** [comment]
Oh! thx for the images :smile: now i get it, but i have no clue yet how to solve this...

**Comment by OgelGames** [comment]
I did some digging into this, and found a way to fix it, so that it works exactly as in the second image above. It only applies for the technic furnaces, the default ones still work as they did before.

I also removed the unrealistic salt recipe from pandorabox_custom. (sorry @6r1d 😄)
