### ISSUE TITLE
Mail crashes server when mail title looks like "<invalid UTF-8 string>"

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#328]
It's a second time the whole MT server reloads when I am checking my mail.

I am using my native language for some mails and sometimes I now see “<invalid UTF-8 string>” instead of the title. Title itself contains several “Re: “ parts, but isn't long. 36 characters, three lines.

When I open an email, server crashes. I think I even saw the contents, but then I used web mail.

I think it can be linked to web mail trying to use user's own encoding, which can be either UTF-8 or CP-1251 on Windows.

**Comment by 6r1d** [comment]
UPD: no crash on another message.
I will check with several other messages in the future to check if it was related.

**Comment by thomasrudin** [comment]
I can't find a stacktrace for that, was that recent about, an hour ago?

**Comment by 6r1d** [comment]
Yes, it happened today.
We also had train issues at the time, but this issue happened twice: I've been checking mail, server crashed.

**Comment by BuckarooBanzay** [comment]
stale, closing this, reopening if it happens again...
