### ISSUE TITLE
Bones in nuclear reactor

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#330]
Possible prevention: item drop if in reactor...

**Comment by OgelGames** [comment]
> replaces bones in an active reactor with a water source

Not really sure that's the best way to fix this, if a player dies in the reactor, all their stuff will be lost...

**Comment by thomasrudin** [comment]
> > replaces bones in an active reactor with a water source
> 
> Not really sure that's the best way to fix this, if a player dies in the reactor, all their stuff will be lost...

Suggestions? maybe drop the inventory if the `bones` chest is full?
What do you expect when you take a swim in the water of a nuclear reactor...? :smile:

**Comment by OgelGames** [comment]
> Suggestions?

Well there is one idea I thought of; with the standard configuration of NRs in the game, the only way to die in the water around the core is via the air filled access hole, so maybe the bones could be moved into that "safe" space.

**Comment by thomasrudin** [comment]
thanks again :smile:
