### ISSUE TITLE
advtrains: impossible to set routing code in train Onboard Computer

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#338]
wagons.lua:889: attempt to call field 'lzb_invalidate' (a nil value)

please add full traceback (can't copy from chat history) and I'll forward it to advtrains bugtracker.

**Comment by thomasrudin** [comment]
Thx for the report, can we try this again with the new version?
I think we are quite a few commits behind the current version :confused: 

I'm setting up the test-server the next few days with all the shiny/experimental stuff :smile:

**Comment by thomasrudin** [comment]
The test-server (`test.pandorabox.io`) is now equipped with the latest advtrains code.
Can you try that there again?

**Comment by int-ua** [comment]
In a couple of hours, thank you :)

**Comment by thomasrudin** [comment]
no feedback, closing this. feel free to reopen if that is still an issue...
