### ISSUE TITLE
Stained framed obsidian glass don't connect in the vertical direction

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#339]
![screenshot_20190926_172447](https://user-images.githubusercontent.com/41878182/65702709-c4498180-e083-11e9-8d38-17390013d3e2.png)

**Comment by thomasrudin** [comment]
Yeah, i know: one of my builds looks like this since the 0.4 -> 5.0 upgrade, this may be an engine issue :confounded:

**Comment by BuckarooBanzay** [comment]
Upstream issue: https://github.com/minetest/minetest/issues/9542
