### ISSUE TITLE
Nodereplacement tool can dig protected digtron crates on open/free area

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#340]
After dig, crate becomes useless.

**Comment by thomasrudin** [comment]
Related: #322
A fix would be to put them on the blacklist...

**Comment by thomasrudin** [comment]
this should work now: https://github.com/SwissalpS/replacer/blob/005fa9bddbbc1941e200ee186aa3bca14b13426f/init.lua#L463

**Comment by coil0** [comment]
When I tested, the crate was added to inventory but lost its metadata.

**Comment by thomasrudin** [comment]
Too bad, i thought `minetest.node_dig()` would invoke the calls on the crate properly... :(

**Comment by OgelGames** [comment]
Fixed here: https://github.com/SwissalpS/replacer/pull/2
