### ISSUE TITLE
vacuumable items on scifinodes:itemholder and power_stand

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#341]
1) Items placed on item holder or power stand can be vacuumed by tube, this feature/bug allows to build workshop with automatic theft option.

2) Issue to scifinodes:itemholder on protected area, players can take items but can't put it back, better idea is to work like in itemframes:pedestal.

**Comment by OgelGames** [comment]
Related: https://github.com/pandorabox-io/pandorabox.io/issues/293

Probably the best fix for both would be to use the code from itemframes:pedestal.

**Comment by OgelGames** [comment]
> Probably the best fix for both would be to use the code from itemframes:pedestal.

Done: https://github.com/D00Med/scifi_nodes/pull/22

**Comment by kubaorlen** [comment]
You are right we can use itemframes:pedestal for item holder but not for power stand. On item holder  we usually leave item for long time, but on power stand you place item for seconds. itemframes:pedestal code is not enought, it requires return item to inventory after punching itemholder/power stand.

**Comment by OgelGames** [comment]
> but on power stand you place item for seconds

Why is that, isn't it supposed to be a display stand?
If you mean to use it for instant repair, the new code fixes that bug too :wink:

**Comment by kubaorlen** [comment]
I sugget to not fix this bug 😜

**Comment by SwissalpS** [comment]
> I sugget to not fix this bug

I agree, it's a feature. But the vacuuming part is a bug.

**Comment by thomasrudin** [comment]
@OgelGames nice! :smile:
