### ISSUE TITLE
Quarry block misses

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#342]
![screenshot_20191002_200404](https://user-images.githubusercontent.com/1026711/66069509-ce6df300-e54f-11e9-9519-0809320bc9c0.png)

**Comment by thomasrudin** [comment]
stale, closing

**Comment by S-S-X** [comment]
note that this issue got worse and quarries misses a lot more blocks than before.
but then, was quarries going to have update soon or maybe already updated?

**Comment by thomasrudin** [comment]
>  but then, was quarries going to have update soon or maybe already updated?

Not directly, no. But i plan to introduce a better replacement instead:
https://github.com/thomasrudin-mt/enhanced_quarry

The aim is to be less laggy, more throughput and have better controls (mesecons/digilines/etc)
