### ISSUE TITLE
Possible language chat fixing

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#345]
It's good idea to help players to skip the step of typing /jc command.
Every new player on server could get window like this:
![screenshot_20190926_172447](https://user-images.githubusercontent.com/41878182/67098979-6b21c900-f1bd-11e9-868e-ac0b3dbadc7b.png)

Choosing flag could execute command:

Cross ---> do nothing (#main) 
English flag ---> do nothing (#main) 
Germany flag ---> /jc de
Russian flag ---> /jc ru
Spanish flag ---> /jc es
French flag ---> /jc fr

**Comment by thomasrudin** [comment]
Oh, that would look nice...
That would be some kind of onboarding screen, shown only once on join...
I'll take a look at this when i have some free time...

**Comment by kubaorlen** [comment]
Two issues:

1) I'm not sure did I include all existing language channels?

2) Maybe add inscription under each flag:
English flag ---> English
Germany flag ---> Deutsch
Russian flag ---> Pусский
Spanish flag ---> Español
French flag ---> Français

**Comment by SwissalpS** [comment]
I have forked beerchat, refactored some and added functionality to facilitate this idea.
https://github.com/SwissalpS/beerchat

adds chat-command: /force2channel <channel>, <player>
which can also be invoked from a formspec result by calling:
beerchat.force_player_to_channel("name_of_issuer", "channel, player_name")

also adds /list_muted

**Comment by thomasrudin** [comment]
> I have forked beerchat, refactored some and added functionality to facilitate this idea.

That looks good, i see you fixed some of the attribute-stuff too :open_mouth: 

> adds chat-command: /force2channel

:+1: 

What are your future plans? can we merge that someday?

**Comment by SwissalpS** [comment]
Once tested on a multiplayer server, we can merge. I don't have any plans for the near future.

**Comment by SwissalpS** [comment]
Have not heard from any testers. My master branch has worked for me on a multiplayer setup with pandorabox mod selection.

Added /whis for those who can't access '$' on their keyboard.

**Comment by thomasrudin** [comment]
merged in @SwissalpS 's changes (https://github.com/pandorabox-io/beerchat/pull/2)

dependabot should pick the commits up and kick of an initial test..

**Comment by int-ua** [comment]
Using flags for language selection is generally not recommended https://ux.stackexchange.com/questions/11891/should-i-use-country-flags-in-language-selection-fields
In short: avoiding collisions and moving away from politics.

**Comment by BuckarooBanzay** [comment]
closing, feel free to make PR's though
