### ISSUE TITLE
Open area depends on xp

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#352]
There could be command which allow to create open areas depends on player xp.

- If player don't have enought xp, area works like protected area.

- If player have enought xp, area works like open area.

Example how this command could look:
`/area_xp <ID> <xp_limit>`

To disable xp area:
`/area_xp <ID>`

**Comment by SwissalpS** [comment]
I like the idea. It would need to take 2 values imo, to give a range. That way you could keep high XP players out of areas too.

**Comment by thomasrudin** [comment]
Good idea!

### Notes for myself

Areas API:
* `areas:getAreasAtPos(pos)`
* `areas:getNodeOwners(pos)`
* `areas:isAreaOwner(id, name)`

**Comment by thomasrudin** [comment]
I'm still in the testing phase, but maybe the `priv-protector` will help you with your issues:
* https://pandorabox.io/wiki/index.php/Priv-protector

This would make it possible to define a priv, for example `hifi_market_south_east`, place priv-protectors with that priv (they are easy to place and configure) and invite (grant) the priv to the owners you want there.

For the priv-granting we could set up a mesecons contraption with a command block...

**Comment by SwissalpS** [comment]
@6r1d had an idea: change fancy vendors so co-sellers can change the settings. Permitting rent-a-vendor booths.

**Comment by 6r1d** [comment]
> @6r1d had an idea
Yeah, also, now that I visited HiFi, I wonder if your idea of a temporary mod duplicating a protection in a given range is faster to implement.

Syntax can be the same, area_pos1 and area_pos2, extended with a direction (+x, +z, -x, -z) and a step.

> change fancy vendors so co-sellers can change the settings
Now we have smartshops, currency:shops and fancy vendors in booths there, which is more than one vendor type to change.

> Permitting rent-a-vendor booths.
I wonder how to go about ownership transfer there?

Simplistic version: korlen "sells" his booths with a sign. These booths are somehow connected or just ajacent.

More complex version: booths are "rented", so after booth is staying empty for a while, other people will be able to re-rent it.
How do we drop items / money, earned by a person who abandoned a booth, though? Fork Wi-Fi chests?

**Comment by OgelGames** [comment]
What I was thinking was to expand on the `/area_open` command just like was done for the playerfactions mod. I also thought it would probably be worth adding priv-protection the same way as well, so the commands would be something like this:

* `/area_open <ID>` - Open the area to everyone
* `/area_xp_open <ID> <minxp>` - Open the area to players with enough xp
* `/area_priv_open <ID> <priv>` - Open the area to anyone who has the specified privilege
* `/area_close <ID>` - Reset the area to owner only protection

**Comment by kubaorlen** [comment]
This idea make sense to me. To be trust i wanted to use `/area_xp_open` only to prevent workshop griefing which is very disappointing last time. `/area_priv_open` is also very good idea to prevent the griefing. I never thought to use `/area_priv_open` or `/area_xp_open` for hifi marketplace, but this issue is still huge problem, because you can destroy vendors by using node-replacement tool or mining drill. I was thinking about next extension of this mod and make co-owners areas which can be owned by joining to them. 

`/area_to_take <ID>` - Create protected area owned by primary player. Again usage this command turn off this type of area
`/area_join <ID>` - Allows player to own this area, now  only primary player have acces to all stuff on this area.
`area_kick <ID>` - Remove player from this area, to avoid situation when player start abuse and start owning to many areas.

Time_Styler made me realize of this problem, because he placed protector block on his shop place in hifi marketplace and i lost conrtrol on this area also shopping place on the other side cannot be used.

**Comment by thomasrudin** [comment]
@kubaorlen regarding the hifi market place: did you check out the xp-protectors? (`xp_redo:protector`) they behave much like you want the area-proposal to, just a little more fine-grained...

**Comment by thomasrudin** [comment]
Should work now, documentation is here: https://github.com/mt-mods/xp_redo/#areas-integration

**Comment by OgelGames** [comment]
Just when I was nearly finished adding it to the areas mod... 
I think I'll still keep working on it though, because I'm also adding the priv protection. Also I think it makes more sense to be in the areas mod anyway. :wink:

**Comment by thomasrudin** [comment]
> I think I'll still keep working on it though

Yes please, that sounds a bit cleaner... :+1:

> EDIT: priv protection has been added too: pandorabox-io/priv_protector@4acff2d

Uhm yeah, that was me... 
I haven't gotten around to merge my accounts yet.. :confounded: 
This should be all of my accounts/mails that i use:
* https://github.com/thomasrudin
* naturefreshmilk (i opened that to code while at work but i don't think anyone cares anyway... :man_shrugging:)
* https://github.com/BuckarooBanzay (i'm going to use that one after i'm done merging the projects someday :smile:)

**Comment by OgelGames** [comment]
> that was me...

Yeah I know, I figured that out a while ago 😄 

Also, just did some testing, and I found neither of them work... Or rather they do after setting the xp/priv, but they stop working after a restart 😟

**Comment by thomasrudin** [comment]
Oh, silly bug, thanks :+1:
