### ISSUE TITLE
Upgrade replacer to active fork

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#353]
Looks like @Sokomine 's `replacer` repo is not maintained anymore (https://github.com/Sokomine/replacer/pulls)

## Alternatives

* https://github.com/HybridDog/replacer
* ?

## Link/Issues

* #350 
* #322

**Comment by SwissalpS** [comment]
launching Meld....

**Comment by thomasrudin** [comment]
"Meld" ? :confused:

**Comment by SwissalpS** [comment]
Yeah, Meld :) (3-way diffs with GUI)

seems to work: https://github.com/SwissalpS/replacer/commit/d2a7bf224f21c9b50c9b46e678ac58a6aa0e80a8

inspection tool still removes mobs that have spawned 'naturally'. No problem found with tamed ones.

I've combined our last version with most of HybridDogs changes. Left out mainly the recipe change.

**Comment by thomasrudin** [comment]
closing this, the `replacer` mod is "up-to-date" again... :)
