### ISSUE TITLE
fancyvend crash

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#354]
```
minetest_1           | 2019-11-10 16:55:22: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnUse(): /data/world//worldmods/fancy_vend/init.lua:1503: attempt to index local 'new_settings' (a nil value)
minetest_1           | 2019-11-10 16:55:22: ERROR[Main]: stack traceback:
minetest_1           | 2019-11-10 16:55:22: ERROR[Main]: 	/data/world//worldmods/fancy_vend/init.lua:1503: in function </data/world//worldmods/fancy_vend/init.lua:1493>
m
```

**Comment by SwissalpS** [comment]
seems that if you use a wand without ever having read settings it crashes minetest.

**Comment by SwissalpS** [comment]
suggest fixing like this:
https://github.com/pandorabox-io/fancy_vend/pull/1/commits/6dbaa3869ea533de8cc67378b565062b3e55ddaa

**Comment by thomasrudin** [comment]
I'd like to converge/switch to one repo at some point, ChimneySwift's repo has a few additional commits that fix a few bugs too... :/

How hard are you hanging on your local commit/PR?

**Comment by SwissalpS** [comment]
not at all. I just offered a fix, if there is a better solution, let's take that. Agree to use an active fork.

**Comment by thomasrudin** [comment]
fixed by https://github.com/pandorabox-io/fancy_vend/pull/2

cleaning up the fork later :tm:
