### ISSUE TITLE
Something is wrong with wiki?

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#356]
- Can't upload images.
- Pages with edited article aren't displayed, only old article is visible.

**Comment by thomasrudin** [comment]
> Can't upload images.

Sorry about the issues, forgot to change the permissions after the update :confounded: 
Should work again...

> Pages with edited article aren't displayed, only old article is visible.

This works for me... what exactly are you trying to do..?

:+1: thanks for reporting

**Comment by kubaorlen** [comment]
I'm trying to update HiFi City and my profile page.
