### ISSUE TITLE
Improperly denied enterance

### ISSUE THREAD

**Issue by FullTimeLinux** [pandorabox-io/pandorabox.io#357]
I attempted to connect to the server while it was not full 23/25 people online. However was denied access because it was full some how??? Please increase the number of players to a better number like 100.

**Comment by thomasrudin** [comment]
whats your ingame name?

**Comment by thomasrudin** [comment]
closing, feel free to reopen if you are still interested...

**Comment by FullTimeLinux** [comment]
Well I was able to log in today, so I guess I must have experienced a glitch.
