### ISSUE TITLE
doors/coral crash

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#358]
```
minetest_1           | 2019-11-13 18:24:53: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...l/share/minetest/games/minetest_game/mods/doors/init.lua:141: attempt to index local 'def' (a nil value)
minetest_1           | 2019-11-13 18:24:53: ERROR[Main]: stack traceback:
minetest_1           | 2019-11-13 18:24:53: ERROR[Main]: 	...l/share/minetest/games/minetest_game/mods/doors/init.lua:141: in function 'door_toggle'
minetest_1           | 2019-11-13 18:24:53: ERROR[Main]: 	...l/share/minetest/games/minetest_game/mods/doors/init.lua:382: in function 'on_rightclick'
minetest_1           | 2019-11-13 18:24:53: ERROR[Main]: 	...hare/minetest/games/minetest_game/mods/default/nodes.lua:2034: in function <...hare/minetest/games/minetest_game/mods/default/nodes.lua:2022>

```

**Comment by OgelGames** [comment]
Fixed here: https://github.com/minetest/minetest_game/pull/2539

**Comment by paramat** [comment]
Now merged in MTGame.

**Comment by thomasrudin** [comment]
Thanks @OgelGames and @paramat :+1: 

@paramat i'm considering to track the `master` branch of the `minetest_game` for pandorabox, how feasible/good is that in your opinion, stability wise?

**Comment by paramat** [comment]
thomasrudin, MTG master branch is the development version of MTG, so it is risky to use that for a server. Sometimes we make mistakes and revert things, occasionally this could cause problems for a server.

**Comment by thomasrudin** [comment]
I added an item-override in the `hacks.lua` of the `pandorabox_custom` mod.
This needs to be removed when the next mt-game gets released...

I also look into packaging the `minetest_game` outside of the engine (it gets cloned in the Dockerfile) so that bugfixes can be cherry-picked next time... :smile:
