### ISSUE TITLE
WARNING !!! Server requires immediate intervention

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#359]
All Teleporting tubes stop working, which cause breaking tubes in many machines !!! Some fix is requires to prevent a disaster.

**Comment by thomasrudin** [comment]
Done: it was a race-condition between two tp-tubes implementations.
Fixed the problem, all tube-configs are reverted to the config from 2019-11-15_02-00-08 and should work again.
The new ones need a "push" (configuration)...

Please reopen if there are any other issues...
