### ISSUE TITLE
pipeworks teleport-tubes receivers can't be neighbours

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#361]
when two or more receiving tp-tubes connect, the items sent to them stay in tubes and don't go into vendor/self contained injector. (suspect all chests and machines are affected too).
Could be a priority issue.

**Comment by thomasrudin** [comment]
can you give me the itemstring of the tube? If it isn't something from `pipeworks:teleport_tube_1` to `pipeworks:teleport_tube_10` then i know where the bug is... :/

**Comment by SwissalpS** [comment]
yes, pipeworks:teleport_tube_x

**Comment by SwissalpS** [comment]
seems fixed :D thanks.

**Comment by thomasrudin** [comment]
> seems fixed :D thanks.

thx for testing
