### ISSUE TITLE
Teleporting tubes stopped sending items

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#362]
May be related to #361 but looks like started only today

**Comment by thomasrudin** [comment]
Can you give me the direction to that tube, in case it works again for me :smile:

**Comment by int-ua** [comment]
Well, it was discussed in #main a lot, I hoped some players sent reports through /mail, just wanted to create the issue here. Anyway, Stores II > Light Tower > int:jam tp tube above the apple sappling, drop anything not in the sorting tube list on the floor and watch it stuck in a loop.

**Comment by thomasrudin** [comment]
A possible workaround would be to re-enter the formspec ro toggle some buttons...

**Comment by OgelGames** [comment]
> A possible workaround would be to re-enter the formspec

Yes, I had a few tubes stop working too, and re-entering the settings (I think only on the receiver if I remember right) got them working again.

**Comment by OgelGames** [comment]
Update: This issue is far worse than I though, every tp tube on the server is affected, and a lot of tubes are breaking! The HiFi City workshop and skipper's H.A.C.C are two places where I've seen multiple tp tubes with items stuck in them, as well as broken tubes dropping stacks of items 😟

Something needs to be done to fix this issue, and fast!

**Comment by thomasrudin** [comment]
> Something needs to be done to fix this issue, and fast!

I see what i can do, don't expect miracles though. In the worst case the latest `pipeworks` upstream change has to be reverted:
* https://github.com/pandorabox-io/pandorabox-mods/commit/fb0579896228d052db9d85d5ac9c931ab0020102
* https://github.com/pandorabox-io/pandorabox-mods/commit/a7555b78e0330da87dc266f831f6701f44c7c6f7

**Comment by thomasrudin** [comment]
@OgelGames i reverted to the latest working state, feel free to restart. otherwise i'll do it later today...

**Comment by OgelGames** [comment]
Me restart? How am I supposed to do that? :confused:

**Comment by OgelGames** [comment]
Looks like you were a few steps ahead of me :smile: 
Your fix should do the job :+1:

**Comment by thomasrudin** [comment]
closing this, thx to all
