### ISSUE TITLE
It is possible to lose armor on death with empty inventory

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#364]
I just died with just everyday carry in inventory (5 items) and armor fell to the ground instead of appearing in bones. Maybe it has to do with the fact that I landed on a 1/16th slab and bones appeared one node higher than coordinates on death.

**Comment by OgelGames** [comment]
I had this happen to me not long ago in my testing world, might be some change or bug in 5.1.0, didn't happen before then unless my inventory was full...

**Comment by int-ua** [comment]
I had it on Pandorabox since I started playing almost (was it May? I don't remember)

**Comment by thomasrudin** [comment]
> didn't believe me previously

I saw that a few times but could not reproduce it, besides: it _is_ death we are talking about, it should not be a nice thing :)

Don't know how to fix that yet, there is an option to disable item-drop on death but that does not fit survival imo...

**Comment by int-ua** [comment]
> it should not be a nice thing :)

Agreed, feel free to close it :)

**Comment by thomasrudin** [comment]
> Agreed, feel free to close it :)

No, i _do_ think the armor not appearing in the bones is a bug!

Here is the relevant code (from 3d-armor):
https://github.com/stujones11/minetest-3d_armor/blob/master/3d_armor/init.lua#L335

Looks like it just searches for bones in the player-death area and puts it in there, if:
* there is enough room
* the name of the bones match

Also: the bones have to be in the 8 nodes range of the body.

Are we talking here about a high-velocity impact? This may cause the bones to be placed far away from the body and thus the dropped armor...

**Comment by int-ua** [comment]
> a high-velocity impact?

yes
