### ISSUE TITLE
Items lost when moving armor from wear slots to inventory over them

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#365]
Steps to reproduce:
1. Wear armor item.
2. Left click it.
3. Place it over any inexpensive item in your inventory.

Originally reported in #main by chuche952

**Comment by thomasrudin** [comment]
References:
* Mod repo: https://github.com/stujones11/minetest-3d_armor/issues/165
* Blocky: https://github.com/BlockySurvival/issue-tracker/issues/51
* Possbile fix by @brhee: https://github.com/stujones11/minetest-3d_armor/pull/168
