### ISSUE TITLE
Falling item / woodcutting crash

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#367]
```
minetest_1           | 2019-12-04 19:14:38: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): /data/world//worldmods/woodcutting/init.lua:320: bad argument #1 to 'get_content_id' (string expected, got nil)
minetest_1           | 2019-12-04 19:14:38: ERROR[Main]: stack traceback:
minetest_1           | 2019-12-04 19:14:38: ERROR[Main]: 	[C]: in function 'get_content_id'
minetest_1           | 2019-12-04 19:14:38: ERROR[Main]: 	/data/world//worldmods/woodcutting/init.lua:320: in function 'callback'
minetest_1           | 2019-12-04 19:14:38: ERROR[Main]: 	/data/world//worldmods/falling_item/init.lua:234: in function </data/world//worldmods/falling_item/init.lua:119>

```

Temporary fix with https://github.com/pandorabox-io/pandorabox-mods/commit/fb5b6c657c92cadb26655d4670929083e69b29ca

**Comment by OgelGames** [comment]
Turns out that this was caused by the same mistake as the doors/coral crash - passing the name of a node to a function instead of the node itself.

https://notabug.org/TenPlus1/falling_item/pulls/1

**Comment by thomasrudin** [comment]
Thanks for looking at this, i just copied&pasted the stacktrace and removed the mod but didn't have the time to check it out :+1: 

Sidenote: tenplus1 tends to "merge" code his own way, mostly modifying it and commiting under his name...

**Comment by OgelGames** [comment]
https://notabug.org/TenPlus1/falling_item/commit/b0f2de10902c0f323ebbf2db4d4e099a8791a3f1

**Comment by thomasrudin** [comment]
> mostly modifying it and commiting under his name
:rofl: 

but cool, thanks :+1:
