### ISSUE TITLE
Mapserver only displays one item in smartshop

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#369]
![smartshop](https://user-images.githubusercontent.com/48543043/70295212-4bf8fc80-183a-11ea-9547-fb326e01ac24.png)
Should display all 4 items for sale, with empty slots displaying a placeholder.

Searching does work though, for all items in smartshop.

**Comment by thomasrudin** [comment]
Main-issue here: https://github.com/minetest-mapserver/mapserver/issues/71

**Comment by thomasrudin** [comment]
Closing issue here (duplicate)
