### ISSUE TITLE
Illumination mod not working on server

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#370]
The illumination mod is still not working on the pandorabox server as of now, I've checked the code and nothing seems to be wrong, and the current version of the mod works perfectly on my test server.

The only thing I can think of is that the mod is not up to date on the server, even though it seems like the server was restarted recently enough that it should be.

**Comment by thomasrudin** [comment]
Well, this is odd: the mods are up-to-date, the update-mechanism worked but the illumination does not work... :confused: 

Even weirder is that it works on the test-server with the same mod-state (but different world-backup)...

I'll check the code for performance-related issues, maybe the playercount/lag has something to do with it...

**Comment by OgelGames** [comment]
Finally fixed it: https://github.com/pandorabox-io/illumination/commit/dc3ff559197d02d4703f6aa7be932cef59d0376a

**Comment by OgelGames** [comment]
Working now. Closing.
