### ISSUE TITLE
Automatic granted privileges

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#373]
There is no reason to get some privallages using mission blocks. Privallages could be granted automaticly with xp. It's annoying when you try to explain someone how use `areas_protector` but player don't have privallage, then you have to show player where get this privallage.

Suggested privs granted automaticly:
- `areas_protector`
- `areas_high_limit`
- `jumpdrive_land`

Privallage room on spawn would act as an information room (about xp permission limit).

**Comment by thomasrudin** [comment]
The `mission` block was the quickest tool for the job at the moment.
Optimally there would be grant hooks on xp leveling, i'll look into that...
