### ISSUE TITLE
Possibility to lose items when assigning output from the vendor storage

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#375]
1. Put a stack of 10 apples and two stacks of one apple each into your inventory.
2. Open fancy vendor interface.
3. Put one apple into vendor storage.
4. Assign output items from stack of 10, stack of 1 and from vendor storage trying to unassign output by taking apple from output slot into a free space in your inventory between each operation.

**Comment by OgelGames** [comment]
It took me a while to figure this one out, but it's actually a simple fix; prevent moving items into input and output slots.
