### ISSUE TITLE
pipeworks repo cleanup

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#379]
@SwissalpS i'd like to clean up the unused repos. is there anything in `pipeworks` that has not been merged/moved out of there? Can i remove that?

**Comment by SwissalpS** [comment]
@thomasrudin I have nothing pending in pipeworks and the overrides in pandora_custom should work no matter where the repo is hosted.
From what I can see, go ahead :)

**Comment by thomasrudin** [comment]
thanks for checking
