### ISSUE TITLE
Recipe collisions

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#382]
* `mypaths:grass`: unregister/change

**Comment by OgelGames** [comment]
Would be a simple fix, to just change the `default:dirt` in the recipe to `default:grass_1`: https://github.com/minetest-mods/mypaths/blob/master/grass.lua#L99
Repo hasn't been updated in 4 years though, so probably will need to fork it to fix it...

**Comment by thomasrudin** [comment]
i unregistered and registered the recipe in the custom repo, i don't think an upstream change is needed here, the `dirt_compressed` node comes from the `moreblocks` mod. This only happens if you add `mypaths` _and_ `moreblocks` anyway..

**Comment by OgelGames** [comment]
Nice, I forgot that was possible :smile:
