### ISSUE TITLE
Light Tower clock crash

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#383]
I was rotating a green digital clock with a sonic screwdriver next to a running water tile and a travelnet nearby when the server crashed and it is now crashing each time I try to login.

**Comment by int-ua** [comment]
> AsyncErr: ServerThread::run Lua: Runtime error from mod 'ontime_clocks' in callback LuaABM::trigger():
> ...9/.minetest/mods/display_modpack/display_api/display.lua:173: attempt to index local 'ov' (a nil value)
> stack traceback:
> 	...9/.minetest/mods/display_modpack/display_api/display.lua:173: in function <...9/.minetest/mods/display_modpack/display_api/display.lua:160>
>

**Comment by int-ua** [comment]
Should `facedir_values[0]` at https://github.com/pyrollo/display_modpack/blob/master/display_api/display.lua#L122 be `facedir_values[1]` maybe?

**Comment by SwissalpS** [comment]
certainly not lua (index 0)

**Comment by coil0** [comment]
`facedir_values[0]` is defined in this case, so that’s not the reason it returns nil.

**Comment by int-ua** [comment]
My local server now crashes on login and I'm ready to test your suggestions. Testing 1 first...

**Comment by int-ua** [comment]
Change suggested by a92, didn't work:
```diff
diff --git a/display_api/display.lua b/display_api/display.lua
index 2fed40f..42a49aa 100644
--- a/display_api/display.lua
+++ b/display_api/display.lua
@@ -116,7 +116,7 @@ local function get_orientation_values(node)
 		if paramtype2 == "wallmounted" or paramtype2 == "colorwallmounted" then
 			return wallmounted_values[node.param2 % 8]
 		elseif paramtype2 == "facedir" or paramtype2 == "colorfacedir"  then
-			return facedir_values[node.param2 % 32]
+			return facedir_values[node.param2 % 24]
 		else
 			-- No orientation or unknown orientation type
 			return facedir_values[0]
```

**Comment by OgelGames** [comment]
https://github.com/pyrollo/display_modpack/blob/master/display_api/display.lua#L72

Seems like this should use `ipairs` not `pairs`

**Comment by SwissalpS** [comment]
pairs works on lists too, at least those I've tried.

**Comment by int-ua** [comment]
> Seems like this should use `ipairs` not `pairs`
> Same for #L76

didn't work

```diff
diff --git a/display_api/display.lua b/display_api/display.lua
index 2fed40f..27ab79c 100644
--- a/display_api/display.lua
+++ b/display_api/display.lua
@@ -69,11 +69,11 @@ local function compute_values(r)
 		restricted=(r.x==0 and r.z==0) }
 end
 
-for i, r in pairs(facedir_rotations) do
+for i, r in ipairs(facedir_rotations) do
 	facedir_values[i] = compute_values(r)
 end
 
-for i, r in pairs(wallmounted_rotations) do
+for i, r in ipairs(wallmounted_rotations) do
 	wallmounted_values[i] = compute_values(r)
 end
```

**Comment by int-ua** [comment]
`paramtype2` is `"wallmounted"`

**Comment by int-ua** [comment]
With `wallmounted_values[node.param2 % 6]` (suggested by a92) it loaded but clock display is broken this way.

**Comment by int-ua** [comment]
Making a PR with this temporary fix:

```diff
diff --git a/display_api/display.lua b/display_api/display.lua
index 2fed40f..dd0b3fc 100644
--- a/display_api/display.lua
+++ b/display_api/display.lua
@@ -114,6 +114,9 @@ local function get_orientation_values(node)
 	if ndef then
 		local paramtype2 = ndef.paramtype2
 		if paramtype2 == "wallmounted" or paramtype2 == "colorwallmounted" then
+			if (wallmounted_values[node.param2 % 8] == nil) then
+				return facedir_values[0]
+			end
 			return wallmounted_values[node.param2 % 8]
 		elseif paramtype2 == "facedir" or paramtype2 == "colorfacedir"  then
 			return facedir_values[node.param2 % 32]
```

**Comment by int-ua** [comment]
wait, coil already created https://github.com/pyrollo/display_modpack/pull/37/files

**Comment by OgelGames** [comment]
So do those PRs fix the crashing on login on your local server @int-ua?
If so maybe the `display_modpack` should be forked temporarily, so the fix can be applied to the server sooner?

**Comment by int-ua** [comment]
Yes, I was able to login with my patch, didn't add coil changes though.
I'm waiting for it be forked, yes. Can you do that and force server code update?

**Comment by OgelGames** [comment]
@int-ua does coil's fork also work? https://github.com/coil0/display_modpack/tree/pandorabox
I can update it now if it does.

**Comment by OgelGames** [comment]
Didn't mean to close this yet...

**Comment by OgelGames** [comment]
Ok, just restarted the server, @int-ua try logging in to see if it's fixed.

**Comment by int-ua** [comment]
Crashing fixed, thank you.

**Comment by thomasrudin** [comment]
i thought something was wrong when i saw the unread count on my mailbox this morning...
Impressive detective work without the logfiles... :open_mouth: 

I opened an issue (#384) for that but i'm not sure yet how to publish the logs without some kind of shell acces...

**Comment by SwissalpS** [comment]
> i'm not sure yet how to publish the logs without some kind of shell acces...

Don't, it would take the fun away :p
There would be a possibility of the watchdog to copy last x lines of log to a static page. (on start)
But I fear that could open another pandoras box. We wouldn't want DMs to appear in public logs.
