### ISSUE TITLE
No item loss on death for new players

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#391]
New players shouldn't lost their equipment to 5k xp (any another value) . This can motivate players who died in short time by stupid way.

**Comment by OgelGames** [comment]
If this would be added, new players would think there are no consequences for death, which would lead to more carelessness, and more deaths; until of course, they pass the xp threshold, and wonder why now they loose their stuff.

**Comment by kubaorlen** [comment]
Yes, you are right, but player disappointment is better than player lost.

**Comment by BobFred7** [comment]
> Yes, you are right, but player disappointment is better than player lost.

I don't think we need to worry about player loss, considering that now we have enough players that the server is usually at 20 or more online.

Alternative idea: when players under 5K XP (or some threshold like that) die, they will lose items except for the starter items (iron pickaxe, apples, torches) that they had in their inventory

**Comment by thomasrudin** [comment]
@kubaorlen i'm opposed: the survival-mechanics should not change with player experience...

**Comment by int-ua** [comment]
I'm probably late, but I'll still throw an idea into the brainstorm pile: you could've mitigated misunderstandings by adding explanation text to that "You died. Respawn" dialog.
