### ISSUE TITLE
Doors recipes.

### ISSUE THREAD

**Issue by Soviet-Glider** [pandorabox-io/pandorabox.io#394]
Both "Mahogany Closet Door" and "Basic white panel Door" are uncraftable as one ingredient in each recipe are incorrect, I remember the same case with "French door, White" and "French door, Mahogany-colored" from the same mod : homedecor, which was fixed.

**Comment by OgelGames** [comment]
> I remember the same case with "French door, White" and "French door, Mahogany-colored" from the same mod : homedecor, which was fixed.

Yes, that was here: https://gitlab.com/VanessaE/homedecor_modpack/commit/d17ec1d9782bcfa17621d8769cd018f222338aaf
I've opened a PR to fix the recipes here:  https://gitlab.com/VanessaE/homedecor_modpack/merge_requests/8

**Comment by OgelGames** [comment]
PR has been merged, can close after mod repository has been updated 😉
