### ISSUE TITLE
cherry tree trunks can't be easily built on

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#397]
reproduce: place cherry tree trunk and try to place another on it. Same goes for other nodes. The trunk seems to refuse to accept them.
I was not able to place with sneak+click nor special+click however others have reported success with sneak+click.

**Comment by OgelGames** [comment]
Seems to be because of `on_rightclick` being unnecessarily defined: https://github.com/runsy/cool_trees/blob/master/cherrytree/init.lua#L128

Some other trees in the `cool_trees` modpack have the same thing, some have it commented out, others have it removed.

**Comment by thomasrudin** [comment]
Had the same issue with another tree of the mod but didn't get around to create a PR yet...
I'll update here if i start working to prevent duplicate fixing attempts... :smile:

**Comment by OgelGames** [comment]
Fixed: https://github.com/runsy/cool_trees/commit/95a616dcdeab7e1b46020d78e5c6c8476e813ce0
