### ISSUE TITLE
lightweight tpr-mod

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#402]
Like this: https://github.com/ChaosWormz/teleport-request
Just without all the bugs and strange "features"...

**Comment by BobFred7** [comment]
Can you be specific about the differences?

**Comment by thomasrudin** [comment]
>  i.e. what strange "features" are in the old tpr mod?

* evade enemy
  * `/tpe`
  * https://github.com/ChaosWormz/teleport-request/blob/master/init.lua#L627

* teleport to place
  * `/tpp`
  * https://github.com/ChaosWormz/teleport-request/blob/master/init.lua#L544
  * (but the actual configuration is checked into the vcs :confused:)

* duplicate teleport command (builtin)
  * `/tpc`
  * https://github.com/ChaosWormz/teleport-request/blob/master/init.lua#L613

**Comment by thomasrudin** [comment]
closing, the mod seems stable enough now...
