### ISSUE TITLE
Too much quarries, causes many of them not working

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#405]
I have 32 qruarry ship, If I eneble them all about 6-8 of them not working, it gives message `digging not started` or `digging 3m above machine` but in fact the machine does nothing. I rebuilded my ship 3 times with the same amount of quarries in a different configuration and error is still the same.

To check this bug go to `Travelhub` --> korlen network (`net2`) --> `ship` 
**Please mail before enter.**

**Comment by OgelGames** [comment]
It's not a bug, it's the per-player digging limit:
https://github.com/pandorabox-io/technic/blob/pandorabox/technic/machines/HV/quarry.lua#L22
https://pandorabox.io/wiki/index.php/Technic#Quarry_limits.2Fquota

**Comment by thomasrudin** [comment]
Side-note: the quarries are very inefficient cpu-wise, i tuned them a bit a few days back, maybe the per-player limit can be further lifted if they get better.

Lag/Quarry-stats: https://monitoring.minetest.land/d/qflCE8YWz/technic-fork?orgId=1&refresh=5s&var-instance=pandorabox.io (its the "switching station time usage", this should not get above ~100ms)
