### ISSUE TITLE
fast walking on spawn

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#409]
Like this: https://github.com/damocles-minetest/damocles_custom/blob/master/center_fast_walk.lua

**Comment by OgelGames** [comment]
Could be useful, but wouldn't it lead to a lot of new players asking why they're walking slow after leaving spawn?

**Comment by BobFred7** [comment]
Put a clear message that "you walk faster here" at spawn?

**Comment by SwissalpS** [comment]
Yes, they will ask and get a 'yes, you can walk faster at spawn' response. Just like they do when they find out that water can be used as a ladder and other game mechanics like beacons.

I don't like the idea of plastering spawn with posters, rather use wiki to inform of nuts and bolt details.

**Comment by kubaorlen** [comment]
I have another idea next to 'running faster on spawn'. Automatic teleport to spawn if `cobble peasant` fell down or display screen with info `type /spawn inorder to back on spawn`.

**Comment by thomasrudin** [comment]
i implemented this with a speed factor of 2, lets see what the reactions are...
