### ISSUE TITLE
show /news on logon depending on XP

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#410]
First time I logged on, I read it. About the fifth time I read it again. After that I only read it after I invoke /news, never when logging on.

Do others also feel it could be dropped for users that frequently log on?
I suggest only showing it to users bellow a certain low XP amount.

**Comment by OgelGames** [comment]
I look at it briefly to see if there's anything new, but otherwise I don't read it, but if it was never shown, I would never remember to look at it... :smile: 
Maybe there could be a toggle for it, just like for the XP hud, so players could choose if they want to see it?

**Comment by thomasrudin** [comment]
The original idea was to put _actual_ news in there, looks like this
is just a welcome banner now, so the xp-limit works for me...

**Comment by SwissalpS** [comment]
server_news mod has a priv already setup: news_bypass
so it would only need to be another priv one gets when passing certain XP amount.

**Comment by OgelGames** [comment]
> server_news mod has a priv already setup: news_bypass
> so it would only need to be another priv one gets when passing certain XP amount.

Yes, but that always stops the news from being shown: https://github.com/Ezhh/server_news/blob/master/init.lua#L24
I guess it's an okay solution for now though...

**Comment by thomasrudin** [comment]
i removed the `server_news` mod until a better solution and actual news-content comes along :smile:

**Comment by thomasrudin** [comment]
@SwissalpS sorry, i just saw your edit after pulling: https://github.com/pandorabox-io/pandorabox_custom/commit/ed9c948a84a40deabf3f0037d3f5dd7d21e38a16 :confounded: 

is it ok if we leave the `server_news` disabled until there is a news-concept or something alike...?

**Comment by SwissalpS** [comment]
@thomasrudin I'm fine with that.
@OgelGames yes, that was the point, to hide news for players who know about /news.
Mostly, when logging on, it's not what players care about. Especially if there was a crash while they were gliding.

500 XP may be rather low, maybe a threshold at stone level would be better.
