### ISSUE TITLE
Dark grey dye trier-3 extender not working

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#411]
**Dark grey dye** trier-3 extender for `telemosaic` not working. I didn't test all dyes, but this one not working for sure.

**Comment by OgelGames** [comment]
Possibly could be this line not working correctly: https://github.com/pandorabox-io/telemosaic/blob/master/teleport.lua#L26
Does dark green work? It also has an extra underscore in its name.
