### ISSUE TITLE
Make server logs visible to moderators

### ISSUE THREAD

**Issue by kiedtl** [pandorabox-io/pandorabox.io#413]
This could be useful, for instance, in cases of griefing/vandalism. moderators should be able to easily access server logs to find the culprit.

Sorry if this has been raised before.

**Comment by OgelGames** [comment]
It has: https://github.com/pandorabox-io/pandorabox.io/issues/384
Which resulted in this: https://pandorabox.io/error-log.txt
Though that is only for errors, and it doesn't seem like it's working properly yet, as it doesn't have the most recent crash.

**Comment by thomasrudin** [comment]
this should work now: https://pandorabox.io/crashlogs/
(this is world-readable, but shouldn't contain any sensitive data)

**Comment by kiedtl** [comment]
Sorry if this is a stupid question -- but won't this only contain crash data? Whereas I what I wanted was actual server logs -- `player XX placed node XXX on xxx,yyy`, for example

**Comment by thomasrudin** [comment]
> but won't this only contain crash data

sorry misread that... :/

i think i can make the logs available to download with a password...

**Comment by SwissalpS** [comment]
> what I wanted was actual server logs -- `player XX placed node XXX on xxx,yyy`, for example

That level of detail is questionable. It would reveal where some are building 'secret' base. It's not that I don't understand why this would be useful to check who is griefing, so I agree that it should only be available to moderators, if at all.

**Comment by S-S-X** [comment]
> That level of detail is questionable. It would reveal where some are building 'secret' base.

For checking actions we do not need access to full raw logs. Honestly, I don't trust all moderators either but also I don't have big problems with idea that logs would be accessible by moderators.

However, if anyone sees this as too big problem then there could also be command to get logs for are where moderator is standing at. That would allow getting enough information to investigate different situations where players have asked for help and/or reported griefing.

Of course downside of this approach is that it would require writing another piece of software and should then be mod in-game.

**Comment by thomasrudin** [comment]
> However, if anyone sees this as too big problem then there could also be command to get logs for area where moderator is standing at.

This likely needs something like `elasticsearch` or similar. I don't know if there is enough CPU/RAM to spare for that.. :disappointed:

> Rollback check privileges would also work here if rollback is enabled.

Rollback does not work reliably and is pretty heavy on the cpu front too...

**Comment by BuckarooBanzay** [comment]
viewing the logs is now possible with `ssh readonly@pandorabox.io` (for staff/devs/moderators)
