### ISSUE TITLE
Dry shrubs / brown paint

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#414]
Opening by the request of lernpvp.
You can't "mix" a dry shrub to make a brown paint. (I think you get sticks instead.)
Also, as @int-ua pointed out, an extracting gives 4x less brown paint, too.

**Comment by OgelGames** [comment]
Yep, stick recipe is registered by `moreblocks` (https://github.com/minetest-mods/moreblocks/blob/master/crafting.lua#L8), dye extracting recipe is in `technic` (https://github.com/pandorabox-io/technic/blob/pandorabox/technic/machines/register/extractor_recipes.lua#L20), and dye crafting is in `bakedclay` (https://notabug.org/TenPlus1/bakedclay/src/master/init.lua#L129).

**Comment by thomasrudin** [comment]
thanks @OgelGames
