### ISSUE TITLE
Drawers omit last inventory slot when double-clicking

### ISSUE THREAD

**Issue by int-ua** [pandorabox-io/pandorabox.io#415]
Should be fixed by https://github.com/minetest-mods/drawers/pull/37 but I didn't test

**Comment by OgelGames** [comment]
Nice, I've been meaning to look at fixing that for awhile, but kept forgetting 😄

**Comment by thomasrudin** [comment]
never noticed that myself until now :open_mouth:

**Comment by OgelGames** [comment]
Should be fixed by https://github.com/pandorabox-io/pandorabox-mods/commit/4c62082637bcdd330199e1f6b869bc38327ee996
