### ISSUE TITLE
new /remove_chernobylite command

### ISSUE THREAD

**Issue by kiedtl** [pandorabox-io/pandorabox.io#417]
Recently, I was trying to pad my corium container with gold. Unfortunately, in the process, corium leaked out and spilled everywhere. Luckily, the area was protected, so nothing was lost. However, tons of chernobylite was stuck everywhere and it took a long time to clean up.

Worse, my (public) workshop was very close to the chernobylite spill. If someone came there without a hazmat they would've been fried alive.

I think a new /remove_chernobylite command/privs (just like the /remove_lavastone command) would be good, both for those who are griefed and for those who are just careless.

Thoughts?

**Comment by OgelGames** [comment]
> I think a new /remove_chernobylite command/privs (just like the /remove_lavastone command) would be good, both for those who are griefed and for those who are just careless.

Totally agree :+1: The other day a player had a huge corium spill after their reactor was split when jumping, it definitely would have been useful to have a command to clean it up.

**Comment by thomasrudin** [comment]
Good idea, i'll refactor the `lavastone`-mod (https://github.com/pandorabox-io/lavastone) for that, as it has all the logic in it..

Candidates for cleanup:
* `/lavastone_remove` (also removes flowing lava)
* `/chernobylite_remove`
* `/corium_remove` (not sure about that...)
* `/flowing_water_remove` (maybe only for mods/staff)

**Comment by kiedtl** [comment]
/flowing_water_remove would definitely be useful in cases of lava greifing. In my case, water was poured on top of the lava to make it solidify, and I still have to clean some of that water up :/

**Comment by OgelGames** [comment]
> * `/corium_remove` (not sure about that...)

Maybe just flowing corium? Or will that be part of `/chernobylite_remove`?

**Comment by kiedtl** [comment]
> Maybe just flowing corium? Or will that be part of /chernobylite_remove?

If `/corium_remove` is going to be implemented, I vote for making it only apply to *flowing* corium. I mean, what if that command removed corium source too, and that command was run inside someone's chernobylite factory...

**Comment by thomasrudin** [comment]
Removing **flowing** corium won't do any harm, the corium source itself should only be removable by staff/members.

The issue i see with removing flowing water is the potential to meltdown a nuclear reactor :/

**Comment by kiedtl** [comment]
Nuclear reactors will have (*should*) water *sources*, not flowing water.

Even if some miserable heretic decided to put just one layer of water sources, and just let the water flow, only flowing water would be removed, and the water sources would flow again and fill the empty nodes... right?

**Comment by S-S-X** [comment]
> * `/lavastone_remove` (also removes flowing lava)
This is good for fixing things even while it is also being used for mining operations.

> * `/chernobylite_remove`
Unless we have another chernobylite node that is similar to lavastone then I'd say this should require either moderator privileges/high xp or it should respect protections.
Maybe those requirements even if there would be another node for nodes not placed by player

> * `/corium_remove` (not sure about that...)
I'd vote big NO for that, corium is easy to remove without any additional commands and you have trashcan in inventory...

> * `/flowing_water_remove` (maybe only for mods/staff)
Agree with only for mods or high xp
