### ISSUE TITLE
"Ghost teleportation" sound effect

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#418]
In the past couple days, it has repeatedly happened to me (and I've heard reports from other players) that I hear the /tpy sound effect when no one had been teleporting to me and I had not been teleporting to anyone. I suspect this is due to the sound effect not being limited to nearby players and being played globally. It's possible this has been fixed since the last time I logged on.

**Comment by thomasrudin** [comment]
Yes, this is fixed since https://github.com/pandorabox-io/pandorabox-mods/commit/f99c9de006f83063db5e764f54549a6a6ba32d06

Thanks to @tuedel :+1: 

I'm closing this, thanks for reporting :smile:
