### ISSUE TITLE
Online crafting guide

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#420]
Like the in-game crafting guide, but it runs separately from the minetest server
This could be useful if the server is lagging a lot but we still want to do some crafting research
Or if we want to do crafting research without logging on
I think there have been some other people who wanted this

**Comment by thomasrudin** [comment]
I started something like that: https://github.com/thomasrudin-mt/mtinfo
but thats nowhere near usable yet... :P

**Comment by SwissalpS** [comment]
I like the idea. It would also enable calculations of raw materials needed etc. (eventually)

**Comment by thomasrudin** [comment]
> I like the idea. It would also enable calculations of raw materials needed etc. (eventually)

That was one of the goals, a kind of recipe-calculator with all steps in between, it also serves as a "showcase" for the server(s).

**fyi**: the current state of the `mtinfo` mod extracts all the data from the ingame to json-files but i haven't had time to properly display it in a meaningful way, just the skeleton webapp...

**Comment by BobFred7** [comment]
Where will we test/develop it? Will it be in pandorabox.io during development?

**Comment by BuckarooBanzay** [comment]
https://pandorabox-io.github.io/pandorabox-mods/#/
