### ISSUE TITLE
Players online / max players is not displayed in server list

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#423]
When I go to "join game" on the Minetest main menu and I see Pandorabox, instead of two numbers separated by a slash to show the number of players online and the maximum number of players, it shows "? / ?". For all other servers I can see on the list, it works properly. Pandorabox is marked as a favorite on my personal server list and I'm using Minetest 5.0.1

**Comment by OgelGames** [comment]
That is just the `server_cloak` mod: https://github.com/pandorabox-io/server_cloak
It's not a bug :wink:

**Comment by thomasrudin** [comment]
@BobFred7 a little background: we have a pretty good inflow of new players and it is quite laggy if we hit the current cap of 30 players and everybody uses some kind of machinery. So i decided we just don't announce anymore if the server is on top of the list...

Of course it is still there and you can connect at any time to it :smile:

**Comment by BobFred7** [comment]
Yeah, that's what I realized shortly after posting the issue
Well, if anyone questions that later, we just link here :)
