### ISSUE TITLE
/area_pos set can't be used on deployers

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#425]
I was protecting an area that had deployers in the corners. It was impossible to do without replacing the deployers first then placing them back after area was protected.

**Comment by BuckarooBanzay** [comment]
Can you elaborate on this? If you protect with `/area_pos1/2` the node **must** be walkable and you standing in there, i don't think any solid node is markable this way...

**Comment by SwissalpS** [comment]
sorry, I was not clear. Using "/area_pos set" then punch two corners.

**Comment by BuckarooBanzay** [comment]
issue is placed upstream: https://github.com/minetest-mods/areas/issues/41
closing this ussue
