### ISSUE TITLE
Water thirst 

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#429]
Water thirst come as hunger. Has the same effects as food. But full water supply and with very low level food or full supply food and with critical level of water  player will die. 
Water thirst can be refill by any fermented drinks or any types of water. 
Empty glass or empty bottle can be used for water containing and drinking. Refilling water can be form block of water, as with empty bucket but not effect even for single water block. Empty bottle or empty glass can contain less water than empty bucket. 
Public and private drinking galeries.

**Comment by Emil9736** [comment]
OgelGames, can you explain your reaction ? I can`t read your mind.

**Comment by OgelGames** [comment]
Oh sorry about that 😄 I like the idea, but if it has the same effects as hunger, then I'm not sure if it's really worth adding. Also, I find hunger to be an annoying feature when I'm playing, and adding more complexity would only make it worse 😄

**Comment by Emil9736** [comment]
We can develope  idea. I think that some difficulties make game more interesting. One of them just have added in this server :D 
Let it be not default water.  
Techic: (lv,mv and hv) water cleanner. Also it will refill empty bottle or empty glass by cleaned water. 
Water with sugar refill supply of food, but some slower and recover health units faster than simple water.

**Comment by thomasrudin** [comment]
I was once on a server that had separate hunger, thirst and stamina bars, it was quite awful to get started there :/

I'm (almost-)neutral about the idea, the concept/implementation should not alienate the players..

**Comment by Emil9736** [comment]
Yes, I have been to on this server. It can not be bare. Without stamina. Sorry for out of topic. How about icons for armour level as for hunger ? It can show you breaking of armour.

**Comment by kiedtl** [comment]
I vote a big NO for this. in my humble opinion, it's bad enough that I have to carry around food, but water too? and not just ordinary water, but special refined water?

Also, I think this increases the barrier for new players to join, since they will not have a water cleaner and will have to buy water from vending stalls.

**Comment by Emil9736** [comment]
Ok. Can you suggest better idea ?

**Comment by S-S-X** [comment]
> it's bad enough that I have to carry around food, but water too?

This is survival (not creative) after all so I don't really see what is problem with carrying food.

> Also, I think this increases the barrier for new players to join, since they will not have a water cleaner and will have to buy water from vending stalls.

Agreed with that. I think thirst will add too much complexity especially for new players.
However, we could allow drinking water without any special treatment.

Maybe this could be implemented somehow, like allowing food to balance out some need for water and vice versa.
But would still probably be nearly impossible to implement this well without adding separate bar for thirst.

Maybe possible if one would need some water and some food to fill completely but could still survive with just food or water.

**Comment by Emil9736** [comment]
Yes, kiedtl. I Agree with you. It must be simple craft filter, for example 3 stell ingots, paper and coal dust. Put 1 water bucket and get after some time cleaned water in bucket. 1 bucket of cleand water refill full thirt. Beginners will start with 1 or more buckets with cleaned water. And I we don`t need special technic lv/mv/hv or technic not hardly craft water cleanner, which will clean faster than simple.

**Comment by Emil9736** [comment]
Golden middle near the first part of idean and this moment, which we discuss.

**Comment by Emil9736** [comment]
It can be placed in public workhops, spawn and shops multiply. For drinking galeries - faucet with water tank or with water refill machine, which accommodate 32 or more water buckets and refill empty buckets, empty glass or empty bottles.  Or let players can be use default water for refill thirst by bucket, glass and bottle. 1 bucket - refill fully. 1 bottle refill 1/2 and 1 glass of water refill 1/4 water ballance.

**Comment by 6r1d** [comment]
What if we automate food and water consumption using invnetory slots? I'd prefer to use these, fill from time to time and actually play instead of monitoring stamina. :-)

**Comment by kiedtl** [comment]
> What if we automate food and water consumption using invnetory slots? I'd prefer to use these fill from time to time and actually play instead of monitoring stamina.

Would be nice, but then there's the problem that new players won't really realize they need to eat until it's too late...

**Comment by BobFred7** [comment]
I'm against adding a thirst system or anything else that's like a secondary hunger/stamina system
What I think would be reasonable, though, is nerfing some of the more effective food sources :tomato:

**Comment by 6r1d** [comment]
> Would be nice, but then there's the problem that new players won't really realize they need to eat until it's too late...
Then it's ok to give people food and leave a slot empty for them to fill it. And then they eat, remember they need to eat at all, use slot, forget it for some time and it's too late, but after they understand the concept. And they are learning!

**Comment by SwissalpS** [comment]
> What if we automate food and water consumption using invnetory slots?

Isn't that essentially just making hunger last longer?
Refill hunger-bar by eating == adding stack to inventory which slowly depletes.

As for drinking, only coconut milk and plain water quench thirst. Sugar drinks and fermented
beverages make more thirsty if anything.

I'm not against idea of thirst, but rather have effort put into healing potions/pills.

**Comment by S-S-X** [comment]
> What if we automate food and water consumption using invnetory slots?

Voting No. This is not adding anything into game, instead it is taking away and adding confusion and more complexity than adding thirst and bottles.

This would need dedicated inventory slots for food and drinkable liquid. This reduces flexibility and forces you to use inventory in specific way.
I can see many situations where player does not want to drink or eat even if he does have inventory full of food. Also to stop eating and drinking one would need to use items that cannot be eaten in dedicated food / water slots.

Without dedicated inventory slots it will force you to eat and drink even if you dont want to.
With dedicated inventory slots it gets really complicated, hard to use and overall not good idea.

**What to do then?**
Do soft launch for drinking: There's already that another open issue [#323 Temporary food effects](https://github.com/pandorabox-io/pandorabox.io/issues/323) that could be used to add some extra benefits for drinking water.

I see temporary food effects as very good feature, now all foods/drinks have exact same effect. Only some are better and some worthless. This issue overlaps a lot with #323 and imo should be handled together or at least each other taken into account while implementing eating/drinking behaviors.

Drinking could be implemented in way that allows later setting it to required or more beneficial to encourage using drinkable liquids if it is determined that it would be good change.

**Comment by Emil9736** [comment]
Many possibilities just have realisated here. Not simple to invent new benefits. And it will add useless features more complexity, entanglement in game. Thank you for your attention and participation.

**Comment by thomasrudin** [comment]
Thanks @Emil9736 for encouraging the discussion :+1:

**Comment by OgelGames** [comment]
> add some extra benefits for drinking water.

Something like increasing the hunger refilled by food by some percentage if a drink was consumed recently?
That would be a good way to implement it IMO, as it wouldn't impact the current system at all.
