### ISSUE TITLE
Digtron Inventory bug

### ISSUE THREAD

**Issue by JRPete2020** [pandorabox-io/pandorabox.io#431]
Digtron stopped for lack of fuel, all inventory formspecs are blank with no slots, the digger heads now contain the formspecs for the inventory.

**Comment by S-S-X** [comment]
This is well known issue, you can take items from digger heads and remove + replace components and start digging again.

Problem can be somewhat mitigated by using higher delays, making sure that all areas near tron are generated before digtron goes near mapblock edges and *not* using digtron when there's any lag on server.

Breakages will still happen but are very rare when you use 15-20 second delay / cycle intervals and make sure that mapgen never gets near digtron.

These tron issues are waiting for a lot larger overhaul of digtron mod, I dont happen to know how it is going forward if it is going forward at all.

**Comment by S-S-X** [comment]
Issues in pandorabox.io repository:
https://github.com/pandorabox-io/pandorabox.io/issues?q=digtron

Upstream repo has some more information too but basically this most probably will not be fixed before upstream or someone(tm), currently working with complete digtron mod rewrite, provides fix.

**Comment by thomasrudin** [comment]
thanks @S-S-X 

Also: a reliable "repro" of the issue would be the first step towards solving this...
