### ISSUE TITLE
receive_iterations_per_step set twice in minetest.conf

### ISSUE THREAD

**Issue by tuedel** [pandorabox-io/pandorabox.io#435]
https://github.com/pandorabox-io/pandorabox.io/blob/master/minetest.conf#L113
https://github.com/pandorabox-io/pandorabox.io/blob/master/minetest.conf#L159

Just stumbled across this. Has potential to cause some confusion eventually :wink:

**Comment by thomasrudin** [comment]
thank you :+1: , i need to reformat that anyway, the `receive_iterations_per_step` setting is not used anymore, the changes are now upstream thanks to sfan5...
