### ISSUE TITLE
Why is anticheat disabled?

### ISSUE THREAD

**Issue by Panquesito7** [pandorabox-io/pandorabox.io#436]

**Comment by thomasrudin** [comment]
There were some issues with bouncing back to the previous coordinate if you used a jumpdrive (anticheat got triggered).
That was some time ago though, maybe i should test that again... :+1:

**Comment by Emil9736** [comment]
Are there cheats for this server ?

**Comment by thomasrudin** [comment]
> Are there cheats for this server ?

Hehe, you wish... (i hope not)
The anticheat messed with the jumpdrive/teleport operation, so i disabled it.
I see if i can re-test if that works again with anticheat enabled...

it was the "moved too fast" anticheat by the way...

**Comment by Emil9736** [comment]
Of cource not. With cheats it`s so senselessly and it is not honest.

**Comment by Emil9736** [comment]
Before this issue i have not thought about it. I was wondered.

**Comment by coil0** [comment]
> I see if i can re-test if that works again with anticheat enabled...

If not, maybe the mod can increase the speed monoid to a very high value (dependent on distance jumped) for all players around the jumpdrive before jumping?

**Comment by BobFred7** [comment]
> > I see if i can re-test if that works again with anticheat enabled...
> 
> If not, maybe the mod can increase the speed monoid to a very high value (dependent on distance jumped) for all players around the jumpdrive before jumping?

I think we would also have the "player moved too fast" problem with anticheat with travelnets and telemosaics, right?

**Comment by thomasrudin** [comment]
> If not, maybe the mod can increase the speed monoid to a very high value (dependent on distance jumped) for all players around the jumpdrive before jumping?

Sounds like a good idea if everything else fails...

> I think we would also have the "player moved too fast" problem with anticheat with travelnets and telemosaics, right?

As far as i remember the problem was that a player clicks the engine "jump" button and starts to walk away after that, somehow the server got the events mixes up and the player seems to have moved in the original position *after* the jump to the new position...

**Comment by Lejo1** [comment]
Disabling anticheat is a pretty critical thing...
You can theoretical dig any blocks as fast as you want anywhere in the world and teleport wherever you want to go to even if you are dead. Of course the Minetest-Anti-Cheat is not the best, but it at least blocks the most malicious things.

What about attaching the player to the new position for a short time?

**Comment by BuckarooBanzay** [comment]
> You can theoretical dig any blocks as fast as you want anywhere in the world and teleport wherever you want to go to even if you are dead.

As far as i understand this is not quite true, *some* anticheat mechanisms are still in place:
We have a `#audit` channel in discord for moderators that is filled with cheat-messages:

```
Player 'xxx' triggered anticheat: 'interacted_while_dead' at position: (6812,12,22837)
Player 'xxx' triggered anticheat: 'interacted_too_far' at position: (-2545,245,563)
```

Source: https://github.com/minetest-beerchat/beerchat/blob/master/web/tx.lua#L73

> Disabling anticheat is a pretty critical thing...

Still true, it is re-enabled, lets see how it works... :smirk:

**Comment by Lejo1** [comment]
Yeah, seems just like you only disable the moved_too_fast anticheat.

**Comment by SwissalpS** [comment]
Recently I noticed that after jumping, or even just using travelnet, my avatar keeps getting tp-ed back to origin after a couple seconds. Not every time, just often enough for me to notice.
Probably during lag-spikes.
Possibly related?

**Comment by BobFred7** [comment]
I've noticed that when just moving around (usually just during lag spikes) I will get frequently teleported back a bit
I was wearing lava boots but I don't think I was sprinting

**Comment by BuckarooBanzay** [comment]
>  Possibly related?

@SwissalpS most likely yes.. :disappointed: 

> I will get frequently teleported back a bit

I think i'll disabled the anticheat setting again, there are lots of false-positives in the `audit` channel on discord and the benfits are not that much...
