### ISSUE TITLE
Additional glass types

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#438]
Hello. Recently I've been thinking that my (and many other) fields might look better without a ton of glass fragments above each. A simple ``glowing`` AND ``transparent`` glass type might solve that, since we have machines to seed and harvest vegetables. So I made another version of a steel framed obsidian glass. [There it is](https://github.com/6r1d/minetest_new_glass).

It also might be useful to [decorate rooms](https://i.imgur.com/ZduMl8C.png) and [make everything](https://i.imgur.com/j0bVEJl.png) [brighter](https://i.imgur.com/QdkFCae.png).

I'd like to use a new material on my field, if it's ok.

We also discussed this idea in chat. It's possible that we might want other glass types in the future, for example, something like a ``dark_glass`` node from ``scifi_nodes``, but as a colored version. For now, though, I am concerned with issue #63 (I doubt I ever saw colored framed glass and I will have to check that), and I am not completely sure how to implement the coloring part.

**Comment by OgelGames** [comment]
So basically it's glowing framed glass, nice 👍

Yes, framed glass can be colored, that is what is used on the space globe at spawn: https://pandorabox.io/wiki/index.php/Spawn_2.0#/media/File:Spawn_3.0_205246.png

As for adding color to your glass, this documents it: (look at the section at the bottom) https://gitlab.com/VanessaE/unifieddyes/-/blob/master/API.md

**Comment by thomasrudin** [comment]
Nice idea, sounds useful

> I doubt I ever saw colored framed glass and I will have to check that

It is used practically everywhere :smile:
Hint: use the airbrush to dye the framed glass (only obsidian_framed)

Another thing: glow-glass can be dyed too and it does glow (but it is not that transparent)
Example: My "Tardis" in Technic city...

**Comment by 6r1d** [comment]
> look at the section at the bottom
Thanks, I see now.

> but it is not that transparent
Yeah, it's my very reason to write this glass type

> It is used practically everywhere
I see; saw the issue and thought it is some other material, so I wanted to check.

**Comment by 6r1d** [comment]
Another update, added colored dark glass.

I'd be thankful for any reviews and help with vertical connections between colored framed glasses. Actually, can we connect all types of framed glasses and leave no frame between these?

**Comment by thomasrudin** [comment]
> UPD: sometimes each block's frame is visible in original framedglass, so I think it's more generic framedglass issue.

Yes, sadly (again) an engine issue: #339

**Comment by SwissalpS** [comment]
I've tested [37c8cee](https://github.com/6r1d/minetest_new_glass/tree/37c8cee5d2245b45fc35f2a06c4fd640079f13cb)
it works fine and suggest we add it to meta-repo.
However I also suggest setting new_glass.hide_recipe_super_steel_framed to 1 as I don't see any
difference visually.
Also I think in the long run this should be merged into framed_glass mod.

@thomasrudin @coil0 @S-S-X @OgelGames

**Comment by 6r1d** [comment]
> I don't see any difference visually.

Since we discussed that yesterday, I made one glow half as intense. Maybe there's some use.
![](https://i.imgur.com/ixvbEGkh.png)

> Also I think in the long run this should be merged into framed_glass mod.

What about colored dark glass? I can try scifi_nodes.

**Comment by SwissalpS** [comment]
funny I tested again today and didn't see the difference with coloured nodes. On your screenshot it does look different.

**Comment by 6r1d** [comment]
Weird, I zipped and cloned the repo locally, same result.

**Comment by thomasrudin** [comment]
@6r1d i see if i have some time the next few days to test this, looks promising so far...

**Comment by thomasrudin** [comment]
@6r1d the mod looks good :+1: , i added my comments as issues, feel free to address them as you like

Can you make a PR for the `pandorabox-mods` repo? I think we could include it in the current state...

**Comment by 6r1d** [comment]
> feel free to address them as you like

Sure thing! I think mod's a bit better now.

> EDIT: the smoked glass is a nice idea too smile

I'm glad it'll have some use.

**Comment by thomasrudin** [comment]
Merged in master, should be active on the next restart/crash, closing...
