### ISSUE TITLE
beerchat PM to multiple players does not work

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#441]
[Please see issue here](https://github.com/minetest-beerchat/beerchat/issues/6)

**Comment by S-S-X** [comment]
Maybe this should be implemented in mail instead of chat.
Allow mail to have bcc recipients, this could be done by allowing comma separated recipients.

**Comment by thomasrudin** [comment]
> Maybe this should be implemented in mail instead of chat.
Allow mail to have bcc recipients, this could be done by allowing comma separated recipients.

Yes, thats what i intended to work on but haven't got time/motivation yet :smile:

**Comment by SwissalpS** [comment]
considering this closed, maybe @S-S-X will sneak in the change to remove the help comment about this function being supported in his refactor of beerchat.
