### ISSUE TITLE
Various crashes

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#444]
```
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'mob_horse' in callback luaentity_Step(): /data/world//worldmods/mobs/api.lua:252: attempt to index local 'v' (a nil value)
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: stack traceback:
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:252: in function 'get_velocity'
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:990: in function 'do_jump'
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:2083: in function 'do_states'
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:3253: in function 'func'
minetest_1        | 2020-02-12 10:16:42: ERROR[Main]: 	...ocal/share/minetest/builtin/profiler/instrumentation.lua:106: in function <...ocal/share/minetest/builtin/profiler/instrumentation.lua:100>
```

```
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod '3d_armor' in callback environment_Step(): /data/world//worldmods/skinsdb/api.lua:5: attempt to index local 'player' (a nil value)
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: stack traceback:
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	/data/world//worldmods/skinsdb/api.lua:5: in function 'get_player_skin'
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	/data/world//worldmods/skinsdb/init.lua:37: in function 'get_player_skin'
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	/data/world//worldmods/3d_armor/3d_armor/init.lua:249: in function 'init_player_armor'
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	/data/world//worldmods/3d_armor/3d_armor/init.lua:308: in function 'func'
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	/usr/local/share/minetest/builtin/common/after.lua:20: in function 'globalstep'
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	...//worldmods/monitoring/monitoring/builtin/globalstep.lua:29: in function <...//worldmods/monitoring/monitoring/builtin/globalstep.lua:20>
minetest_1        | 2020-02-12 10:34:22: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:429: in function </usr/local/share/minetest/builtin/game/register.lua:413>
```

```
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): /data/world//worldmods/mobs/api.lua:1013: bad argument #1 to 'sin' (number expected, got nil)
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: stack traceback:
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: 	[C]: in function 'sin'
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:1013: in function 'do_jump'
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:2086: in function 'do_states'
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: 	/data/world//worldmods/mobs/api.lua:3256: in function 'func'
minetest_1        | 2020-02-12 10:37:25: ERROR[Main]: 	...ocal/share/minetest/builtin/profiler/instrumentation.lua:106: in function <...ocal/share/minetest/builtin/profiler/instrumentation.lua:100>

```

# Links
* https://notabug.org/TenPlus1/mobs_redo/src/master/api.lua#L252

# Potential causes
* https://github.com/minetest/minetest/pull/9390

**Comment by sfan5** [comment]
<pre>
ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod '3d_armor' in callback environment_Step(): /data/world//worldmods/skinsdb/api.lua:5: attempt to index local 'player' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	/data/world//worldmods/skinsdb/api.lua:5: in function 'get_player_skin'
ERROR[Main]: 	/data/world//worldmods/skinsdb/init.lua:37: in function 'get_player_skin'
ERROR[Main]: 	/data/world//worldmods/3d_armor/3d_armor/init.lua:249: in function 'init_player_armor'
ERROR[Main]: 	/data/world//worldmods/3d_armor/3d_armor/init.lua:308: in function 'func'
ERROR[Main]: 	/usr/local/share/minetest/builtin/common/after.lua:20: in function 'globalstep'
ERROR[Main]: 	...//worldmods/monitoring/monitoring/builtin/globalstep.lua:29: in function <...//worldmods/monitoring/monitoring/builtin/globalstep.lua:20>
ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:429: in function </usr/local/share/minetest/builtin/game/register.lua:413>
</pre>

I don't think this is related to any change actually, just a plain mod bug.
* 3d_armor stores objectrefs across globalsteps
![i](https://user-images.githubusercontent.com/1042418/74333813-f5a7bd00-4d98-11ea-8308-66358ed125c5.png)
* then it retrieves the name (the objectref is still functional for some reason) and calls another api..
![i](https://user-images.githubusercontent.com/1042418/74334203-be85db80-4d99-11ea-8f95-f09af4e53d47.png)
* ..but get_player_by_name can no longer find the player
![i](https://user-images.githubusercontent.com/1042418/74334598-8337dc80-4d9a-11ea-9af9-4b9f01ed1830.png)

**Comment by sfan5** [comment]
The crashes in mobs_redo are more interesting, it seems `on_step` gets called despite the object being "gone" (as the engine calls it).

A simple workaround would be to do this, however this sounds like an engine bug and should be fixes there.
![i](https://user-images.githubusercontent.com/1042418/74335936-9304f000-4d9d-11ea-8fbb-c93ee977e3d7.png)

**Comment by thomasrudin** [comment]
Thanks for investigating :+1:, i see if i can reproduce/fix that on the test-server the next few days...

> Edit: Just checked the engine code, on_step is only called if the object still exists (since 5.0) so the actual issue here lies elsewhere.

Those bugs would justify a revert, right? The current state on the `master` branch won't work with most of the worlds out there... :disappointed:

**Comment by sfan5** [comment]
> Those bugs would justify a revert, right?

Hard to answer. The patch _should_ not have broken any well behaving mods.
Without having the mobs_redo crashes narrowed down, you don't know who's in the wrong, how many mods this would affect and whether the engine should be less strict.

**Comment by sfan5** [comment]
Ok, figured out the mobs_redo issue:
Inside `on_step` > `do_env_damage` > `check_for_death` the code might delete the entity.
But the the rest of on_step (including the `do_states` seen in the backtrace) continues running and crashes when the (deleted) entity does not return useful values.

In short: Not an engine bug.

**Comment by lhofhansl** [comment]
Commented on minetest/minetest#9390. I noticed this too (with mobs_redo)

**Comment by thomasrudin** [comment]
patched with https://github.com/pandorabox-io/minetest_docker/commit/30b23262a9f56a28093ab3d88f3739cccc3c81d2, closing the issue...
