### ISSUE TITLE
List of biofuel input items

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#450]
Suggestions for materials to be added as biofuel-able
- glue
- sugar
- agave (if not already)
- rye, oat and barly seeds
- rice?
- since papyrus works, why not minegeld? or only stacks of money?
- corn, what about other produce?

here's a list of items that did not work:
beetroot, grapes, tomatoes, corn, carrots,
green beans, onion, garlic clove, potato,
peper, garlic, honey, mulch,
cucumber, raspberries, pea pod, blueberries plantable (the ones from bushes work),
rhubarb, chilis, pepercorn, rye seeds, oat seeds,
rice grains, cocoa and coffee beans,
raw latex, rubber
pumpkin and melon slices don't but full fruit is accepted.

related #6

**Comment by BuckarooBanzay** [comment]
I think even groups can be added, maybe a simple `group:plant` entry can slash most of those items..

**Comment by SwissalpS** [comment]
raw latex, rubber

**Comment by OgelGames** [comment]
I had a look into this and found that just about everything listed above is already convertible in the upstream version, but that version is missing the output fixes, so I re-fixed it and opened a PR: https://github.com/Lokrates/Biofuel/pull/6

Seeing as Lokrates hasn't been active since June last year, I don't expect the PR to be merged anytime soon, so I copied the updated and fixed version to a branch on the pandorabox fork: https://github.com/pandorabox-io/Biofuel/tree/updated

The only other difference is that the output is now vials of biofuel (4 makes 1 bottle), and the speed has been slowed a bit, but that can be easily changed with the new settings if needed.

**Comment by SwissalpS** [comment]
> the output is now vials of biofuel (4 makes 1 bottle),

So the refineries need to be rebuilt to add another autocrafter? That's a risky change. :/

**Comment by OgelGames** [comment]
> That's a risky change. :/

I was thinking that, but it can be changed to be exactly as it was by adding these settings:
```
biomass_input = 4
fuel_production_time = 8
refinery_output = true
```

**Comment by SwissalpS** [comment]
Yes refinery_output = true is the important setting in my view.
Production time was 4, it wouldn't break a system completely if speed was halved since cans are not used in any subsequent recipe.

Make sure the minetest.conf settings are updated first, then merge the new version otherwise we have the 'problem' of vials existing in game ;) (minetest.conf needs admin action)

**Comment by BuckarooBanzay** [comment]
> I had a look into this and found that just about everything listed above is already convertible in the upstream version, but that version is missing the output fixes, so I re-fixed it and opened a PR: Lokrates/Biofuel#6

Looks good :+1: 

> So the refineries need to be rebuilt to add another autocrafter? That's a risky change. :/

Should we really be backward compatible here? The biofuel was op to begin with anyway...

> Seeing as Lokrates hasn't been active since June last year, I don't expect the PR to be merged anytime soon

Yeah, he takes his time usually but comes around eventually...

> Make sure the minetest.conf settings are updated first

The final `minetest.conf` is a result of this file:
https://github.com/pandorabox-io/pandorabox.io/blob/master/minetest.conf

And one containing the keys (not checked into git)

The final config is generated with this:
https://github.com/pandorabox-io/pandorabox.io/blob/master/generate-config.sh

But this can only be done on the shell/ssh and is not automated yet.
I can add the settings and execute script if this is ready (looks like it though...)

**Comment by OgelGames** [comment]
> Should we really be backward compatible here? The biofuel was op to begin with anyway...

Well personally I'd be fine with the new system, the only sticking point really is the factories that have been built on the original system.

**Comment by BuckarooBanzay** [comment]
I added the settings for compatibility, lets start with that i guess...
