### ISSUE TITLE
GeoIP parser bug

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#452]
I recently noticed that `/geoip` command ignores nicknames starting with digits. I thought about adding it to `beerchat` repo, but I haven't found GeoIP command there.

**Comment by BuckarooBanzay** [comment]
>  but I haven't found GeoIP command there.

The `/geoip` command comes from the mod with the same name:
https://github.com/pandorabox-io/geoip

> I recently noticed that /geoip command ignores nicknames starting with digits

Hmm, thats strange, there are no regex-shenanigans involved there (https://github.com/pandorabox-io/geoip/blob/master/init.lua#L42) :confused:

**Comment by 6r1d** [comment]
**UPD**: I haven't thought of it before, but the bug is /geoip-related, not parser-related.
I can't use it on an account with nickname made of normal letters. No VPN, just ADSL.

**Comment by BuckarooBanzay** [comment]
@6r1d i totally forgot: i removed that service/container because i had storage issues on that partition (system). The image used half a gig without any geoip-data....

The `/geoip` command should have reported an error, but ok... :stuck_out_tongue: 

I may have to look for another solution anyway, the maintainer put the repo in maintenance-mode:
https://github.com/klauspost/geoip-service/

**Comment by 6r1d** [comment]
Well, I was mainly concerned because there's a lot of new accounts. I think it's one account per 5 minutes or so, digits or gibberish characters only. I think someone picked Pandora to debug MT client: initially it was just registration, now there's also gibberish messages and well, nothing else.

I kicked them for some time, but since account is *generated* each time and there's no griefing, server should clean them up, right?

**Comment by BuckarooBanzay** [comment]
> Well, I was mainly concerned because there's a lot of new accounts

I noticed that a fewk weeks back and checked a few accounts manually, picked 3 of them, all had different ip's and no VPN-association... (i just did the same with 2 accounts: same result)

> I kicked them for some time, but since account is generated each time and there's no griefing, server should clean them up, right?

Nope, thats done manually:
https://github.com/pandorabox-io/pandorabox.io/blob/master/scripts/purge_xp_null_metadata.sh

I may automate that if the account creation gets excessive...

**Comment by BuckarooBanzay** [comment]
The geoip-service is up and running, the `/geoip` command should work again.

**Side-note about banning**: you can still ban with `/xban` or `/xtempban`. The incoming ipv6to4 address is not bannable anymore, so mass-bans should not be a problem... (also the builtin `/ban` command is disabled)

Follow-up issue about all the strange new joins: #460 

(feel free to reopen if something still does not work...)
