### ISSUE TITLE
Improve communicating events that have high impact on game play

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#455]
Thinking about this one:
https://github.com/pandorabox-io/pandorabox.io/issues/454

After looking at chat history I see that at least some active and established players got a bit confiused about this event. And after thinking a bit about it it has happened several times in past too.

What I'm thinking of would be few simple commands for moderators:
* `/server-announce <bla bla bla>` Would send message to everyone online, possibly with ping. Requires ban priv.
* `/server-announce-rm <id>` Remove server announcement. Requires ban priv.
* `/announcements` List current server announcements with ID. No privileges required.

Possibly also add to login hook to send current announcements to players logging into server.
Data storage would not need to be persistent, just ram backed table for storing messages.

Idea is to be easily able to set very *basic **temporary** messages about special events* and maintenance stuff that affects gameplay enough to create frustration among players who do not know why something does not work or works completely different.

I propose adding functionality directly into chat, this would also work as another step for providing better API for beerchat so do not just add MVP by throwing another chat command into beerchat core.

**Comment by zbx-pandorabox** [comment]
Players attitude:
Sounds like good idea. This will be much more operative then any kind of 'news board' on spawn place which nobody read( news board can be ofc good for long term announcements like "new mod XYZ installed,mod XYZ modified,  radioactivity effects disabled, etc. but I understand that this feature is more demanding and benefits are uncertain ).
"Ping" is in my opinion very important(for example I'm mostly ignoring chat if I'm concentrated for creation of something), colored message can be nice.

**Comment by BuckarooBanzay** [comment]
current workaround:

* Custom `server_news` mod: https://github.com/pandorabox-io/server_news
* Only displays a formspec if the `news.txt` file exists (should only be used for updates or upcoming maintenance interruptions)

## Further improvements

* Let moderators write to the `news.txt` file with a simple formspec

PR: https://github.com/pandorabox-io/pandorabox-mods/pull/589

**Comment by S-S-X** [comment]
Waiting for functionality to be merged, mods updated and server configuration added to enable extension:
```
beerchat.enable_announce = true
```
