### ISSUE TITLE
Search by owner

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#457]
I think it would be quite useful if on the online map, we could have search results be filtered by the name of the owner of the object rather than the name of the object

**Comment by OgelGames** [comment]
Also would be nice to be able to search to sell items, i.e. search for the input rather than the output.

**Comment by BuckarooBanzay** [comment]
Closing this here, feel free to comment on https://github.com/minetest-mapserver/mapserver/issues/86
