### ISSUE TITLE
Should advtrains mod be removed?

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#463]
**Is Adv train useless or necessary mod ?** 
 People use adv train very rare. There a lot of abandoned avd railways and railway stations, platforms. 
Only owner can place train. Also it works with some lags and freeze  and use useful computing resources.
Will it be disabled ? 
As for me railway for boost carts rather better.

**Comment by BobFred7** [comment]
:+1: I just about never use it, it is said to be a significant source of lag, and adds a lot of items that adds confusion to the crafting guide ... but maybe there are some people who use it a lot and would disagree

**Comment by S-S-X** [comment]
> Is Adv train useless or necessary mod ?

I think it is very nice mod, how useful it is depends on how you define usefulness. I think it is useful if you want to build cool railway networks with proper trains and actual routing for train lines.

> People use adv train very rare. There a lot of abandoned avd railways and railway stations, platforms.

Currently seems to be 68 total trains and 24 of those are active.
There's also some new trainlines under construction and I've heard of many plans for more train lines and plans for connecting smaller railway networks.
Sometimes I've used trains to get around too.

> Only owner can place train.

Depends on how railway network is built. Probably only you can also place blocks into your base if you have decided so.
I dont think this is limitation of advtrains, most probably it is restriction placed by owner of that railway network.
If you feel that there should be some possibility to bypass protections placed by owner then maybe open another issue for this explaining why and under what conditions bypassing protections should be allowed.

> Also it works with some lags and freeze and use useful computing resources.

> it is said to be a significant source of lag

While it does use some CPU time it does not seem to be that significant source of lag or computing resources:
https://monitoring.minetest.land/d/A8ErBXmWk/advtrains?orgId=1

> and adds a lot of items that adds confusion to the crafting guide

Around 45 items that are only useful for actual trainlines, 21 of those are trains, wagons or train/wagon components.
Most of items that come up are building blocks used for platforms.

> Will it be disabled ?

Probably not.

> As for me railway for boost carts rather better.

For the record, I've used carts only in Rabbit1's elevator :smile:

**Comment by OgelGames** [comment]
I'm with @S-S-X on this one. While it isn't exactly a necessary mod, and the cost to use ratio isn't the best, it's definitely not useless, and shouldn't be removed.

**Comment by Emil9736** [comment]
I suggest a voting  and then compare value of agreed and disagreed.

**Comment by BuckarooBanzay** [comment]
>  People use adv train very rare. There a lot of abandoned avd railways and railway stations, platforms.

@Emil9736 Yes there are, but there are also (some) maintained stations and trainlines out there and a few well made tutorials...

> it is said to be a significant source of lag

@BobFred7 it does consume some cpu-time but it is more or less stable (around 100ms in a second) We have currently bigger lag-contributors (`pipeworks` and `mesecons` for example, depends on the contraptions built)

> For the record, I've used carts only in ElSmacko's elevator smile

@S-S-X I think i saw that once, nice trick... :smile: 

> I suggest vote and then compare value of agreed and disagreed

@Emil9736  I'm very sorry, i'm all for voting and stuff but this won't work in this case: some train-owners tend to take long breaks between playing and would not be able to join in....

Also: there is a `/advtrains_cleanup` command i'm using from time to time that cleans up non-automated trains (https://github.com/minetest-monitoring/monitoring/blob/master/monitoring_advtrains/cleanup.lua) this seems to help a bit

I'm very sorry but i have to close this in favor or keeping the `advtrains` mod, if that thing makes problems in the future we can talk about this again...
