### ISSUE TITLE
Protector repo moved

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#464]
https://github.com/mt-mods/protector/issues/5

Update protector submodule remote @ pandorabox-mods.

GitHub is able to redirect URLs but should still use new proper URL for remote.

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:

**Comment by BuckarooBanzay** [comment]
thanks a lot, i changed the url accordingly :+1:
