### ISSUE TITLE
fast growing seedlings

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#468]
From **GamePlayer**:
```
What if you add options for creating fast growing seedlings in crafting?
It would be made of 1 fertiliser and 1 any seedling.
The options for placing a fast growing seedling would be limited to 50k XP.
What do you think?
```

**Comment by BobFred7** [comment]
When the fast-grow seed develops into a plant and is broken, would it drop accelerated seeds or normal seeds?

**Comment by S-S-X** [comment]
Recipe should require more fertilizer than what would be worst case by chance when actually using fertilizer.
Trees for example: moretrees should require at least 5 fertilizer and sapling for recipe.
Small poplars would probably require 8 x 99 stacks of fertilizer for one sapling :smile:

**Comment by OgelGames** [comment]
To be honest I don't see the benefit of this, I'd rather see strength 4 fertilizer get added...

**Comment by OgelGames** [comment]
> I'd rather see strength 4 fertilizer get added...

I decided to test it, and it works as expected (grows trees 100% of the time), except strength 4 doesn't grow crops at all for some reason... 😕 

For the moment I've added it to a branch of `pandorabox_custom` here: https://github.com/pandorabox-io/pandorabox_custom/commit/6d2271b56cf43ba4bf6fa643316563814a6de57c

**Comment by BuckarooBanzay** [comment]
@OgelGames this looks good! Except for the redwood tree, but i guess i implemented that wrong somehow in the `redwood` mod...

**Comment by OgelGames** [comment]
> Except for the redwood tree, but i guess i implemented that wrong somehow in the `redwood` mod...

Nothing is wrong in the `redwood` mod, I think there is something that is not working in the `bonemeal` mod for strength 4, I just don't know what...

**Comment by BuckarooBanzay** [comment]
closing this, @OgelGames implemented that in https://github.com/pandorabox-io/pandorabox_custom/commit/6d2271b56cf43ba4bf6fa643316563814a6de57c works well so far...
