### ISSUE TITLE
Default password on login

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#472]
## Proposal

* Enable default password for new logins
* Show password on website/wiki/discord/forum
* Remove `server_cloak` mod

## Benefits

* Server is displayed in serverlist without exceptions
* Finding out the password needs a bit of work (new-joins should be more serious players)
* Fixes (hopefully): #460 

## Potential downsides

* Maybe no more new players

@OgelGames @S-S-X @SwissalpS @coil0 @int-ua @6r1d thoughts?

**EDIT**: also a "nag-dialog" is in order to warn if the password is unchanged

# PR's

* Config: https://github.com/pandorabox-io/pandorabox.io/pull/473
* Mods: https://github.com/pandorabox-io/pandorabox-mods/pull/541

**Comment by OgelGames** [comment]
I'm all in favor of this, there are way too many new players even with the server cloak, and making new players go to the websites to get the password will also have the benefit of them likely learning a bit about the server before they join.

**Comment by S-S-X** [comment]
Sounds good if done correctly. Retrieving password should still be easy enough:

Server description (announce) should give very simple instructions on how to find password.
Maybe this info should even be translated to few most common languages.

For example put simple message there:
> Get your password from https://pandorabox.io website.
> Obtenga su contraseña del sitio web https://pandorabox.io
> Получите ваш пароль с сайта https://pandorabox.io
> Holen Sie sich Ihr Passwort von der Website https://pandorabox.io

^^ that was straight from google translator.

Then at https://pandorabox.io there should be easy to find/see link to site where you can see password and simple instructions for changing your password immediately after first login.

**Comment by 6r1d** [comment]
Well, this looks like a great idea.
To be clear, will users who forgot the password be deleted after a given interval?

**Comment by S-S-X** [comment]
> To be clear, will users who forgot the password be deleted after a given interval?

This would probably follow same rules as before, if user wont interact then @BuckarooBanzay's script will remove user from db but if he does interact then user account will stay there.

Could also force password change after login with temporary password (grant interact after password is changed) but in the end this is not different from setting password at first login and the forgetting it.

**Comment by BuckarooBanzay** [comment]
default password is now required (next restart/crash)

I placed the password in the announce-string and the wiki/website:

<img src="https://i.imgur.com/H14XZSU.png"></img>

This should be prominent enough for new players...

> If it seems that there's bots logging in and someone decides to fetch password automatically then just start rotating default password and add some captcha for password site.

I don't think those are bots, they are most likely players from a ad-ridden unofficial mobile-app...
As for the captcha-method: i hope we don't need that, i hate those... :confounded:

**Comment by BobFred7** [comment]
> I don't think those are bots, they are most likely players from a ad-ridden unofficial mobile-app...

If there's any clear/programmable way to check for this situation, maybe send a message to the user when they join to inform them of something like "you are using an unofficial app to connect to the game, this is really Minetest, there is an official app for this that is free and has no ads"

**Comment by BuckarooBanzay** [comment]
> If there's any clear/programmable way to check for this situation, maybe send a message to the user when they join to inform them of something like "you are using an unofficial app to connect to the game, this is really Minetest, there is an official app for this that is free and has no ads"

That was possible in the <=0.4.17-times with some formspec hacks but they are pretty indistinguishable now from the server-perspective.

Just the media-download gave some clues away (the User-Agent header) but then you would have to correlate the ip's on the webserver with the ones ingame and write other glue-code just to warn that you are using an inofficial minetest-fork, it's not worth the additional time and complexity IMO...
