### ISSUE TITLE
There is no access to Webmail 

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#474]
Doesn`t work Webmail: Cannot GET /

**Comment by BuckarooBanzay** [comment]
> Doesn`t work Webmail: Cannot GET /

My bad: those apps (webmail, wiki, map, chat-proxy) get auto-updated with security-patches every few days or so. But it looks like this time the reverse-proxy (the one responsible for the SSL-certificate and http-routing) didn't let it through after the update...

Don't know the exact cause but i put it on the list for later (#475) it should work again by the way...

Thanks for reporting :+1: feel free to do it again if something is up, i don't get messaged when those things fail (yet)
