### ISSUE TITLE
remove radioactive gas

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#478]
With the change to the vacuum-mod space got pretty tough to survive on its own.
The `radioactive_gas` was a workaround of mine to make space more challenging but it looks like thats not needed anymore

Todo-list:
* [ ] remove mod
* [ ] register alias

**Comment by BobFred7** [comment]
Is space going to be made more challenging through an alternative system or will it just be easier again?

**Comment by BuckarooBanzay** [comment]
> Is space going to be made more challenging through an alternative system or will it just be easier again?

Same as before, @S-S-X made space-exploration a bit harder than it was a few months back (https://github.com/mt-mods/spacesuit/commit/dc59f608adb0df94d190fad0b2bd38719ff3fb9c)

I think this change alone should be challenging enough...
