### ISSUE TITLE
new ores

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#482]
Source:
* `xtraores` https://github.com/AntumMT/mp-xtraores

# Earth
?

# Moon
* blue marble
* unobtanium

# Asteroids
* black marble (scattered on the surface)

# Mars
* red marble
* platinum (desert-stone)
* osmium (desert-stone)

**Comment by OgelGames** [comment]
Not sure what to think, on one hand I like the idea of adding some new ores (especially if they can be used to craft better tools), but on the other hand I don't like the idea of there being so many ores that don't have any use other than for tools and armor...

Also, not really a fan of the textures... I mean, cobalt is supposed to be blue, not green... :confounded:

**Comment by BuckarooBanzay** [comment]
> Maybe a custom ore mod would be better than xtraores?

Yes, i'm not going to pull in that mod (the code is a mess and it has a few OP items) but i'm using some of the textures in a custom mod, maybe even in the `planet_mars` or `planet_moon` mod itself..

> Not sure what to think about this, on one hand I like the idea of adding some new ores (especially if they can be used to craft better tools and armor), but on the other hand I don't like the idea of there being so many ores that don't have any use other than for tools and armor...

Most of them will be decorative only at first, the marble variants are a nice addition imo.
Not sure about the use of platinum, osmium and unobtanium yet, maybe i'll start with the marble nodes first...

**Comment by OgelGames** [comment]
> maybe even in the `planet_mars` or `planet_moon` mod itself..

> maybe i'll start with the marble nodes first...

👍 I do like the marble...

**Comment by BobFred7** [comment]
> but on the other hand I don't like the idea of there being so many ores that don't have any use other than for tools and armor...

Agree, maybe add a use for something with beacons...

**Comment by BuckarooBanzay** [comment]
closing this, marbles were added, i'll think about usages for the rest (platinum,osmium) some other time
