### ISSUE TITLE
Mapserver crash

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#502]
Don't remember exact error but probably something with deserializing SQL response, could have been unexpected null value or something.
If needed I might be able to reproduce that but basically it was because mapserver apparently didnt check input for "garbage" data.

Basically push some control chars to lcd, mapserver gets that stuff and dies because it does not understand how to handle it.

**Comment by BuckarooBanzay** [comment]
> Don't remember exact error but probably something with deserializing SQL response, could have been unexpected null value or something.

Did this happen in the frontend? o_O

**Comment by S-S-X** [comment]
502 Bad Gateway so nginx probably wont get useful response from backend.

Could not get error out again that mentioned SQL, I'm pretty sure it was not message directly from SQL server but from some SQL library for web apps.
Pretty sure it came through from XHR to map/api/mapobjects.

**Comment by BuckarooBanzay** [comment]
closing this

Recent changes:
* mapserver got an update of the underlying mapping framework (`leaflet`)
* log file monitoring

if anything pops up again please open a ticket in the `mapserver` repository (possibly with stacktrace and/or time of the error)
