### ISSUE TITLE
Node breakers smelting everything even without lava tools

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#513]
Problem seems to be in last lavastuff commit and at line:
https://github.com/minetest-mods/lavastuff/commit/7b405a49a93dec4c2259e8210554d75e7289c839#diff-d7d74284e2e39f6c06d199c8e2bedbd0R71

Pipeworks fake player is not userdata but table: https://gitlab.com/OgelGames/pipeworks/-/blob/master/common.lua#L177

IMO problem is in lavastuff mod and should be fixed there, lavastuff should not assume that digger is always userdata type.

**Comment by S-S-X** [comment]
Issue should be fixed https://github.com/minetest-mods/lavastuff/commit/ff314c727f6378b4c2774b64394a3e065da2950e

Test after pulled to mods repo and close when fix verified.

**Comment by OgelGames** [comment]
Nice find, I looked at lavastuff, but I didn't notice that :+1: 

Still confused why it cooked saplings twice though...

**Comment by BuckarooBanzay** [comment]
Nice work @S-S-X :tada:
