### ISSUE TITLE
Digiline_routing components can be cloned very easily

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#515]
New digiline_routing components can be cloned.
Took only few minutes to discover this and machine at test server that clones stuff to chest.
-1525,-6315,125

**Comment by S-S-X** [comment]
and other small issues like previously mentioned ability to bypass mesecon limits

**Comment by BuckarooBanzay** [comment]
> New digiline_routing components can be cloned.

How so? (i can't log into the server right now...)

**Comment by S-S-X** [comment]
protection + dig_node without digger + feedback loop = 300 items

**Comment by S-S-X** [comment]
Cloning is fixed via @Lejo1's commit that uses remove_node.

**Comment by BuckarooBanzay** [comment]
I've switched to @Lejo1's fork for the time being (until/if NumberZero merges the changes)
