### ISSUE TITLE
protector area privs not cleared after area is removed

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#517]
I made a couple of areas and did /area_priv_set # banana on them to prevent me from damaging the areas. Later I removed the areas. Other players started complaining about not being able to build in their newly created areas.
Checking with /area_priv_get showed banana.

To fix: need some callback/hook to update [priv_protector]'s cache-table when areas are removed.

Edit: [areas] [seems to have a hook for this.](https://github.com/minetest-mods/areas/blob/448fe3ebf18af48f8ef69738c2801c724d08bf10/api.lua#L12)

**Comment by OgelGames** [comment]
FYI, I actually added privlege and XP protection support to areas here: https://github.com/OgelGames/areas, the code has been sitting there for a while, and I'm not really sure what to do with it. 

Changing to that would also fix this bug, and improve some things too, but I don't know about how compatibility/conversion would work with all the priv and XP areas already created...

**Comment by SwissalpS** [comment]
sounds like something to test on test-server :)
@BuckarooBanzay

**Comment by S-S-X** [comment]
That might also need some extensive testing for protection check order if that could change in any way.

However I think currently areas like to be more permissive than restrictive meaning that if you have overlapping rules for both closed and open area protections then more permissive wins, but that's just observation based on very simple tests. Not sure if it is just early return and protection type also affects how stacked rules will be handled.

Would be nice to have all that in areas but also if areas already have usable API for this stuff and intends to provide just very basic protection with API for extension then maybe priv_protector should be fixed and if there's some significant improvements in @OgelGames fork then transfer those to priv_protector and/or areas depending on where those improvements belong.

**Comment by BuckarooBanzay** [comment]
> To fix: need some callback/hook to update [priv_protector]'s cache-table when areas are removed.

Yeah, exactly. I did this in my `area_effects`mod:
https://github.com/damocles-minetest/area_effects/blob/9ec86aa2543aa97bac25282a5dae743fec587550/accessors.lua#L15-L18

I applied the same thing to the `priv_protector` but the `xp` area needs it too i guess...

**Comment by BuckarooBanzay** [comment]
> Changing to that would also fix this bug, and improve some things too, but I don't know about how compatibility/conversion would work with all the priv and XP areas already created...

What improvements did you do over there?

**Comment by OgelGames** [comment]
> What improvements did you do over there?

Not much, just these 3 things I think:
- "Areas:" doesn't show on the HUD if there are no areas
- Priv-protected areas can have multiple privileges assigned
- XP-protected areas can have both a min and/or max XP

> if areas already have usable API for this stuff and intends to provide just very basic protection with API for extension then maybe priv_protector should be fixed and if there's some significant improvements in @OgelGames fork then transfer those to priv_protector and/or areas depending on where those improvements belong.

That is a good point, and transferring the improvements would probably be the easiest solution, particularly for compatibility...

**Comment by BuckarooBanzay** [comment]
> Not much, just these 3 things I think:
    "Areas:" doesn't show on the HUD if there are no areas
    Priv-protected areas can have multiple privileges assigned
    XP-protected areas can have both a min and/or max XP

I _do_ like those changes but i'm conflicted between including them in a custom fork and
trying to implement/upstream them in the `minetest-mods` one.

Also: it looks like the upstream mod is still under development (slow but still...):
https://github.com/minetest-mods/areas/commits/master

> That is a good point, and transferring the improvements would probably be the easiest solution, particularly for compatibility...

:+1: for upstreaming them, i'd like to help somehow but i guess it will end in a waiting game or ping orgy...
