### ISSUE TITLE
smartshop inaccuracy on map server (and/or "search shop")

### ISSUE THREAD

**Issue by Omikhleia** [pandorabox-io/pandorabox.io#523]
I haven't seen this issue being reported, but i noticed two issues regarding how smartshops on the map server are shown (and also in the listing from the `/search shop` chat command).

- On the mapserver view, only 1 sale slot is listed, out of the 4 these shops:

  ![image](https://user-images.githubusercontent.com/18075640/86284225-c1675880-bbe2-11ea-8a47-618d02762977.png)

  _This shop actually has 4 slots of different dye colors, not 1_

- Items are sometimes reported as out of stock (and are also reported as red with the `/search shop` command) and the stock is actually dubious:

  ![image](https://user-images.githubusercontent.com/18075640/86283994-5289ff80-bbe2-11ea-84b1-c648c8aabfba.png)

  _This shop actually has several available bunnies_

  Hint: Tamed mobs aren't stackable (1 item in a shop inventory slot). ~~The stock value might be wrong even for other stackable items; that 138 in the above example is dubious (when i checked the shop, i'm pretty sure it had _several_ stacks of 99 items in shop inventory slots)~~ EDIT: But here they are sold by 5, so the value might be correct.

I'm not sure (yet) where to start investigating for this weird behavior!

**Comment by S-S-X** [comment]
Here's duplicate #369 and main ticket in mapserver repo https://github.com/minetest-mapserver/mapserver/issues/71

**Comment by S-S-X** [comment]
@Omikhleia I dropped comment to mapserver ticket what I believe where issue lies, take a look there. Closing this one.

**Comment by BuckarooBanzay** [comment]
@Omikhleia yeah, @S-S-X is right, this is still an open issue.
The ingame search should show your results though, as the data is available in the mapserver's database:

## Request
```bash
curl 'https://pandorabox.io/map/api/mapobjects/' -H 'Content-Type: application/json; charset=utf-8' --data-raw '{"pos1":{"x":521,"y":-1,"z":-217},"pos2":{"x":561,"y":10,"z":-212},"type":"shop"}' | jq
```

## Response (truncated)
```json
  {
    "mapblock": {
      "x": 544,
      "y": 1,
      "z": -215
    },
    "x": 8706,
    "y": 18,
    "z": -3425,
    "type": "shop",
    "mtime": 1593570929,
    "attributes": {
      "in_count": "1",
      "in_item": "currency:minegeld_10",
      "out_count": "1",
      "out_item": "mobs_animal:bee",
      "owner": "Gorlock",
      "stock": "104",
      "type": "smartshop"
    }
  },
  {
    "mapblock": {
      "x": 544,
      "y": 1,
      "z": -215
    },
    "x": 8706,
    "y": 18,
    "z": -3425,
    "type": "shop",
    "mtime": 1593570929,
    "attributes": {
      "in_count": "10",
      "in_item": "currency:minegeld_10",
      "out_count": "1",
      "out_item": "mobs_animal:bunny_set",
      "owner": "Gorlock",
      "stock": "0",
      "type": "smartshop"
    }
  },

```

Its just not (yet) properly displayed on the map: you can only click on the topmost POI... :see_no_evil:
