### ISSUE TITLE
Heavy lag spikes induced by malicious client traffic

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#530]
## 2020-08-14 0800

```
# Server: version=5.3.0-docker, uptime=119065, max_lag=31.7173, clients={shanish, Mythos, deathwatch, shangul, SNEO, MrCube-bit, dead_link}
```

<img src="https://i.imgur.com/5xz9BVA.png"></img>

```
05:26 <pandorabot> Player shanish joined the game
05:27 <pandorabot> carlos left the game
05:30 <pandorabot> Player carlos joined the game
05:32 <pandorabot> carlos left the game
05:32 <pandorabot> shanish left the game
05:33 <pandorabot> Player Tagada joined the game
05:35 <pandorabot> Player shanish joined the game
05:42 <pandorabot> <shanish> my world is not loading
05:42 <pandorabot> <shangul> hmm?
05:43 <pandorabot> <shangul> slow internet connection, shanish?
05:43 <pandorabot> <shanish> just loaded after a few minutes, possibly
05:44 <pandorabot> shangul left the game
05:46 <pandorabot> MilesDyson left the game (timed out)
05:46 <pandorabot> <Bonat> heavy lag shots here now - stacks return to source
05:47 <jessicara> yeah just have to be patient when that happens, move a stack and wait on it
05:47 <pandorabot> Player shangul joined the game
05:48 <pandorabot> shangul left the game
05:51 <pandorabot> shanish left the game
05:55 <pandorabot> Player shangul joined the game
06:31 <pandorabot> Tagada left the game
06:42 <pandorabot> Player deathwatch joined the game
07:02 <pandorabot> Bonat left the game
07:29 <pandorabot> Player Mythos joined the game
07:29 <pandorabot> Player shanish joined the game
07:33 <pandorabot> shangul left the game
07:35 <pandorabot> Player shangul joined the game
07:35 <pandorabot> shangul left the game
07:43 <pandorabot> Player shangul joined the game
07:44 <pandorabot> shangul left the game
```

Possibly related:
```
2020-08-13 15:38:14: ERROR[ConnectionSend]: con(4/1) dropped reliable packet for non existent peer_id: 758
2020-08-13 16:50:02: ERROR[ConnectionSend]: con(4/1) dropped reliable packet for non existent peer_id: 811

2020-08-14 05:45:49: WARNING[Server]: [mapserver-bridge] post took 30623305 us
2020-08-14 05:45:51: WARNING[Server]: [mapserver-bridge] processing took 16614 us
2020-08-14 05:46:02: WARNING[Server]: [mapserver-bridge] post took 10521406 us
```

**Comment by S-S-X** [comment]
If it is some simple DOS by connection/packet/too much data from single client then easiest workaround would probably be limiting incoming traffic per client on master server (one that is on edge receiving connections). Simply tc or even just iptables.

Not inside containers as if I've understood correctly you have not enabled IPv6 routing there yet and those will get NAT'd and also it is probably easier and more correct to do traffic control / basic firewalls / waf / whatever before docker routing. I don't however really know anything about underlying architecture so of course it depends on actual network config.

So just a suggestion for *possibly* mitigating some of issues that might look like targeted attacks.

**Comment by BuckarooBanzay** [comment]
i'm standing ready with `tcpdump` :smile:

**Comment by BuckarooBanzay** [comment]
This may be caused partially by the recent switch to postgresql of the `auth` database (#528).

Every call to `minetest.get_player_privs()` or `minetest.check_player_privs()` executed a call to the auth-database to check privileges. At the time the auth data was still in the sqlite-db it was not noticeable because the round-trip-time was almost non-existent, in the postgresql case there is a TCP-Connection involved.
The db-roundtrip is now fixed by (yet another) caching layer: https://github.com/BuckarooBanzay/set_player_privs_cache

There is still some additional lag that wasn't there before, i'm hoping i get to the bottom of this with some addional profiler-data in a new engine-build: https://github.com/pandorabox-io/pandorabox.io/pull/537
