### ISSUE TITLE
Traders missing some common mob functionality

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#533]
reported by skylord:
> traders cannot be protected and they can't be fed.

Add those for traders.
Note about protection: rune protection does not currently work correctly, protected mobs can be killed by other players.

~https://github.com/mnh48-minetest/mobs_npc/blob/master/trader.lua~
https://notabug.org/TenPlus1/mobs_npc/src/master/trader.lua

**Comment by SwissalpS** [comment]
they also can't be moved.

**Comment by BuckarooBanzay** [comment]
>  Note about protection: rune protection does not currently work correctly, protected mobs can be killed by other players.

This is bad :confused:

**Comment by SwissalpS** [comment]
The traders don't offer good deals. If there was a small chance of getting an "igor egg for a gold lump" offer, it would make them more interesting to interact with. Igors come in many skins for the collectors.

It could also be fun to make the traders only attainable through such a jackpot-deal, they too come in many skins.

**Comment by OgelGames** [comment]
@S-S-X that's not the repo we use currently, it's this one: https://notabug.org/TenPlus1/mobs_npc/src/master/trader.lua 😉 

> The traders don't offer good deals. If there was a small chance of getting an "igor egg for a gold lump" offer, it would make them more interesting to interact with. Igors come in many skins for the collectors.

I would still like all NPCs to spawn like regular mobs, but having traders sell mob eggs (or tamed mobs?) would be great. considering how hard it is to get mobs.

> It could also be fun to make the traders only attainable through such a jackpot-deal, they too come in many skins.

So how would get the trader you buy the trader from? 😄 

I think I will have a go at fixing and improving traders a bit, I think the simplest way to add different/better trades would be functions to add or remove trades, which could then be changed in `pandorabox_custom`.

**Comment by OgelGames** [comment]
Done: https://notabug.org/OgelGames/mobs_npc

Decided to not add extra functions for changing trades, as they can be changed in the `mobs.human.items` list, but I did add spawning for traders and igors.

I think I might wait to open a PR until after they have been used a bit, but I don't think anything else needs to be changed (aside from changing trades in `pandorabox_custom`).

**Comment by BuckarooBanzay** [comment]
> Done: https://notabug.org/OgelGames/mobs_npc
> 
> Decided to not add extra functions for changing trades, as they can be changed in the `mobs.human.items` list, but I did add spawning for traders and igors.
> 
> I think I might wait to open a PR until after they have been used a bit, but I don't think anything else needs to be changed (aside from changing trades in `pandorabox_custom`).

i took the liberty to switch to your fixed repo here: https://github.com/pandorabox-io/pandorabox-mods/pull/989
The change to the custom repo can be done another time too, right?

**Comment by OgelGames** [comment]
> i took the liberty to switch to your fixed repo
> The change to the custom repo can be done another time too, right?

Great 👍 Yes, the other changes can be made whenever we decided what trades we want. (perhaps a separate issue could be opened for that?)

**Comment by SwissalpS** [comment]
> So how would get the trader you buy the trader from? smile

An event or mission to distribute the first 3 :)

**Comment by SwissalpS** [comment]
@OgelGames  Traders shouldn't be breedable, imo. At least not with configured baby
https://notabug.org/SwissalpS/mobs_npc/commit/50b748ef02601dc65d9e092e6d3cac887b096c90

I forked, updated readme, but did not figure how to PR from web interface
https://notabug.org/SwissalpS/mobs_npc/commit/5530aa0e29b5bd1eb1700b755ade63ff5fcd4ec9

**Comment by OgelGames** [comment]
@SwissalpS I made the traders not breedable and update the readme, hope you don't mind I didn't merge your changes, but it was easier to just make the changes myself...

Also fyi, you can open a PR by clicking the green compare button next to the branch selection 😉

**Comment by SwissalpS** [comment]
thanks, I'll give that a try.
Also, sure, I don't mind how you merged the proposed changes :)

**Comment by SwissalpS** [comment]
nice and tidy readme, congrats :)

**Comment by SwissalpS** [comment]
may I sugest using nametag:
https://notabug.org/SwissalpS/mobs_npc/commit/48595a4fc11bdfe60b9aac47ce15b01c409385ec

or 'Trader ...', 'Igor ...', 'NPC ...'
https://notabug.org/SwissalpS/mobs_npc/commit/b6652377716a463b80f0335f4d0d5e8385c8f2f2

in chat messages. I like the nametag idea best, but that would involve a little work.
Players would get a bit more feedback as to which of their x-mobs they just clicked.

**Comment by OgelGames** [comment]
> may I sugest using nametag: ... in chat messages.

Done: https://notabug.org/OgelGames/mobs_npc/commit/c69c02086c5fcadca7ef70a9f0f206c2a161e8ed

Translations will need to be updated, but in the meantime it works fine without them.

**Comment by OgelGames** [comment]
Closing, issue is fixed, changes to trades can be discussed in a new issue: https://github.com/pandorabox-io/pandorabox.io/issues/536

**Comment by SwissalpS** [comment]
very nice solution, thanks :D

**Comment by BuckarooBanzay** [comment]
thank you @OgelGames :+1:
