### ISSUE TITLE
Mapserver and new block

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#546]
Since Huhhila doesn't have a Github accound, I'm copying something he found. He says that mapserver doesn't display sulfur blocks or ultra framed obsidian glass. Though displaying the second is weird: glass is transparent. Maybe it can be displayed as something bluish? How can I update mapserver? :-)

**Comment by BuckarooBanzay** [comment]
Transparency isn't implemented yet, i haven't found a suitable algorithm that is fast enough yet:
https://github.com/minetest-mapserver/mapserver/issues/42

The colors are defined in text-files here:
https://github.com/minetest-mapserver/mapserver/tree/master/static/colors

I think `custom.txt` would be a good fit, if not: new files can be added here: https://github.com/minetest-mapserver/mapserver/blob/d3d52341fcb22de94f3bcf7e046c99cf0e3ac47d/app/setup.go#L87-L95

### About the update process

The mapserver is one of those services that get updated automatically:
* every commit produces a docker image with the help of github actions
  * Action: https://github.com/minetest-mapserver/mapserver/blob/master/.github/workflows/docker.yml
  * Image: https://hub.docker.com/r/minetestmapserver/mapserver/tags?page=1&ordering=last_updated)
* The container gets updated on the server if a newer one is found with the help of `watchtower`: https://github.com/containrrr/watchtower

https://github.com/pandorabox-io/pandorabox.io/blob/5d1d98cfa61dfc85be2192c719224421c37842c6/docker-compose.yml#L63-L67

**Comment by MilesBDyson** [comment]
also an issue with the mapserver does not see a node with overlays correctly such as the 'default:blueberry_bush_leaves_with_berries' shows up as 'default:blueberry_bush_leaves'.
not sure but i think it has something to do with the berry's being an overlay on the 'default:blueberry_bush_leaves' node.

i had a similar issue with the colored clay mod that did not use images for the nodes so the colors did not show up on the map, then i think that mod was eventually removed at some point any way..

**Comment by MilesBDyson** [comment]
also i can make the glass any color you want but it has to be in simple RGB format and does not support translucent or clear

**Comment by MilesBDyson** [comment]
ok i added technic:sulfur_block to the colors list

**Comment by BuckarooBanzay** [comment]
i think this is fixed, if not reopen please
