### ISSUE TITLE
Odd area protection bug

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#548]
Some player shared an area protection with me (giving me an area protection over an area they also protected) a while ago.

They did the same with several other players.

Now that I tried to come back to that place, I found that I couldn't build or break there or do anything else there that would require an area there (like coming through a protected travelnet station).

Another player who had an area there was still able to manipulate things there just fine.

When they tried to make a new area there for me, they got a mysterious error message ("cannot create area", something rather unhelpful).

The areas list in the lower left said my area was still there.

`/select_area` appears to give a success message for areas that exist and failure for areas that do not exist, giving a success message also for areas that exist but I don't own.

`/select_area` with the ID of the area I was said to own as reported in the lower left gave a success message.

All this seems rather messed up and there is probably a bug or corruption.

**Comment by S-S-X** [comment]
When message "cannot create area" came was there other areas owned by different players? Any overlapping areas?

* Individual areas for different players: message is kinda correct but not helpful.
  This also means that areas were messed up by not using recursive removal or proper cleanup before removing parent area.
* Only sub areas tied to parent area and player attempting to create area was owner of parent area: it clearly is a bug.
* No areas owned by anyone else than player who was trying to create area: it clearly is a bug.

Could be good to find out what cases could cause such error, maybe doing that also reveals bit more information about what might have been cause for such behavior.

**Comment by BuckarooBanzay** [comment]
@BobFred7 can you disclose the area-id's? i'll check if there is something off..

**Comment by BobFred7** [comment]
> When message "cannot create area" came was there other areas owned by different players? Any overlapping areas?

There were other overlapping areas owned by several other players at the time.

I don't know whether they were subareas or fully separate areas.

> can you disclose the area-id's?

I think my nonfunctioning area was #3083 , I don't remember what any of the other possibly involved ones were

**Comment by BuckarooBanzay** [comment]
Is this your area:
```json
{
  "name": "StationX",
  "parent": 1978,
  "pos1": {
    "x": 7486,
    "y": 9986,
    "z": 20986
  },
  "pos2": {
    "x": 7514,
    "y": 10014,
    "z": 21014
  }
}
```
(i'm having trouble with those 1-indexed arrays in lua, that's why i'm asking)

If so: there is a `parent` area that may affect yours:

```json
{
  "name": "StationX",
  "owner": "xercyst",
  "pos1": {
    "x": 7486,
    "y": 9986,
    "z": 20986
  },
  "pos2": {
    "x": 7514,
    "y": 10014,
    "z": 21014
  }
}
```

I could give you temporary `areas` priv temporarily to solve that issue, do you have a ingame name?

**Comment by S-S-X** [comment]
Protection seems to works correctly preventing area creation with those areas (if areas are like that).
"cannot create area" message could be improved a lot so that it would tell bit more about situation, in this case it should say something along the lines "cannot create area because you are not area owner but only builder"

**Comment by S-S-X** [comment]
Probably done with this already and can be closed, reopen if needed....
