### ISSUE TITLE
drawers:controller can not access full drawers

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#551]
When drawer is full and user attempts to eject items using digiline, for some reason no item is ejected.
Workaround is to periodically check all drawers for 100% and reduce if so.

**Comment by BuckarooBanzay** [comment]
Does that have something to do with the latest fix (proper maxStack value) or is that a long known problem (i mostly extend the storage _before_ they get to 100% :laughing:)

**Comment by SwissalpS** [comment]
I was extending with more drawers :p even upgrades can't stop overflow :)
This was my first test with digiline control. Maybe chi knows if it has been this way since start.

**Comment by S-S-X** [comment]
I think it was like that already before this commit: https://github.com/minetest-mods/drawers/commit/6603f2727989f1a9bba6671c461353b36511ee7d

**Comment by S-S-X** [comment]
What this actually does and why it checks count != maxCount to return items?
https://github.com/minetest-mods/drawers/blob/f6bca2ade23479f95d51a37053ef0cdf38f23210/lua/api.lua#L260

**Comment by SwissalpS** [comment]
chi just confirmed that it has never worked.

**Comment by OgelGames** [comment]
> What this actually does and why it checks count != maxCount to return items?
> https://github.com/minetest-mods/drawers/blob/f6bca2ade23479f95d51a37053ef0cdf38f23210/lua/api.lua#L260
> 
> Seems like possible cause for me

I'd say so too, it literally says to only return items if it's not full. There should only be a check for the item name, nothing else, as the count is checked correctly here: https://github.com/minetest-mods/drawers/blob/f6bca2ade23479f95d51a37053ef0cdf38f23210/lua/visual.lua#L258

**Comment by OgelGames** [comment]
Leave this open until the PR closes it 😉

**Comment by SwissalpS** [comment]
seems the change was pulled.
