### ISSUE TITLE
digiline_routing filter can be rotated to occupy same node as luac/other node

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#553]
It's a dual node item and when rotated to occupy same node as luac, well, when digging filter it destroys luac.

Edit: I was able to destroy bedrock and protected nodes with this.

**Comment by BuckarooBanzay** [comment]
> Edit: I was able to destroy bedrock and protected nodes with this.

:facepalm:

**Comment by S-S-X** [comment]
What about protection? Probably also allows destroying protected nodes.

**Comment by SwissalpS** [comment]
> <Zlo> when you rotate digiline message filter you need to place one wire under block to connect when you just place it it connects ok

So seems also the connection parameters are not updated.
How about disabling rotation, period?

**Comment by BuckarooBanzay** [comment]
>  How about disabling rotation, period?

Sounds good, what about the sonic screwdriver? _hides_ :smile:

**Comment by SwissalpS** [comment]
> what about the sonic screwdriver?

good point, not that easy to stop that one, luckily :)

**Comment by S-S-X** [comment]
what large nodes hanle this well enough? there's some homedecor stuff to test and others too. maybe just allow creating weir stuff and fix routing components so that they check if placeholder is there (if there's any)

**Comment by SwissalpS** [comment]
[seems to do the trick](https://github.com/numberZero/digiline_routing/pull/12)
