### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#560]
Recently, Chi found a bug with missing textures, related to `scifi_nodes` mod:

- `scifi_nodes_door1a_inv.png`
- `scifi_nodes_door2a_inv.png`
- `scifi_nodes_door3a_inv.png`
- `scifi_nodes_door4a_inv.png`

I can confirm the bug on PandoraBox; I teleported to a place near `0, 0, 0`, under the voting booth by `6789alepfwxz` and UFO ship by SingingPotato. There were red messages in chat about the missing textures.
(Seems like I mistakingly deleted the screenshot with the exact coordinates.)

I can't reproduce the bug locally with a Doom door and https://github.com/D00Med/scifi_nodes/commit/b54333d56b014339a0bfed9ba3b2ed45d0a4dc11, though.

**Comment by OgelGames** [comment]
I believe that is something in one of the drawers in the building in the sky above 0,0,0, I think I had that error too when I was there once...

**Comment by BuckarooBanzay** [comment]
Looks like those are still the "unaliased" items (before the doors were cleaned up in the `scifi_nodes` mod), when i removed and re-inserted them on the test-server the proper inventory image showed up :shrug:

**Comment by OgelGames** [comment]
> when i removed and re-inserted them on the test-server the proper inventory image showed up

Yeah, that makes sense, the old textures are on the drawer entities, so wouldn't even be able to move them (like to lga's museum).
