### ISSUE TITLE
Cookable tools and armor

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#562]
Got the idea from what @SwissalpS mentioned about wood tools in #main, thought it would be good if all (or at least most) unwanted tools and armor could be cooked to get materials back.

Wood(en tools) could turn into charcoal and metal(lic tools) could melt back into ingots, not sure about mese, diamond and lava, but I don't see those being unwanted much, so perhaps they wouldn't be cookable.

**Comment by SwissalpS** [comment]
keep in mind how much wood is in the tool. Wooden tools probably could give charcoal, but iron has only max two sticks, which does not seem to be enough for charcoal.

Similar thought is to use wooden tools in fuel refinery, also doors and other wooden objects.

**Comment by SwissalpS** [comment]
Also sugar was mentioned. If apples and dry sticks can be turned into biofuel, I don't see why sugar shouldn't.

**Comment by OgelGames** [comment]
> keep in mind how much wood is in the tool. Wooden tools probably could give charcoal, but iron has only max two sticks, which does not seem to be enough for charcoal.

What I meant was that wooden tools would give charcoal, and metal tools give ingots, with the sticks being lost as part of the cooking.

> Similar thought is to use wooden tools in fuel refinery, also doors and other wooden objects.

Not sure about biofuel, but would make sense for other wooden things to be cookable into charcoal...

**Comment by OgelGames** [comment]
I decided to only add tools and armor because if nodes are cookable, lava tools will cook them, which won't be fun...

**Comment by SwissalpS** [comment]
>  if nodes are cookable, lava tools will cook them,

those could be repurposed in fuel refinery :)
