### ISSUE TITLE
traders changed their names after reboot

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#567]
I had set all the names of my traders to ' ' so the nametags wouldn't show.
After last reboot, some of them have names again.

**Comment by OgelGames** [comment]
That is actually intentional: https://github.com/pandorabox-io/mobs_npc/blob/fa072c5c3a816f82dc2dc701a6fbf84939c6f3c7/trader.lua#L84

You can still set a blank name by using two spaces, but maybe it shouldn't be like that... :thinking:

**Comment by SwissalpS** [comment]
> That is actually intentional: https://github.com/pandorabox-io/mobs_npc/blob/fa072c5c3a816f82dc2dc701a6fbf84939c6f3c7/trader.lua#L84
> 
> You can still set a blank name by using two spaces, but maybe it shouldn't be like that... thinking

Thanks, I'm glad there is a way to force no tag.
