### ISSUE TITLE
Shared anvils

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#568]
Add option to make anvil shared: anyone can use shared anvil.

Anvils already contain metadata, metadata + crafting can be used to craft shared anvils without adding another node. Infotext can tell if stack of anvils is shared ones or not. Same goes with anvils placed in world.
```
<SwissalpS> I like the idea of an upgrade slot for chest in refineries, SCI and even anvil - though I doubt last one will be accepted upstream
<SX> got another idea, it would be also possible to use crafting to create shared anvil without adding another node for it. I think that would fit easily to customizations
<SX> actually not sure if it is possible, have to check...
<SX> Craft recipes only support item strings, but fortunately item strings can also contain metadata
<6r1d> yay
<SX> so it would be possible to make crafting recipe that adds metadata to convert anvil to shared, not sure if
you can reset that...
<SX> reset should be possible, could be cheap item combined with anvil to make shared anvil and just anvil to
reset back to fully owned
<SX> maybe even just anvil conversion back and forth if craft recipe items also support metadata checks
<SwissalpS> if that would work, that'd be great actually
<SX> "Metadata field filtering in the `recipe` field are not supported yet," so no...
<SX> needs some anvil + paper sheet or something to make shared and just anvil to get owned back or other
way round
<SX> would needs recipes + preserve_metadata extension/override + after_place_node extension/override
```

**Comment by BuckarooBanzay** [comment]
> Anvils already contain metadata, metadata + crafting can be used to craft shared anvils without adding another node.

Sounds interesting, how do you want to achieve that?
The owner-check is hardcoded here: https://github.com/minetest-mods/anvil/blob/7708aee694174ac7352048dc016e81de0f74a0d9/init.lua#L222

**Comment by S-S-X** [comment]
One dirty workaround would be to set owner meta value empty and override clicker name to be empty. I think userdata can be easily cloned in a way that clicker:get_player_name can be overridden by using info in userdata object metatable.
Not sure if that will work but it would probably be most straightforward and least intrusive way to override it.

If that wont work then of course it is possible to override metadata every time someone uses anvil, before calling that function set owner to current player and afterwards set meta:set_string("infotext", S("@1's anvil", owner)) to something else like "Shared anvil".

Best however would be to add changes to upstream repo, I think crafting recipes for shared anvils could be easy to accept as it wont change behavior at all without direct player actions.

If empty owner meta data field would be used (actually empty deletes meta key) then it also would not add any new metadata, just changes how check is done at line 222 and what will go to `infotext`. Stack would still need some metadata value that is not empty, for example use `itemstack:get_meta():set_int("shared", 1)`. If not available then it is not restored and current `after_place_node` functionality is used.

Currenlty if anvil for some reason does have empty `owner` metadata then it is broken, that would be just redefined to be feature :smile:

**Comment by S-S-X** [comment]
Added PR, shared anvil for testing is available here: https://github.com/S-S-X/anvil and in master branch.

**Comment by S-S-X** [comment]
crafting shared anvil: paper + anvil to crafting grid
resetting to owned: shared anvil to crafting grid
