### ISSUE TITLE
ccompass.teleport_nodes

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#576]
These are the nodes, that when punched with a compass, teleport player to comapss' target.

Currently only the default default:mese is active on pandorabox. My places are starting to look a bit strange with yellow blocks in places that have no other yellow.

Would it be making the compass too overpowered if we added some other colours?
Was thinking of coal block and mithril block.

Coal because that fits almost into all colour schemes and mithril because it is a) expensive b) magical and c) a colour that also matches well with many others.

Coal might be too cheap however :/

Ideas, thoughts?

**Comment by BuckarooBanzay** [comment]
Sounds good :+1: 

> Coal might be too cheap however :/

How about obsidian? Its not more expensive but maybe more "magical" :yum:

**Comment by OgelGames** [comment]
Maybe lava block? :wink:

**Comment by SwissalpS** [comment]
yes obsidian is great idea so is lava block.

so for colour schemes:
black: obsidian
blue/purple: mithril block
red: lava block
white: scifi_nodes:pad (needs recipe and probably override)
yellow: mese

That covers most schemes, is there a suitable for green?

**Comment by OgelGames** [comment]
One thing we need to remember is that every node that used as a teleport node can't be used to set compass, so I think we should pick nodes that are not frequently used for building. For that reason I think coal is better than obsidian, and also coal is a bit more expensive.

Also I think the `scifi_nodes:pad` should not be used, because it could be made functional one day, and it also has an unusual node shape. I think stainless steel would be better for white/grey.

For green maybe hemp block, the only thing I've seen that used for is fake banana leaves...

**Comment by SwissalpS** [comment]
> One thing we need to remember is that every node that used as a teleport node can't be used to set compass

good point, would be trivial to add functionality to sneak + click to set on such nodes.

If coal is ok, then hemp is too, no?

**Comment by OgelGames** [comment]
> would be trivial to add functionality to sneak + click to set on such nodes.

True, but I think that would break the nice simplicity of it...

> If coal is ok, then hemp is too, no?

Yeah, I guess it is okay :smile:

**Comment by SwissalpS** [comment]
> I think stainless steel would be better for white/grey.

It's not as common as obsidian in buildings, but still used. There would be silver which I have not seen used in any buildings.

**Comment by S-S-X** [comment]
> Would it be making the compass too overpowered if we added some other colours?

Add some cost for this kind teleportation methods, something cheap like mese shard for teleporting. Then compass will still show you direction if you don't have that magic power item with you.

**Comment by OgelGames** [comment]
> Add some cost for this kind teleportation methods,

That's overcomplicating it again...

**Comment by SwissalpS** [comment]
[I've prepared a commit](https://github.com/pandorabox-io/pandorabox.io/pull/577)
