### ISSUE TITLE
custom server texture pack

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#585]
@El-Naso the repository at https://github.com/minetest-mirrors/farming is just there for mirroring purposes

## overview

Usually changes are proposed on the upstream repository, in this case that would be `tenplus1`'s https://notabug.org/TenPlus1/farming.git
But he does not have a good track record if it comes to changes from other people (he also merges stuff under his name but thats another issue :shrug:)

:arrow_right:  So i thought instead of going upstream with something that would get rejected anyway we can create a custom texturepack.

I already did the groundwork for it:
* Texture pack repository: https://github.com/pandorabox-io/pandorabox-textures
* Path override into the minetest_game's `texture` directory: https://github.com/pandorabox-io/pandorabox.io/pull/584

## how this works

I found this section in the `lua_api.txt` (https://github.com/minetest/minetest/blob/3176daee79a8e91bd16fc275704f49fe1648db32/doc/lua_api.txt#L92-L94)

```
* If the game contains a folder called `textures` the server will load it as a
  texturepack, overriding mod textures.
  Any server texturepack will override mod textures and the game texturepack.
```

The PR #584 will create a directory with the newly created repository and every texture in there overrides any other defined in a mod

(let me know if there are better alternatives, i haven't found much info on how to override/set server textures)

**Comment by El-Naso** [comment]
> the repository at https://github.com/minetest-mirrors/farming is just there for mirroring purposes
Dang it xD

So the other option is to set our own texture override. 
Wait wait, I shouldn't fork this if I'm listed as a contributor, right? I just commit to master?

**Comment by OgelGames** [comment]
> (let me know if there are better alternatives, i haven't found much info on how to override/set server textures)

AFAIK, it's the same as using a texture pack as a client.

> All versions of Minetest support custom textures with a folder under the main Minetest Folder called textures.

Which in this case I think would be `./data/pandorabox-textures:/usr/local/share/minetest/textures/pandorabox-textures`

https://github.com/minetest/minetest/blob/master/doc/texture_packs.txt
https://wiki.minetest.net/Help:Installing_Texture_Packs
https://wiki.minetest.net/Texture_Packs

> Wait wait, I shouldn't fork this if I'm listed as a contributor, right? I just commit to master?

Yes, small changes can be committed directly to master, but larger changes (like new textures) should be committed to a separate branch and have a PR made so we all can discuss the changes.

**Comment by S-S-X** [comment]
> Yes, small changes can be committed directly to master, but larger changes (like new textures) should be committed to a separate branch and have a PR made so we all can discuss the changes.

There's opinions :smile:
My general opinion is that everything should go through pull requests and stable branch should be protected and disallow pushing anything directly no matter how small changes are.

If change does not affect core thing of repo or is simple fix for simple fault that have to be fixed then it should be fine to merge that PR right away but still PR provides many important things:
* Place for discussion after changes, committer should not be one who decides if it is important or not to provide place for discussion or not.
* Easier paper trail and place for better description, very good for tracking what was changed without having to rely on merge strategies.
* Notifications, commits do not normally provide any notfications.

**Comment by El-Naso** [comment]
> My general opinion is that everything should go through pull requests and stable branch should be protected and disallow pushing anything directly no matter how small changes are.

So I should: 

1. fork
2. commit changes to a branch of my fork
3. PR to merge whole thing so the branch with my changes can be merged to main later.

**Comment by S-S-X** [comment]
> > My general opinion is that everything should go through pull requests and stable branch should be protected and disallow pushing anything directly no matter how small changes are.
> 
> So I should:
> 
> 1. fork
> 2. commit changes to a branch of my fork
> 3. PR to merge whole thing so the branch with my changes can be merged to main later.

You can do that but it somewhat complicates few things:
* Other contributors cannot easily work on same branch.
* It is harder for others to finish abandoned work.

Both are situational of course but I would recommend, when possible, to work on dedicated branch on main repository instead of forking.

### So what would be recommended then?
When you do have direct access to repository it is better to create branch to that repository (main upstream repository) instead of forking.
Work on your branch and if needed invite others to work with you on that same branch.
When work is done create pull request from your branch to default branch.

That is better than forking because it is a lot more flexible, for example it is easier for others to help with merging and fixing simple things.
So I would recommend forking only if you do not have direct access to repository.

**Comment by El-Naso** [comment]
Then I formally request direct access to the texture repo at https://github.com/pandorabox-io/pandorabox-textures '^^

I alredy have another texture lined up (biofuel can) but I'll probably wait until tomorrow to upload it.

**Comment by OgelGames** [comment]
I think I just found how server texture packs work: https://github.com/minetest/minetest/blob/master/textures/texture_packs_here.txt
> Put your texture pack folders in this folder. Textures in the "server" pack will be used by the server.

I tested it using the `pandorabox-textures`, naming the folder "server", and the texture pack was automatically enabled.

**Comment by OgelGames** [comment]
> Then I formally request direct access to the texture repo at https://github.com/pandorabox-io/pandorabox-textures '^^

I added you (just need to accept the invite I think), I hope @BuckarooBanzay is ok with that :smile:

**Comment by BuckarooBanzay** [comment]
> Put your texture pack folders in this folder. Textures in the "server" pack will be used by the server.

Tried that, didnt work :yum: maybe i messed up some work-directory things...

> I added you (just need to accept the invite I think), I hope @BuckarooBanzay is ok with that smile

Of course :+1: 

> BTW, I like those chocolate textures, makes a lot more sense for it to be very dark chocolate considering it's made from pure cocoa yum

I just leave this here:

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJeMD_qY9--PqL3PB1wFTc8v4So35lBk6yCA&usqp=CAU"/>

**Just fyi:** i haven't done any ci/auto-update magic yet, that repository still needs to be updated manually on the server...

**Comment by El-Naso** [comment]
The chocolate texture looks dark on Github but ingame it should look ok. 
The screenshot I posted on discord is from the latest version of the texture.

**Comment by OgelGames** [comment]
> ingame it should look ok.

Yes, it looks great, I'm actually already using the `pandorabox-texures` because I cloned it into my textures folder :smile:

**Comment by OgelGames** [comment]
Texture pack is added and working, so closing this.
