### ISSUE TITLE
minetest 5.3.0 hud overlay for awards off

### ISSUE THREAD

**Issue by wsor4035** [pandorabox-io/pandorabox.io#589]
what the title says
https://cdn.discordapp.com/attachments/668090931861258250/786066198513057842/unknown.png
![image](https://user-images.githubusercontent.com/50966843/101588275-af3de180-39ee-11eb-81fe-12975fd098dc.png)

**Comment by BuckarooBanzay** [comment]
interesting :thinking:
i ~~stole~~ copied that from the awards mod, i think back then we had other rank images :yum:

**Comment by BuckarooBanzay** [comment]
:vomiting_face:  hud alignments

**Comment by wsor4035** [comment]
> 🤮 hud alignments

yup, i know
