### ISSUE TITLE
Fix scifi_nodes:light_dynamic collision box  to be same as hit box

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#590]
Hit box is fine but collision box is blocking full node.
For sure it should not block player like that, could even consider removing collisions from that node but it might be too much.

**Comment by BuckarooBanzay** [comment]
Haven't tested it, but something like that
```
	node_box = {
		type = "fixed",
		fixed = {
			fixed = {-0.5, -0.5, -0.5, -0.45, 0.5, 0.5}
		}
	},
```
After here: https://github.com/D00Med/scifi_nodes/blob/eed0d601be51b5335e3838f5135182c4e024487a/nodeboxes.lua#L477 _should_ do the trick.

**Comment by BuckarooBanzay** [comment]
fixed by https://github.com/D00Med/scifi_nodes/commit/178fd9c48b2f60801aab9865e6c8fd9d0a5417f2

**Comment by BuckarooBanzay** [comment]
https://github.com/pandorabox-io/pandorabox-mods/pull/1258
