### ISSUE TITLE
XBlocks color/wall blocks mod request

### ISSUE THREAD

**Issue by JRPete2020** [pandorabox-io/pandorabox.io#593]
To add some color blocks to the server besides wool I am requesting
https://github.com/JRPete2020/XBlocks
to be added to the server.  It brings color blocks, walls and stairs for making more colorful builds possible.

**Comment by S-S-X** [comment]
> for making more colorful builds possible.

You know that there's airbrush which can be used to change color of many nodes?

However not sure if any of those can be slabs or stairs.

**Comment by BuckarooBanzay** [comment]
> for making more colorful builds possible.

I'd rather look into how to make the already available slabs/stairs colorable
There is an api document for the `unifieddyes` mod: https://gitlab.com/VanessaE/unifieddyes/-/blob/master/API.md
Param2-type `colorfacedir` should work somehow for that... :thinking: 

The upside with that is that the node-count doesn't skyrocket and the existing textures can be used
