### ISSUE TITLE
Vanishing objects

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#595]
The content(any group of items) of objects _can vanish by digging\mining them_. They listed below:
Group: homedecore
- Kitchen Cabinet (Locked)
- Kitchen Cabinet with sink (Locked)
- Refrigerator (stainless steel) (Locked)
- Oven (stainless steel) (Locked)
- Microwave Oven (Locked)
- Desk (Locked)

**Comment by BuckarooBanzay** [comment]
Thanks for reporting, haven't dug deep enough but here are some links to some of the registrations:

`homedecor.register("refrigerator_steel", {`
https://gitlab.com/VanessaE/homedecor_modpack/-/blob/master/homedecor_kitchen/init.lua#L6

`function homedecor.register(name, original_def)`
https://gitlab.com/VanessaE/homedecor_modpack/-/blob/master/homedecor_common/registration.lua#L6

Not sure where the "locked" variants" get registered though

**Comment by Emil9736** [comment]
As for me I met this bug only with locked homedecore objects and not only full of any items.

**Comment by SwissalpS** [comment]
nightstand was mentioned too

**Comment by OgelGames** [comment]
https://gitlab.com/VanessaE/homedecor_modpack/-/merge_requests/21

**Comment by Emil9736** [comment]
Problem didn`t solved. Objects still vanish in digged locked objects of group homedecore.

**Comment by OgelGames** [comment]
> Problem didn`t solved. Objects still vanish in digged locked objects of group homedecore.

That is because the server hasn't restarted since the fix, after the next restart/crash the mod will update and be fixed 😉

**Comment by Emil9736** [comment]
> 
> 
> > Problem didn`t solved. Objects still vanish in digged locked objects of group homedecore.
> 
> That is because the server hasn't restarted since the fix, after the next restart/crash the mod will update and be fixed 😉

Ok. I`ll will wait restarting of the server :D

**Comment by BuckarooBanzay** [comment]
Nice work @OgelGames !

**Comment by SwissalpS** [comment]
yes, thanks for grinding this one @OgelGames
