### ISSUE TITLE
Stereo sound files

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#598]
Thanks to chi for [making this list](https://pastebin.furver.se/hv7v0t7xc/) of all stereo sound files used on pandorabox

**Comment by BuckarooBanzay** [comment]
For reference (https://raw.githubusercontent.com/minetest/minetest/master/doc/lua_api.txt):
```
For positional playing of sounds, only single-channel (mono) files are
supported. Otherwise OpenAL will play them non-positionally.
```

I'm not sure that happens to _all_ played sounds, for example `scifi_nodes_door_mechanic.ogg`:
```
# file scifi_nodes_door_mechanic.ogg
scifi_nodes_door_mechanic.ogg:    Ogg data, Vorbis audio, stereo, 24000 Hz, ~66666 bps, created by: Xiph.Org libVorbis I (1.3.5)
```

I'm certain i've never heard that sound globally... :thinking:

**Comment by OgelGames** [comment]
> For positional playing of sounds, only single-channel (mono) files are
supported.

Ah, of course 🤦

**Comment by SwissalpS** [comment]
aka lyrebird

**Comment by SwissalpS** [comment]
haven't heard lyrebird in a while, then again, have not been playing a lot

**Comment by BuckarooBanzay** [comment]
> haven't heard lyrebird in a while, then again, have not been playing a lot

closing then, feel free to reopen if needed
