### ISSUE TITLE
mobs_npc seem to spawn on neighbours instead of node

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#605]
My spawn areas generally are a layer of grass under a layer of the spawning node.
Often I see the mobs spawn half way inside the spawning node and instantly correct position to stand on node.
But sometimes they seem to correct downward and are stuck under the spawning layer.

From code it looks ok, but as described above, in-game it seems different.

**Comment by OgelGames** [comment]
I think that is something to do with `mobs_redo`, but I have also looked a the code before, and found nothing that should cause it... 😕

**Comment by OgelGames** [comment]
https://notabug.org/TenPlus1/mobs_redo/pulls/83
