### ISSUE TITLE
"Sent" button in webmail

### ISSUE THREAD

**Issue by 6r1d** [pandorabox-io/pandorabox.io#614]
I remembered a complaint I've heard before: `/mail` or webmail don't have a **sent** button. And it'll be really nice to have someday. (I'm saving it here so it's easier to see, but I can move the issue later.)

**Comment by Emil9736** [comment]
Rename button `Submit` ? Not **Send** ?

**Comment by OgelGames** [comment]
No, sent button as in a button to look as mails you have sent to players, an outbox.

**Comment by S-S-X** [comment]
Code for mail and should add issues there too:
Webmail: https://github.com/minetest-mail/mail
Game mod: https://github.com/minetest-mail/mail_mod

**Comment by BuckarooBanzay** [comment]
Just fyi: the outgoing mails aren't currently stored in the player's save-file but thats not a show-stopper...

**Comment by Klaranth** [comment]
Easy work around now would be to add your own name in CC.

**Comment by OgelGames** [comment]
https://github.com/mt-mods/mail/pull/26
