### ISSUE TITLE
Pistons should check protections

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#616]
Currently digiline piston does not check protection and can push to pull from protected area, not sure about mesecon pistons.
Full 1-16 nodes can be pulled or pushed to/from protected area.
Protected nodes can also be destroyed.

Pistons are not owned so that cannot be used but there's way to do checks using mesecon.mvps_push / mesecon.mvps_pull_all / mesecon.mvps_pull_single as those will get required information to check protection owner of piston and owner of pull / push position.

**Comment by TechDudie** [comment]
This is an obvious bug, I already noticed it months before, why isn’t if f1xx3d yet?

**Comment by S-S-X** [comment]
> This is an obvious bug, I already noticed it months before, why isn’t if f1xx3d yet?

Because you were so lazy and did not fix or report it.

**Comment by OgelGames** [comment]
> there's way to do checks using mesecon.mvps_push / mesecon.mvps_pull_all / mesecon.mvps_pull_single as those will get required information to check protection owner of piston and owner of pull / push position.

Looks like it already uses those functions: https://cheapiesystems.com/git/digistuff/tree/piston.lua 🤔

**Comment by S-S-X** [comment]
> > there's way to do checks using mesecon.mvps_push / mesecon.mvps_pull_all / mesecon.mvps_pull_single as those will get required information to check protection owner of piston and owner of pull / push position.
> 
> Looks like it already uses those functions: https://cheapiesystems.com/git/digistuff/tree/piston.lua 🤔

Yeah and that's why I've always just assumed that protections do work, I'm pretty sure there's been overrides for those to do some protection checks.

Digistuff pistons however are not calling `mesecon.mvps_set_owner` which it should do, simply calling that from `after_place_node` would fix protections.

**Comment by S-S-X** [comment]
Could add LBM with that to call `mesecon.mvps_set_owner` on old pistons but maybe first make sure that workaround actually works.
Then just keep issue open until upstream fixed it and after that get rid of server customizations hack.

**Comment by TechDudie** [comment]
In my defense, _because_ I found it months before, I found it before I joined pandorabox, and it kinda sank to the bottom of my memory.

**Comment by TechDudie** [comment]
This bug allows player to make a missile to blow stuff up/a vehicle to steal protected nodes, all sorts of creative ways to grief other players, due to this, I will not disclose the designs anytime soon.
