### ISSUE TITLE
stackable compasses want / want-not ?

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#634]
I've been playing around with some ideas after we got used to metatools being stackable.

There may be a wish to not give compass even more power.

And if we make them stackable what is ccompass.stack_max to be?

**Comment by SwissalpS** [comment]
[Here's a test branch](https://github.com/SwissalpS/ccompass/tree/recipeIdeaB)

**Comment by S-S-X** [comment]
Things that should be tested:
* What happens if you set metadata and inventory is full
* What happens if you set metadata and inventory slots are full but has space in stack with exact same metadata (not sure if this is possible with compass)
* What happens if you have stack of compasses in single inventory device and program compass
* Something else???

**Comment by SwissalpS** [comment]
> * What happens if you program compass and inventory is full with no space for compass with new metadata
currently they do not split off a stack like metatools do. If stack usage is enabled, then the whole stack is set to the same location. This seems to make more sense with original idea of compass mod that was introduced for treasure-hunt games.
If the option to use stacks is not enabled, then player cannot calibrate or jump with a stack in hand.

> * What happens if you program compass and inventory slots are full but has space in stack with exact same metadata (not sure if this is possible with compass)
as above, does not apply currently.
However stacking works 'out-of-the-box' from engine as follows: same data and needle point in same direction -> stackable up to ccompass.stack_max

The needle part is a bit clumsy. I don't want to add an 'on inventory change' hook to deal with this. Also not solving auto-needle alignment, helps keep some disadvantage to having compass.

> * What happens if you have stack of compasses in single inventory device and program compass
Have not tested automated, thanks for reminding me.

**Comment by S-S-X** [comment]
> Might be nice to add stack splitting behaviour for when stack usage flag is off.

This could possibly be done by modifier keys but yes I think setting whole stack is better than forcing to only affect single compass, also simpler as a little bonus. While it could make it simpler to record some route players can still also split stacks themselves if needed.

Probably not really that important feature, splitting stacks is maybe more like nice to have if there's nothing better to do... getting it right with everything is also bit complicated and needs relatively large amounts of testing.

**Comment by SwissalpS** [comment]
> > * What happens if you have stack of compasses in single inventory device and program compass

When stack usage turned off and stack activated in node breaker:
-jumping or calibrating: chat message to use single

When stack usage turned off and single activated in node breaker:
-jumping: as is, owner is teleported
-calibrating: dialog shows but data is not written to compass (nor one in player's inventory)

When stack usage turned on and stack activated in node breaker:
-jumping: owner is teleported
-calibrating: dialog shows but data is not written to compasses (nor one in player's inventory). They do not stack with new compasses until made new with reset craft action.

**Comment by S-S-X** [comment]
@SwissalpS is this already done here https://github.com/pandorabox-io/pandorabox-mods/pull/1626 or does it still need something?

**Comment by SwissalpS** [comment]
@S-S-X yes, that update allows us to enable stacking of compasses if that is what we want.

Two ways, one via custom mod setting compass fields or simpler with server config settings:
ccompass_stack_max:                 1 by default. Sets maximum stack size, 1 to 65535    ccompass_allow_using_stacks:    false by default

The first generally enables stacks up to set max size.
The second setting, if set to true, would allow setting a full stack to the same location with one click.

So the question remains, do we want or not? The software now supports it.

**Comment by S-S-X** [comment]
Stacking would be fine in my opinion and setting whole stack at once would be useful for missions and minigames.
Few players have actually asked about this (possibility to clone compasses) to be able to create a lot of compasses (to be used with missions) pointing to same location.

**Comment by SwissalpS** [comment]
stacking is a bit finiky as the direction needs to match.

Q: what max stacksize do we want? 512, 108, 99, 42 or maybe even only 8?

I'd like a large size so I can have a decent amount with me to then hand out easily. 42 would be large enough but might cause even more confusion because most items have max stack of 99 on pandorabox.

**Comment by S-S-X** [comment]
> Q: what max stacksize do we want? 512, 108, 99, 42 or maybe even only 8?

I'd say at most 99, should be enough for almost anything (you'll be sending larger amounts of anything using tubes anyway) and is pretty much standard max stack size.
Smaller than 99 maybe but I don't really see good reasons to limit it, if looking for realistic stack sizes then instead of making compass stacks smaller we should start from lead blocks, technic machines and that kind of stuff...

So I'd say 99 unless going to actually start balancing stack sizes of all items using some carefully selected rules.

**Comment by SwissalpS** [comment]
I have prepared the changes here in minetest.conf
https://github.com/pandorabox-io/pandorabox.io/pull/694

If it's preferable to enable the feature via pandorabox_custom mod, we can do that way too.

**Comment by BuckarooBanzay** [comment]
Nice work :+1: 

> If it's preferable to enable the feature via pandorabox_custom mod, we can do that way too.

If you do it via the customization mod then everybody that checks out our mod-set will have the same config/setup, with the `minetest.conf` it would still be opt-in
Both ways have ups and downs...

Merged the setting-PR, this can be closed, right? :thinking:
