### ISSUE TITLE
Connect Discord channel  to in-game channel

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/pandorabox.io#656]
Connect ideas Discord channel to in-game, so players can add ideas directly from game.

**Comment by BuckarooBanzay** [comment]
:point_right: https://github.com/pandorabox-io/pandorabox.io/pull/655 ?

**Comment by Klaranth** [comment]
There was a discussion earlier about ideas here, while in-game. Would've been nice to direct folks to it, to discuss things there and away from #main.  
That way I can also find the text easier and is it easier for me to add it here to github (and bucky's mailbox )
