### ISSUE TITLE
Soda machine black. Placing again wont help.

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#657]
Home_workshop. Soda machine is black. Dig, replace, but it black. 
![screenshot_20210518_232315](https://user-images.githubusercontent.com/53637630/118704296-65c0b080-b830-11eb-9d5d-620b72baf846.png)

**Comment by OgelGames** [comment]
I tried placing one (both on the server and in a singleplayer world), and it looks fine. Maybe try clearing your cache.

**Comment by Emil9736** [comment]
Please don`t close issue! I tried to clearing cache, bit it didn`t solved problem. 
![screenshot_20210519_141910](https://user-images.githubusercontent.com/53637630/118788640-6b101080-b8ad-11eb-830f-0513574eab5f.png)

**Comment by S-S-X** [comment]
@Emil9736 Does this happen everywhere or just in that specific location?

**Comment by Emil9736** [comment]
> 
> 
> @Emil9736 Does this happen everywhere or just in that specific location?

It happens everywhere. There are no specific conditions for this case.

**Comment by OgelGames** [comment]
I found the solution/problem; with smooth lighting off it is black, with it on it is normal.

No clue as to why though...

**Comment by OgelGames** [comment]
So decided to check the test server (still with the old version of homedecor) and the soda machine is perfectly fine with smooth lighting off, so it is related to the recent update. Also while I was there I noticed `technic:insulator_clip`'s have the same problem.

**Comment by OgelGames** [comment]
So I found the problem, the node definitions were missing `paramtype = "light"`. I've fixed the technic node already, and made a PR for the other nodes: https://gitlab.com/VanessaE/home_workshop_modpack/-/merge_requests/1
