### ISSUE TITLE
travelnet fare

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#66]
travelnet.allow_travel = function( player_name, owner_name, network_name, station_name_start, station_name_target )

* Only pay if not owned/protected

**Comment by thomasrudin** [comment]
side stepped with private travelnet destinations (P)

**Comment by kiedtl** [comment]
I cannot agree with this. Travelnet is an extremely important tool and doing this would be more likely to cause gamers to leave than stay.
