### ISSUE TITLE
Add recipe for transparent textline (textline:hud)

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox.io#663]
Textline was added but does not have recipe yet.

Either to textline mod, seems to be active and might be good option.
Or to pandorabox customization repo if needed...

I think conversion recipe from textline:lcd to textline:hud could be good enough for this as items are basically same, other just does not have background.

**Comment by S-S-X** [comment]
Alternative of course could be admin vendor (those need some cleanup too, many could be already removed as items are craftable).

**Comment by BuckarooBanzay** [comment]
> Alternative of course could be admin vendor (those need some cleanup too, many could be already removed as items are craftable).

Right, i removed one a while back, worked with the `protection_bypass` button, just fyi :wink:

**Comment by S-S-X** [comment]
Yes, I know those work with protection_bypass. Already suggested in chat before that I could update one of vendors if I could get single texline hud...

**Comment by OgelGames** [comment]
https://github.com/gbl08ma/textline/pull/8
