### ISSUE TITLE
Correct description of Mithril scythe 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/pandorabox.io#669]
The text of the scythe states

(Right-click to harvest and replant crops) 

This should be 

(Left-click to harvest and replant crops)

**Comment by OgelGames** [comment]
https://notabug.org/TenPlus1/farming/pulls/53

**Comment by OgelGames** [comment]
https://notabug.org/TenPlus1/farming/commit/70803f8aefc8c68377dc3396001a6ca7973f8372
