### ISSUE TITLE
Should we make dry grass reproducible ?

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#672]
Should we make dry grass reproducible ? Now it is not reproducible: using fertilizer on dry dirt or on dirt_with_dry_grass gives only default grass, not dry grass.

**Comment by BuckarooBanzay** [comment]
> using fertilizer on dry dirt or on dirt_with_dry_grass gives only default grass, not dry grass.

Yeah, it would be consistent if dry dirt would also yield dry grass :thinking:

**Comment by OgelGames** [comment]
I was sure this was fixed some time ago, but apparently not... 😕 

https://notabug.org/TenPlus1/bonemeal/src/master/init.lua#L96-L102
```lua
-- default biomes deco
local deco = {
	{"default:dirt_with_dry_grass", dry_grass, flowers},
	{"default:sand", {}, {"default:dry_shrub", "", "", ""} },
	{"default:desert_sand", {}, {"default:dry_shrub", "", "", ""} },
	{"default:silver_sand", {}, {"default:dry_shrub", "", "", ""} },
}
```

Created an issue for it here: https://notabug.org/TenPlus1/bonemeal/issues/16
