### ISSUE TITLE
Bridger corner beams settings 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/pandorabox.io#673]
Huhhila
Since bridger corner beams were added... should the related minetest.conf settings be considered too? Git history doesn't go far enough to see when crafting wooden bridges was enabled previously.

bridger/crafts.lua has 3 settings of which 1 is enabled in minetest.conf. Haven't counted how many craft recipes those would result in. And nodes.lua refers 3 similar disable settings for actually getting rid of the nodes, but none of those is in disabled state either.

**Comment by OgelGames** [comment]
Moved issue because it's not an idea, actually more like a bug. (also because labels :D)
