### ISSUE TITLE
Unreliable Jumpdrive Success response

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [pandorabox-io/pandorabox.io#691]
Sometimes after a jump a LUA Controller connected to the Jumpdrive is not triggered by a success message.
(Nitpicking: It may be triggered at the old location I guess but nothing can be logged to mem in the case I'm talking about)

Foremost there seem to be 2 cases of a successful jump:
1) The block the JD was in pre-jump experiences high usage.
2) The block the JD jumps to experiences high usage.
(There may be a 3rd case where either source nor target location experiences much usage but that's unproblematic AFAIK)

In the second case a LUAc never seems to register the success message the JD should send.

EDIT: Replicate by jumping with a small ship entirely within the same block at both source and target. My LUAc never logged any success message then.

**Comment by SwissalpS** [comment]
I feel like we have already started an issue on this topic, but am failing to find it.

from what I remember the missing success message does not happen on specific coordinates. It can happen at locations where the message mostly arrives at.

I've also tried to track it down in singleplayer set up logging on mod side. As far as I remember, jumpdrive mod always logged message even if luac did not.

possibly relate? https://github.com/pandorabox-io/pandorabox.io/issues/511

**Comment by FeXoR-o-Illuria** [comment]
Yes, it is absolutely possible the JD sends it but the LUAc either never receives it or is unable to do anything with it because the run is interrupted or finished when the LUAc is not at the same spot any more or whatever.

**Comment by BuckarooBanzay** [comment]
> And, yea, it's more like it happens sometimes independent of the location.

If this is an issue with the mesecons-throttling i may have a partial workaround for it: We could bump the throttling value again and see how it goes.

Background: Current cpu-hog is the `technic` mod and i think we can safely increase the max-usage for the mesecons-stuff again.
The setting is currently at 30 ms (https://github.com/pandorabox-io/pandorabox.io/blob/master/minetest.conf#L110) but i think 60 ms wouldn't hurt :shrug:

**Comment by SwissalpS** [comment]
there are two independant issues here:
1. missing success message. Was already happening before mesecons-gate
2. high penalty on mostly second jump (grasshopper mostly had low usage on every second jump and high on every other) saw similar behaviour with vacuum harvester which jumps between two fixed locations in different blocks.

**Comment by FeXoR-o-Illuria** [comment]
I jumped a ship, the target location didn't suffer any penalty ... and it still didn't get a success signal x)
Yea, pretty random though at least I found a way to reliably NOT detect the success signal and always get high usage (Added to opening post).

**Comment by BuckarooBanzay** [comment]
> I jumped a ship, the target location didn't suffer any penalty ... and it still didn't get a success signal x)

Relevant code is here: https://github.com/mt-mods/jumpdrive/blob/6f18026d5882631e9b2fd666d932356f04411478/digiline.lua#L95-L101

```lua
	-- send new message in target pos
	send_pos = targetPos
	digilines.receptor_send(send_pos, jumpdrive.digiline_rules, set_channel, {
		success = success,
		time = timeormsg
	})
```

Deferring the call by one or multiple globalsteps with `minetest.after` might help if this is one of those "stale-data" issues.

**Comment by FeXoR-o-Illuria** [comment]
Yep that commit fixed the issue. I now always get a success reply, nice!
Now let's hope people rarely set a new target within those 0.5s :p
Thank you a lot @BuckarooBanzay ! ;)

**Comment by SwissalpS** [comment]
Lately I haven't heard any complaints about either not receiving success messages nor about the mesecons penalty being a problem anymore.

Time to archive?

**Comment by BuckarooBanzay** [comment]
closing, please reopen (with a repro if possible) if the issue persists
