### ISSUE TITLE
Chat bridge migration

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#699]
I've been playing around recently with `matterbridge` (https://github.com/42wim/matterbridge) and think it _could_ be a good replacement for the current ~~hacked together app~~ chatbridge (the app/proxy, not the beerchat-mod)

The list of supported chat platforms is pretty awesome:
```
bridge between mattermost, IRC, gitter, xmpp, slack, discord, telegram,
rocketchat, twitch, ssh-chat, zulip, whatsapp, keybase, matrix,
microsoft teams, nextcloud, mumble, vk
and more with REST API (mattermost not required!) 
```

~~It has a major downside though: **direct messages/commands to ingame would not be possible anymore** (relevant issue: https://github.com/42wim/matterbridge/issues/191)~~
*EDIT*: not an issue anymore, commands/DM's can be issued over the `mtui` now (https://pandorabox.io/ui)

# Pros :+1: 
* A plethora of supported chat platforms
* Makes the current beerchat-proxy obsolete (maintenance)
* The `beerchat` mod can directly talk to the matterbridge api (https://app.swaggerhub.com/apis-docs/matterbridge/matterbridge-api/0.1.0-oas3)

# Cons :-1: 
* ~~No direct messages/commands to ingame anymore~~
  * ~~A possible workaround would be a dedicated `#commands` channel (name debateable) that can be used with `/login <tan>`~~
* Something else i'm not thinking of?

# Related issues
* https://github.com/pandorabox-io/pandorabox.io/issues/678
* https://github.com/pandorabox-io/in-game/issues/84

**Comment by S-S-X** [comment]
> No direct messages/commands to ingame anymore

This is very bad and while chat platform support looks very good I would currently see this as worse option for purpose than any proxy that can send messages to special channel (bots, direct, single end point, etc...).

> A possible workaround would be a dedicated #commands channel (name debateable) that can be used with /login <tan>

Would you be able to login in (somewhat) secure way from your chat platform? Probably not if I understood correctly... and that makes commands way less useful.

Would there be some way to make this work using bridge API? Like somehow accept message for custom delivery but drop it from normal queue.
That would still require writing new s/w piece, in any case would be better to first see if linked issue can provide even partial solution.

**Comment by S-S-X** [comment]
> Would there be some way to make this work using bridge API?

I think there might be, first time I'm really looking at `matter<anything-here>` so no experience but API seems to allow setting gateway for outgoing message.
And some docs are saying: _"A gateway here is a collection of protocols that you want to bridge."_

That might provide a way around it...

**Comment by Klaranth** [comment]
'if it ain't broke' 

What is broken in the current system?

**Comment by S-S-X** [comment]
> 'if it ain't broke'
> 
> What is broken in the current system?

Better question would be what is not broken because there's a lot of broken things in current system, you can start by looking at https://github.com/minetest-beerchat/beerchat/issues and only after that comes missing features like support for other protocols.

**Comment by BuckarooBanzay** [comment]
> Would you be able to login in secure way without writing password to public chat from your chat platform? Probably not if I understood correctly... and that makes commands way less useful.

This is still possible if you log in with a temporary access number `/remote_tan` from ingame (https://github.com/minetest-beerchat/beerchat/blob/705f2bc4d2b5a7716a97aab42e16f8f3f66c2329/web/tan.lua#L4-L11)
But everything would show up in the command channel (not sure if thats good or bad)

**Comment by BuckarooBanzay** [comment]
**bump** 

Some of the disadvantages above are a non-issue now: commands can be executed with the ui now: https://pandorabox.io/ui/

The DM/PM-Situation has not improved but it is not worse with the matterbridge in place than currently.

Are there any objections/issues now with this (before i start working on it).

**Comment by OgelGames** [comment]
One thing I'm wondering is how moderation will work with so many chat platforms, will it need to be done per-platform or will there be some other way?

**Comment by BuckarooBanzay** [comment]
> One thing I'm wondering is how moderation will work with so many chat platforms, will it need to be done per-platform or will there be some other way?

I think the discord and irc platforms are very well moderated, for matrix i think @MCLV-pandorabox might volunteer or someone else more active on that side (not me though, two chat-platforms already fill my whole attention-horizon)

**Comment by MCLV-pandorabox** [comment]
I already volunteered and have admin status on the #main channel on Matrix. When anybody(except the bot :-/ ) sends a message there, my phone bleeps. Really only #main is usable on Matrix.org and I'll do what I can to get more activity there.
Centrally managed would be ofc preferred, but I don't know if that is feasible in the short term.
