### ISSUE TITLE
Minetest 5.5.0 migration

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#711]
Engine/Game migration

* Image: https://github.com/pandorabox-io/minetest_docker/releases/tag/5.5.0-r1 (based on `5.5.0` upstream tag)

# Notable changes

* `zstd` map format (should increase performance)
* Custom async patches aren't applied on this (might impact performance)

# Related issues

* [x] https://github.com/minetest-mapserver/mapserver/pull/218
* [x] #710
* [ ] might fix https://github.com/mt-mods/jumpdrive/issues/33 (the custom engine-patch might be the cause)

# Issues

* [x] https://github.com/Lejo1/adv_keys/issues/4

**Comment by OgelGames** [comment]
Looks like `basic_debug` is not a thing now (https://github.com/minetest/minetest/commit/5da204f5bcda7a45ce17f04651627fd8a9d70a82), so we won't need to merge https://github.com/pandorabox-io/pandorabox.io/pull/680.

Also, not sure if this affects anything, but the max mapgen limit was increase by 7 nodes: https://github.com/minetest/minetest/commit/a9bccb964f6c6ffe9d4f84922d9be640e4dd2f1e

**Comment by SwissalpS** [comment]
> Also, not sure if this affects anything, but the max mapgen limit was increase by 7 nodes

Just went to north edge and dug west for 1k nodes, nothing out of the ordinary.

Ran some centrifuges at Submoonine, seems ok except I had to /grantme fly bc the beacons didn't seem to grant it to me.

**Comment by OgelGames** [comment]
Everything seems to be fine, I ran around a bit and nothing happened :)

> I had to /grantme fly bc the beacons didn't seem to grant it to me

Yep, it doesn't grant it if you can grant it yourself (it checks for the `privs` privilege).

**Comment by BuckarooBanzay** [comment]
The new release might fix some issues with "lost" mapblocks or metadata while using the jumpdrive:

After some perf-issues a while back i wrote a postgres-async patch (here: https://github.com/pandorabox-io/minetest_docker/blob/master/patches/minetest_async_pg.patch) but this might have introduced some race-condition issues while saving and retrieving a mapblock at the same time (fresh mapblock-data is in the save-queue but the engine retrieves the old one from the db directly).
The patch _should_ now not be needed anymore due to the hopefully better `zstd` compression.

**Comment by BuckarooBanzay** [comment]
closing, updated to `5.6.0-dev` (https://github.com/minetest/minetest/commit/ec9f1575121e3b064b919bca7efddfa8b0fc4e65)

fyi: the "async environment" functions are in there too (`minetest.handle_async` and `minetest.register_async_dofile`) :wink:
