### ISSUE TITLE
Git-ify the skins directory

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#733]
Create a `pandorabox_skins` repo and link it to the `skinsdb` textures folder, for easier adding and maintaining of skins.

See also: https://github.com/pandorabox-io/in-game/issues/263

**Comment by BuckarooBanzay** [comment]
I started to implement this because it's not that big of a deal, but i just realized: the `mtui` app has already a skin-update function (https://pandorabox.io/ui/#/skin).

Which one will be the master for the player skins, the self-uploaded skins from the `mtui` or the ones in git? :thinking: 
(i'm fine with either one, just asking for opinions)

**Comment by OgelGames** [comment]
Probably the simplest would be to have the player skins handled by `mtui`, and git for the global ones, then you could just git-ignore the skins starting with `player_`.

Personally I like the idea of keeping the copyright on my own skin :)

**Comment by BuckarooBanzay** [comment]
https://github.com/pandorabox-io/pandorabox_skins

**Comment by OgelGames** [comment]
I think the skinsdb textures could be ignored too, unless there's some reason to keep them there?

**Comment by BuckarooBanzay** [comment]
The git repo is currently in place of the `textures` folder of the `skinsdb` mod, i _think_ it needs some of the textures

**Comment by OgelGames** [comment]
But ignoring them wouldn't delete them, right? They would just be removed from the `pandorabox_skins` repo.

Also, they are tracked/updated by `pandorabox_mods`, so I think they *need* to be ignored. 🤔

**Comment by OgelGames** [comment]
Hmm... It seems like they have been removed... I think they might need to be put back in the folder manually, and then everything will be good.

Also I noticed there are no preview textures, and some of the old player skins are missing too...

**Comment by OgelGames** [comment]
Updating `pandorabox_mods` doesn't put them back... I think I'll stop trying to fix what I can't.

**Comment by BuckarooBanzay** [comment]
> EDIT 2: I've reverted the commit that removed the files, I'll let you sort it out whenever you've got time :) https://github.com/pandorabox-io/pandorabox_skins/commit/11f6359f4ce308e78d79d1938ab95690bcfa74d8

Uhm, so how do we sort this out? I still think the additional textures don't really hurt and adding a copy-job feels kinda hacky :/ suggestions?

**Comment by OgelGames** [comment]
Revert the revert commit (https://github.com/pandorabox-io/pandorabox_skins/commit/11f6359f4ce308e78d79d1938ab95690bcfa74d8), and then restore the files by running `git restore .` in the skinsdb folder. (not the textures folder)

This is only a one-time thing, then it will work exactly the same as ignoring the `player_*` skins.

**Comment by BuckarooBanzay** [comment]
done :+1:
