### ISSUE TITLE
Protect quarry from manipulations

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#77]

**Comment by thomasrudin** [comment]
Related: https://github.com/minetest-mods/technic/pull/468

**Comment by Lejo1** [comment]
Will do
Technic PR

**Comment by Lejo1** [comment]
added to: minetest-mods/technic/pull/468

**Comment by thomasrudin** [comment]
That was just a note for me, but cool :smile:
