### ISSUE TITLE
[BUG](Web UI) Unable to view player list and player profile does not load

### ISSUE THREAD

**Issue by Monniasza** [pandorabox-io/pandorabox.io#781]
To reproduce this bug, log in to the Web UI and open player list.

The player list won't load and your profile bar also won't load

**Comment by SwissalpS** [comment]
my profile loads just fine

player search works fine and shows the players' profiles

however I can confirm that player list and command shell seem to wait for a response.

let's retest in a couple hours, if it still doesn't load, we can file an issue on the corresponding repo

**Comment by Monniasza** [comment]
It still doesn't work

**Comment by BuckarooBanzay** [comment]
should work now after i restarted it, filed a bug for future me here: https://github.com/minetest-go/mtui/issues/149

**Comment by SwissalpS** [comment]
yep, working on my end too

**Comment by Monniasza** [comment]
It works!
